### ISSUE TITLE
[Feature]: Add the ability to choose a zone instead of a specific location to avoid `resource_unavailable`

### ISSUE THREAD

**Issue by jggoebel** [hetznercloud/terraform-provider-hcloud#1003]
### What whould you like to see?

When creating a `hcloud_server` i sometimes do not care about the specific location the server is created at. Some locations tend to have unavailable resources (Like `nbg1` currently does not have type `cx42` available.)

Why not introduce a `network_zone` field that would accept `eu-central` and choose `nbg1`, `fsn1` or any other location inside that region that can fulfill this server_type?

This propably requires changes to the hetzner api but it would improve our workflow. Currently we sometimes run into this issue and have to manually switch to another location where server_type is available

**Comment by apricote** [comment]
Thanks for the suggestion @jggoebel.

You can already omit the `datacenter` and `location` arguments and then the API will use the currently recommended datacenter. Not sure how this handles out of stock server types though.

I have added this request to our internal feedback tracker.

As the terraform provider can only implement APIs that already exists, I will close this issue.

**Comment by jggoebel** [comment]
Yes i know that - the problem with that is i do not want the servers to be placed in the us-west, us-east or ap-asia but specifially in eu-central (or any other eu based locations) because of data privacy.
