### ISSUE TITLE
[Bug]: warning about attribute `allow_deprecated_images`

### ISSUE THREAD

**Issue by KiaraGrouwstra** [hetznercloud/terraform-provider-hcloud#1011]
### What happened?

using this provider with `TF_LOG=warn`, i end up getting a few messages about `allow_deprecated_images`, an attribute i hadn't passed myself:

```
2024-10-13T14:21:11.838+0200 [WARN]  Provider "registry.opentofu.org/hetznercloud/hcloud" produced an invalid plan for hcloud_server.my_server, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .allow_deprecated_images: planned value cty.False for a non-computed attribute
```

### What did you expect to happen?

no warning

### Please provide a minimal working example

```
resource "hcloud_server" "my_server" {
  name        = "node1"
  image       = "debian-11"
  server_type = "cx22"
  public_net {
    ipv4_enabled = true
    ipv6_enabled = true
  }
}
```

**Comment by jooola** [comment]
Hey,
The only way for us to fix those warnings is to migrate our resources to the new plugin framework, which is currently being worked on (see #752). You can find additional details about those warnings here: https://github.com/hashicorp/terraform-plugin-sdk/issues/1227

You can safely ignore those warnings. Closing as not planned, as it will resolve itself when migrating to the plugin framework.
