### ISSUE TITLE
[Bug]: FLAG delete_protection - when TRUE cant destroy resources

### ISSUE THREAD

**Issue by KlockiLego** [hetznercloud/terraform-provider-hcloud#1014]
### What happened?

```
resource "hcloud_primary_ip" "primary_ipv4_cp_02" {
  name              = "primary_ipv4_cp_02"
  datacenter        = "fsn1-dc14"
  type              = "ipv4"
  assignee_type     = "server"
  auto_delete       = false
  delete_protection = true
  }
```

The documentation is misleading:
https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs#delete-protection

When `delete_protection` is TRUE then OpenTofu cannot delete the resource. It is `Destroying....` forever.

### What did you expect to happen?

Delete resources as documented.
https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs#delete-protection

### Please provide a minimal working example

```
resource "hcloud_primary_ip" "primary_ipv4_cp_02" {
  name              = "primary_ipv4_cp_02"
  datacenter        = "fsn1-dc14"
  type              = "ipv4"
  assignee_type     = "server"
  auto_delete       = false
  delete_protection = true
  }
```

**Comment by jooola** [comment]
Thanks for the report, this should be fixed with #1015.
