### ISSUE TITLE
[Feature]: hcloud_server should be able to attach to subnet

### ISSUE THREAD

**Issue by pscloud-patrick** [hetznercloud/terraform-provider-hcloud#1063]
### What whould you like to see?

When creating an `hcloud_server` ressource, it's only possible to attach the server to a network, but no to a subnet. Therefore I need to explicitly set the IP adress to one of the subnets. So I need to maintain the IP pool. Thats very uncomfortable

**Comment by jooola** [comment]
Closing as duplicate of https://github.com/hetznercloud/terraform-provider-hcloud/issues/672
