### ISSUE TITLE
No example for user_data, and I can't make it work.

### ISSUE THREAD

**Issue by afandian** [hetznercloud/terraform-provider-hcloud#11]
I am trying to use user_data to set up an initial username. There is no example of how to use it in the [documentation](https://www.terraform.io/docs/providers/hcloud/r/server.html). I have tried to do something like this:

```
resource "hcloud_server" "my_server" {
  name        = "docker-leader"
  image       = "ubuntu-18.04"
  server_type = "cx51"
  ssh_keys    = ["${hcloud_ssh_key.my_key.id}"]
  user_data = "${file("my-file.yaml")}"
}
```

But it just seems to fail silently. I assume the functionality works, but I don't know how to use it.

Could you please include a working example?

**Comment by thetechnick** [comment]
Hi @afandian,
you can find a working example in the Hetzner Cloud API docs:
https://docs.hetzner.cloud/#servers-create-a-server

```
#cloud-config
runcmd:
- [touch, /root/cloud-init-worked]

```

I would also recommend to have a look at the cloud init docs: http://cloudinit.readthedocs.io/en/latest/

**Comment by LKaemmerling** [comment]
@afandian when you still have a problem with this, feel free, to reopen this issue.

**Comment by jeff1985** [comment]
I had the same problem and after some debugging it turns out, that it is important to have the header line inside the user data, otherwise the config will be ignored!

```
#cloud-config
here your config goes
```

**Comment by jceb** [comment]
@LKaemmerling @thetechnick The hint regarding the `#cloud-config` header would make great addition to the docs. I also struggled to make it work for the same reason.
