### ISSUE TITLE
Don't destroy and recreate server when trivial changes made to user_data file

### ISSUE THREAD

**Issue by rightaway** [hetznercloud/terraform-provider-hcloud#110]
I have added some comments to my user_data file, and because of this the user_data hash in the tfstate file has changed, so it wants to destroy and recreate the server. But this isn't necessary because only comments were changed. This also applies if other trivial changes were made like to spacing or formatting.

There should be a way to tell it to update the tfstate file with the new hash of the user_data file.

If I manually update all the user_data hash values throughout the tfstate file it works, but there could be many occurrences and having to do this manually every time I make a trivial change to user_data file would be very unproductive.

**Comment by LKaemmerling** [comment]
This is something we can not control in the Provider. This can only be fixed in Terraform itself because terraform says our provider that the property has changed.

**Comment by rightaway** [comment]
I can create an issue for it. Would it go in the main terraform repo? And is it specific to user_data or any use of a file? If you could give me a sentence or two that describes the issue better than I know it I can add it to the issue so they'll know it's not specific to this provider. (Or you can create the issue directly, I just don't want to put it on you.)

**Comment by LKaemmerling** [comment]
After looking more into this I can say this works as indeed. You change the user_data file, so it has another hash. We can not know what your change was if it was trivial or a breaking change, so we assume it is a breaking change always.

**Comment by rightaway** [comment]
I know, that's why I'd like to create an issue in terraform to add a command to tell it to update the hash if we know that it's a trivial change. We'd already be doing the same thing manually (changing every hash by hand) if we know it's a trivial change. I'd just like to request them for a more automated way.

**Comment by LKaemmerling** [comment]
I really can't tell you if the terraform guys can help with this issue. We calculate the hash in our provider. I guess the easiest way would be to change it by hand. I guess in most cases the change of a user_data file will be a breaking change.
