### ISSUE TITLE
Removing hcloud_volume_attachment and setting server_id in hcloud_volume

### ISSUE THREAD

**Issue by rightaway** [hetznercloud/terraform-provider-hcloud#111]
If I remove `hcloud_volume_attachment` and set `server_id` to that same server from the volume attachment in `hcloud_volume`, it actually detaches the volume from the server, even though nothing has really changed. I'm just defining the exact same outcome but in a different way.

If I run the plan again it says there are no changes. This seems wrong. The volume which has `server_id` isn't getting attached to that server.

**Comment by rightaway** [comment]
And in the other direction, if I'm adding `hcloud_volume_attachment` to reflect something that already exists, then I get `Error: volume is already attached to a server, please detach it first (service_error)`. It's attached to a server, but it's the same server defined in the configuration. Why is it complaining?

**Comment by LKaemmerling** [comment]
You need to know that terraform always tries to achieve the state you describe in your code, by defining resources. When you delete the `hcloud_volume_attachment` resource it detaches the server when you then set the server_id it uses the other resource `hcloud_volume`.

I guess you should read a little bit more about terraform and its principles.
