### ISSUE TITLE
error when trying to add server to private network subnet

### ISSUE THREAD

**Issue by fessmage** [hetznercloud/terraform-provider-hcloud#117]
I got error `Error: Incorrect attribute value type` `Inappropriate value for attribute "network_id": a number is required.` when tried to add hcloud server to subnet in private network.

Example config:
```
resource "hcloud_network" "net" {
    name     = "net"
    ip_range = "10.1.0.0/16"
}

resource "hcloud_network_subnet" "subnet" {
    network_id   = "${hcloud_network.net.id}"
    type         = "server"
    network_zone = "eu-central"
    ip_range     = "10.1.1.0/24"
}

resource "hcloud_server_network" "server-net" {
     server_id  = "${hcloud_server.server.id}"
     network_id = "${hcloud_network_subnet.subnet.id}"
 }
```
and output:
```
Error: Incorrect attribute value type

  on staging.tf line 37, in resource "hcloud_server_network" "server-net":
  37:     network_id = "${hcloud_network_subnet.subnet.id}"

Inappropriate value for attribute "network_id": a number is required.
```
and this is output of variables from private network and subnet:
```
Outputs:

net = [
  {
    "id" = "18810"
    "ip_range" = "10.1.0.0/16"
    "labels" = {}
    "name" = "staging-net"
  },
]
subnet = [
  {
    "gateway" = "10.1.0.1"
    "id" = "18810-10.1.1.0/24"
    "ip_range" = "10.1.1.0/24"
    "network_id" = 18810
    "network_zone" = "eu-central"
    "type" = "server"
  },
]
```

As far as i understood from error text, resource `hcloud_server_network` expect integer for network_id parameter, but as you can see from output, id of subnet is not integet, but a string.

**Comment by LKaemmerling** [comment]
You need to specify the network ID (from you sample `net.id`) not the subnet id.

**Comment by fessmage** [comment]
What if i have two subnets and two servers?First server must use subnet 1, second - subnet 2.
Your suggestion works only for one subnet in private network.

**Comment by LKaemmerling** [comment]
This works for any setup. You have two ways how IP addresses will be allocated.  You can let our system choose over all subnets or specify a specific ip.

**Comment by fessmage** [comment]
That seems not good enough...
Honestly, I expected something different from this network concept - creating one private network, divide it to subnets and then just allocate subnets to all instances of some types. Setting it manually makes this subnets concept almost useless. 
This is limitation of hcloud api, am i right? In that case, there is nothing we can do from terraform side, until api changes.

**Comment by LKaemmerling** [comment]
This is the concept of how we see the subnets. At the moment the subnets are mostly useless, but there are use cases in the future where it makes sense to have this concept.

**Comment by fessmage** [comment]
Ok, thanks Lucas!
