### ISSUE TITLE
Support the new "Network" feature?

### ISSUE THREAD

**Issue by rbjorklin** [hetznercloud/terraform-provider-hcloud#122]
Hetzner announced a new feature in July, [Networks](https://www.hetzner.com/news/07-19-networks-beta/). Is support for this in the works?

For reference: [FAQ](https://wiki.hetzner.de/index.php/CloudServer/en#Networks).

**Comment by LKaemmerling** [comment]
There is already support available as of 1.11.0 (July 2019): https://github.com/terraform-providers/terraform-provider-hcloud/blob/master/CHANGELOG.md#1110-july-10-2019 (latest Version is 1.13.0)
