### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by nielsole** [hetznercloud/terraform-provider-hcloud#13]
Currently the only option to install the provider is to install it from source. While that is literally 4 lines of code it requires setting up a Go environment. It would be easier to just include binaries for at least macOS and linux.

EDIT: Just looking at other providers, not including binaries seems to be the norm. Is this correct? Then I will just close the ticket.

**Comment by madebyherzblut** [comment]
The binaries for providers in this org are distributed by [Hashicorp](https://releases.hashicorp.com/terraform-provider-hcloud/) directly and downloaded automatically when you run `terraform init` 🙂
