### ISSUE TITLE
How to associate an `hcloud_server` with a project?

### ISSUE THREAD

**Issue by pavlo** [hetznercloud/terraform-provider-hcloud#13]
Hey guys, it is rather a question, not an issue per se.

Say I have a couple of projects created manually via https://console.hetzner.cloud/projects interface. Is there way then to specify which of them would the `resource "hcloud_server" "node"` associated with?

Thank you!

**Comment by thetechnick** [comment]
Hi @pavlo,
when you want to use the Hetzner Cloud API you need an access token.
ProjectTokens can be created in the cloud console:

![screencapture-console-hetzner-cloud-projects-4127-access-tokens-1517424357481](https://user-images.githubusercontent.com/7278896/35641292-0b63a7e8-06c0-11e8-9f6a-06cf3088fb1c.png)

These tokens are bound to the project they are created in and there is no support (yet) for API credentials spanning multiple projects.
This means that the token you configure the terraform provider with also specifies in which project terraform works.

```
# Configure the Hetzner Cloud Provider
provider "hcloud" {
  token = "${var.hcloud_token}"
}
```

Projects in the Hetzner Cloud are to separate invoices and permissions when inviting multiple users.
In the future we want to enable users to tag/label all resources to better organize your stuff in an project.

**Comment by pavlo** [comment]
Thank you a lot! I had an API token though did not realize it was bound to a project. 

Thanks for your help!

**Comment by thetechnick** [comment]
I am glad to help
