### ISSUE TITLE
hcloud_server resource should probably use hash for user_data

### ISSUE THREAD

**Issue by jcassee** [hetznercloud/terraform-provider-hcloud#14]
When using `plan` or `apply`, the `aws_instance` resource uses the hash of the `user_data` attribute. Instead the `hcloud_server` resources displays the value itself. The value can become very and might contain sensitive data. 

Compare [resource_hcloud_server.go](https://github.com/hetznercloud/terraform-provider-hcloud/blob/74b3b088bcb4ccb8919f55e83e113de8dc1a2a26/hcloud/resource_hcloud_server.go#L48) and [resource_aws_instance.go](https://github.com/terraform-providers/terraform-provider-aws/blob/b82247b1d1270097aaf1e746749d958525bbdff5/aws/resource_aws_instance.go#L106).

Unfortunately, I know too little Go to create a pull request myself.

By the way, 🙇 for creating a Terraform provider for Hetzner Cloud so soon! Absolutely prompted me to jump in.

**Comment by thetechnick** [comment]
Hi @jcassee,
thanks for your report.
I will look into this, looks like a good change to implement.
