### ISSUE TITLE
hcloud_server create returns errors

### ISSUE THREAD

**Issue by yaffol** [hetznercloud/terraform-provider-hcloud#140]
In the last couple of days, when creating 2 cloud server instances with the hcloud_server module, I've experienced the first instance creating correctly, then either failures with a return of 'Unknown error', or the next instance be stuck in the 'Still creating...' phase for a very long time - like 10 minutes until I killed the process.

The other factor is that I have also been forcing these instances to re-create by calling terraform taint on them, eg:
`terraform taint  hcloud_server.tinc2 `

When I get the 'unknown error', the instance has not been created, nor can I see it in the Hetzner cloud console.
However, when the instance is stuck on 'Still creating...' I see the server is created and fully operational within the cloud console.

I have enabled TF_LOG at debug, but don't see a great deal of useful information at this stage.

```
hcloud_server.tinc2: Still creating... [12m10s elapsed]
hcloud_server.tinc2: Still creating... [12m20s elapsed]
```

The terraform module config for the instances is:

```
resource "hcloud_server" "tinc1" {
  name        = "${local.name_prefix}tinc1"
  image       = data.hcloud_image.ubuntu_18-04_docker.id
  server_type = "cx21-ceph"
  user_data   = data.template_file.cloud_init_ansible_user.rendered
  labels      = {
    "tinc" = "yes"
  }
}

resource "hcloud_server" "tinc2" {
  name        = "${local.name_prefix}tinc2"
  image       = data.hcloud_image.ubuntu_18-04_docker.id
  server_type = "cx21-ceph"
  user_data   = data.template_file.cloud_init_ansible_user.rendered
  labels      = {
    "tinc" = "yes"
  }
}
```

I know that creating an instance from a custom snapshot can take a lot longer than from one of the 'default' OS images, so I wondered if it was related to that and timeouts somewhere along the line, but I'm not sure how to properly debug this - very happy to provide whatever extra information I should.

It is possible to sort the state out by deleting the server manually in the cloud console, but it's a bit of a faff to have to do it, and I'd like to know what's really going on!

**Comment by yaffol** [comment]
OK I think this *may* be related to #138 although I'm pretty sure I got the error first, and then enabled TF_LOG to try to find out more what's going on, but I can't be sure.

I also have enabled a logging path with TF_LOG_PATH and will monitor the files to see if I can find anything more about what's going on.

**Comment by LKaemmerling** [comment]
If you encounter these errors again, would it be possible to open up a support ticket with the attached TF Log file?  Could you run TF like:
`TF_LOG=all TF_LOG_PATH=log.txt terraform apply` ? This will output a log.txt file.

**Comment by LKaemmerling** [comment]
Looks like this was a temporary issue. I will close the issue. If you encounter the same problem again, feel free to open the issue again.
