### ISSUE TITLE
Error: entered token is invalid (must be exactly 64 characters long)

### ISSUE THREAD

**Issue by Beenhakker** [hetznercloud/terraform-provider-hcloud#144]
Hi,

I am switching to Hetzner, and while running `terraform plan` the first time, I get the error you see in the title.

After `wc` the API-key, I can see it's 65 characters long. I regenerated it three times, with the same result. Also tried to shorten it with 1 character, but tough luck.

Am I missing something?

Kind regards

**Comment by LKaemmerling** [comment]
All Hetzner Cloud Tokens have a length of exactly 64 chars. Please try it again with copy&paste the token from the Cloud Console.

**Comment by Beenhakker** [comment]
Hi,

They don't, otherwise I would have not opened this issue, that's why I am asking.

Again, in more detail:
I am logged in to https://console.hetzner.cloud/ - access - API tokens - generate API token

This is what I get:
```
$ echo c61iu7rOJasN9PTdJTXHzrt1YFHZN5iIQVuWVb2v9mKxK8Xoj8RzJX3ksv33YnKn|wc
       1       1      65
```
It's 65 chars long, not 64.
