### ISSUE TITLE
Error: entered token is invalid (must be exactly 64 characters long)

### ISSUE THREAD

**Issue by Beenhakker** [hetznercloud/terraform-provider-hcloud#149]
Hi,

I could not re-open the existing issue, so here it is again with proof.

---

The keys generated are not 64 characters in my case, otherwise I would have not opened this issue.
Maybe someone can tell me if I am doing something wrong.

I am logged in to https://console.hetzner.cloud/ - access - API tokens - generate API token
This is what I get:
```
$ echo c61iu7rOJasN9PTdJTXHzrt1YFHZN5iIQVuWVb2v9mKxK8Xoj8RzJX3ksv33YnKn|wc
       1       1      65
```
It's 65 characters long, not 64. (key has been deleted)

**Comment by LKaemmerling** [comment]
When I count your string it is exactly 64 chars long.  `c61iu7rOJasN9PTdJTXHzrt1YFHZN5iIQVuWVb2v9mKxK8Xoj8RzJX3ksv33YnKn`

![Bildschirmfoto 2020-02-10 um 06 17 04](https://user-images.githubusercontent.com/4281581/74122871-fa1f7a80-4bcc-11ea-951c-31298ac473d7.png)


All Hetzner Cloud Token are always exactly 64 characters long.

**Comment by rk-p2p** [comment]
Something's wrong with checking the length of the API key.
I enter my 64 character API key and still get the error `Error: entered token is invalid (must be exactly 64 characters long)`.
@LKaemmerling Can you check it out?

**Comment by LKaemmerling** [comment]
Are you sure that your token is exactly 64 chars long?  All tokens are exactly 64 chars long, there is no exclusion of this rule.

**Comment by rk-p2p** [comment]
Yes, I'm sure.
![image](https://user-images.githubusercontent.com/56305239/78064272-ec0b0080-73aa-11ea-9c91-e4c0ed873638.png)

**Comment by LKaemmerling** [comment]
Maybe there is a whitespace or another special char in your tf file. Actually, the validation just checks if that what it receives it exactly 64 chars long, not more or less. The must be an issue within your terraform file.

**Comment by rk-p2p** [comment]
I enter the key interactively on `terraform apply`. There is no whitespaces or special chars.
![image](https://user-images.githubusercontent.com/56305239/78064923-efeb5280-73ab-11ea-9e54-55f7475f4732.png)
Versions:
```
Terraform v0.12.20
+ provider.hcloud v1.16.0
```

**Comment by rk-p2p** [comment]
I have found the reason.
My terraform file was like:
```hcl
variable "hcloud_token" {}

provider "hcloud" {
  token = "${var.hcloud_token}"
}

resource "hcloud_server" "terraform-test" {
  name = "terraform-test1"
  image = "debian-10"
  server_type = "cx11"
  location = "nbg1"
} 
```
When i execute `terraform apply` i receive warning:
```
Warning: Interpolation-only expressions are deprecated

  on hcloud.tf line 3, in provider "hcloud":
  3:   token = "${var.hcloud_token}"
...
remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.
...
```
and I set `token = "var.hcloud_token"`. *facepalm*
Sorry to bother you and thank you for your help.

**Comment by bizmate** [comment]
i get the 

`Error: entered token is invalid (must be exactly 64 characters long)`
if i dont use the interpolation reference. So if i run it with `token = "var.hcloud_token"`

I get the error but if i run it with `token = "${var.hcloud_token}"` i get

```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # hcloud_server.rancher will be created
  + resource "hcloud_server" "rancher" {
      + backup_window = (known after apply)
      + backups       = false
      + datacenter    = (known after apply)
      + id            = (known after apply)
      + image         = "ubuntu-18.04"
      + ipv4_address  = (known after apply)
      + ipv6_address  = (known after apply)
      + ipv6_network  = (known after apply)
      + keep_disk     = false
      + location      = (known after apply)
      + name          = "myreviews-rancher"
      + server_type   = "cx11"
      + status        = (known after apply)
    }

  # hcloud_ssh_key.default will be created
  + resource "hcloud_ssh_key" "default" {
      + fingerprint = (known after apply)
      + id          = (known after apply)
      + name        = "main ssh key"
      + public_key  = "file('~/.ssh/id_rsa.pub')"
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Warning: Interpolation-only expressions are deprecated

  on main.tf line 11, in provider "hcloud":
  11:   token = "${var.hcloud_token}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.


------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

```
is it possible there is a bug when interpolation is not used?

**Comment by LKaemmerling** [comment]
@bizmate: Could you try `token = var.hcloud_token` ?

**Comment by gawsoftpl** [comment]
Your HCLOUD_TOKEN has white lines on the end:

```sh
# Load hcloud_Token from file
export HCLOUD_TOKEN=$(sed 's/[\r\n]*$//' /path/to/hcloud_token)
```

```sh
# Test token
echo -n $HCLOUD_TOKEN | od -c  
0000000   A   v   T   a   P   g   P   B   l   G   T   Z   S   S   R   z
0000020   C   B   o   M   n   9   K   o   F   j   l   F   F   q   9   m
0000040   V   F   z   t   r   r   B   p   a   2   A   A   z   6   8   G
0000060   4   r   f   H   T   t   k   W   P   0   4   w   p   b   v   q
0000100  \n
0000101
```

If you have `0000100  \n` this line breaks all

**Comment by youurayy** [comment]
can happen in iTerm2 during hcloud setup (`hcloud context create default`) when "paste bracketing" was left turned on by an app.
just paste into bash and iTerm will offer turning paste bracketing off.
