### ISSUE TITLE
Alias IPs on hcloud_server_network not assigned

### ISSUE THREAD

**Issue by seimic** [hetznercloud/terraform-provider-hcloud#154]
Hi,

assigning of Alias IPs on a server network seems not to work.  

```
resource "hcloud_server_network" "node01_net" {
  server_id = hcloud_server.node01.id
  network_id = hcloud_network.network01.id
  ip = "10.0.0.10"
  alias_ips = ["10.0.0.2"]
}
```

Kind regards,
Michael

**Comment by LKaemmerling** [comment]
Alias IPs are never assigned. You need to configure them manually on the cloud server. See: https://wiki.hetzner.de/index.php/CloudServer/en#networks_server_multiple_ips

**Comment by seimic** [comment]
The API has this functionality: https://docs.hetzner.cloud/#server-actions-attach-a-server-to-a-network
This works in hcloud-cli and in rest api but not in terraform.
The terraform documentation for the hcloud_server_network states this option is available... but has no effect at all.
https://www.terraform.io/docs/providers/hcloud/r/server_network.html

Configuring the interface at OS level is different thing, must be done manually. You are right in this.
Like this for example:
```
auto ens10:1
    iface ens10:1 inet static
      address ${alias_ip}
      netmask 32
```
This can be configured at multiple nodes in cluster at same time. Only the one which has the alias ip assigned, has this address available. Works like floating IP but in local network.
At now I assign the alias IP initially in cloudinit using the API because in terraform this option didn't work (alias_ips argument is ignored). Not a big thing but if documentation states it works I though its a bug when it doesn't.

**Comment by LKaemmerling** [comment]
Yep you are right, this is a bug within the terraform provider. I will prepare a fix.

**Comment by seimic** [comment]
Thank you very much.

**Comment by LKaemmerling** [comment]
@seimic v1.16.0 was released which contains a fix for this
