### ISSUE TITLE
hcloud_server.ingress: server limit exceeded (resource_limit_exceeded)

### ISSUE THREAD

**Issue by valentinbud** [hetznercloud/terraform-provider-hcloud#16]
I have 10 servers in default project, nine of them created using terraform. 

<img width="1680" alt="projects" src="https://user-images.githubusercontent.com/3338528/35840333-3e832a44-0afe-11e8-9613-bcf452e96f03.png">

In my last last I got the following error:

```
Error: Error applying plan:

1 error(s) occurred:

* hcloud_server.ingress_worker[0]: 1 error(s) occurred:

* hcloud_server.ingress_worker.0: server limit exceeded (resource_limit_exceeded)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```

Is the resource limit adjustable? Are you willing you make it a little bit bigger, maybe double?

Please advise me how to proceed. Thank you.

**Comment by thetechnick** [comment]
Hi @valentinbud,
our low prices unfortunately attract some scammers/spammers, so we limit the amount of servers for a new customer to 10. If you want to increase these limits, please open a ticket in the [Cloud Console](https://console.hetzner.cloud/support). Our support will then increase your limits accordingly.

Depending on your needs a brief description of your use case for the servers will speed up the process.

**Comment by valentinbud** [comment]
Hi @thetechnick,

I will open up a ticket. I am glad the limits can be increased. I am also going to provide a brief description of my use case along with the request as you've suggested.

I use this opportunity to thank you for all the work invested in making this provider a reality. It made my life way much easier and far more enjoyable. 

I am curious what's coming next :).
