### ISSUE TITLE
Extend the list of supported server types by the recently introduced CPX family

### ISSUE THREAD

**Issue by pa-yourserveradmin-com** [hetznercloud/terraform-provider-hcloud#160]
The 1.16.0 release lacks CPX servers in the list of supported. How to reproduce: just try to create new `hcloud_server` instance of type, for example, `cpx31-ceph` and you will receive error on _apply (not validate)_ step:

```
 Error: server type 'cpx31-ceph' not found (invalid_input)
   on modules/default/main.tf line 11, in resource "hcloud_server" "instance":
   11: resource "hcloud_server" "instance" {
```

**Comment by LKaemmerling** [comment]
A `cpx31-ceph` is not available. Our new CPX family doesn't have the ceph option atm.

**Comment by pa-yourserveradmin-com** [comment]
Sorry, you're right, found this in two minutes after your reply! Thank you!
