### ISSUE TITLE
Terraform destroy does not clear resources

### ISSUE THREAD

**Issue by DanielMSchmidt** [hetznercloud/terraform-provider-hcloud#162]
Hey there,

First of all thank you for this great project, it was awesome to work with so far!

I have a fairly simple project that provisions some `hcloud_server` and I noticed that when we use `terraform destory` the resources are still available in the hetzner cloud interface, but terraform reports that the resources are still present. I would expect the resources to be destroyed

**Comment by DanielMSchmidt** [comment]
I also saw a problem regarding creating the new resources, I see the servers as available through the API but terraform never picks them up.

**Comment by DanielMSchmidt** [comment]
Okay, I tried a few more things today, it seems to be the same problem in the last three versions. Spinning up one instance works just fine and completely reliable, more then one creates the instances and terraform fails reliably

**Comment by LKaemmerling** [comment]
Could you use the building logging functionality to generate a log?
``TF_LOG=DEBUG TF_LOG_PATH=apply_log.txt terraform apply``
``TF_LOG=DEBUG TF_LOG_PATH=delete_log.txt terraform destory``

This will generate a apply_log and a delete_log.txt. Could you send me both logs via e-mail to lukas.kaemmerling@hetzner-cloud.de? Please keep in mind that these log files contain the API token, so please never upload them to a public place (like Github).

**Comment by DanielMSchmidt** [comment]
I was trying to reproduce this, but today I could not, everything runs just fine with 1 or 6 instances. I will add some logs and reopen the issue if it occurs again 👍
