### ISSUE TITLE
Configure servers with floating ips

### ISSUE THREAD

**Issue by miracle2k** [hetznercloud/terraform-provider-hcloud#18]
I'm new to Terraform. I want to create, say, 5 servers, each of which has 3 floating ips. This works, using essentially`${element(servers, count.index}` for the floating ips to divide them across the servers.

I want to also have each instance be configured to support the ips assigned to it (i.e. write a`/etc/network/interfaces.d` file). I can't make this part work.

I've tried to:

- Convince Terraform to generate a cloudconfig.
- Convince Terraform to pass the right ips to a provisioner.

The first thing I struggle with is figuring out how to get all the ips for each individual server, given the strategy of how they are assigned via `element()`. Terraform doesn't seem powerful enough to do this. So my plan is to simply pass *all* floating ips generated to every server, along with the server index, and then let the script on that server figure out which of those ips Terraform would have assigned, replicating the logic.

However, I can't get beyond a cycle error:

```
resource "hcloud_server" "vm" {
  count = "${var.num_vms}"
  name = "vm-${count.index+1}"
  image = "debian-9"
  server_type = "cx11"
  ssh_keys = ["${hcloud_ssh_key.default.id}"]

  provisioner "file" {
    source      = "setup-extra-ips.sh"
    destination = "/tmp/setup-slave-ips.sh"
  }

  provisioner "remote-exec" {
    inline = [
        "/tmp/setup-slave-interfaces.sh ${join(" ", hcloud_floating_ip.extra-ip.*.ip_address)}"
    ]

    connection {
      type     = "ssh"
      user     = "root"
      private_key = "${file("~/.ssh/id_rsa")}"
    }
  }
}
```

Says:

```
* Cycle: hcloud_floating_ip.extra-ip, hcloud_server.vm
```

I wonder if anyone has ideas of how to do this?

**Comment by thetechnick** [comment]
Hi @miracle2k,
I think the cycle arises, because the floating ip needs the server to be created (server id) and the server needs the floating ip to be created (for the provisioner).

To resolve the loop you can first create the floating ips without assigning them and edit the terraform config to assign them afterwards.

**Comment by miracle2k** [comment]
I managed to solve this using a null_resource.

**Comment by patrickvale** [comment]
Hi @miracle2k could you post the configuration using the null_resource? It would be really interesting to see the working version! Thanks!

**Comment by miracle2k** [comment]
It ended up quite hacky:

```
resource "null_resource" "slave-ip-enable" {
  count = "${var.num_slaves}"
  
  provisioner "file" {
    source      = "setup-slave-interfaces.sh"
    destination = "/tmp/setup-slave-interfaces.sh"
  }

  provisioner "remote-exec" {
    inline = [
        "chmod +x /tmp/setup-slave-interfaces.sh",
        "/tmp/setup-slave-interfaces.sh \"${join(" ", hcloud_floating_ip.slave-ip.*.ip_address)}\" ${count.index} ${var.num_slaves}",
        "/etc/init.d/networking restart"
    ]    
  }

  connection {
    host = "${element(hcloud_server.slave.*.ipv4_address, count.index)}"
    type = "ssh"
    user = "root"
    private_key = "${file("~/.ssh/id_rsa")}"
  }
```

```
#!/bin/bash

set -e

IPS="$1"
THIS_SERVER_INDEX="$2"
THIS_SERVER_TOTAL="$3"
	

# From Terraform we get ALL ips for ALL servers. This is becaues the Terraform
# language does not seem powerful enough to give us only those ips that have
# been assigned to us.
#
# What happens is we create 2 servers with 3 ips each, so 6 ips. We then
# use element(servers, count.index) within the ip resource to assign the
# first ip to the first server, the second ip to server nr 2, the third
# ip again the the first server.
#
# We now have to untangle this.
MY_IPS=$(python3 -c "import sys; _, ips, idx, total = sys.argv; out = ips.split(' ')[int(idx)::int(total)]; print(' '.join(out))" "$IPS" $2 $3)


# Parse into a bash array
IFS=' ' read -ra ADDR <<< "$MY_IPS"


echo "" > /etc/network/interfaces.d/99-hcloud-floating-ips.cfg
for IP in "${ADDR[@]}"; do
    cat >> /etc/network/interfaces.d/99-hcloud-floating-ips.cfg <<EOM
iface eth0 inet static
    address ${IP}
    netmask 255.255.255.255
EOM
done


# Be sure we restart the slave because the ips changed
supervisorctl restart app
```

**Comment by patrickvale** [comment]
@miracle2k thanks!
