### ISSUE TITLE
ssh: root password needed?

### ISSUE THREAD

**Issue by ibayer** [hetznercloud/terraform-provider-hcloud#19]
Hi,

I just lunched a server according to the example in the docs.

```
# Configure the Hetzner Cloud Provider
provider "hcloud" {
  token = "xxx"
}

resource "hcloud_server" "node1" {
  name = "node1"
  image = "debian-9"
  server_type = "cx31"
}

# Create a new SSH key
resource "hcloud_ssh_key" "default" {
  name = "Terraform Example"
  public_key = "${file("~/.ssh/id_rsa.pub")}"
}
```

The ssh key seems to be added properly (according to the web interface) but 
I can't ssh in to the server without entering a password.
Is there a default password? Creating a new one with the rescue service doesn't really make sense
in combination with terraform.

**Comment by thetechnick** [comment]
Hi @ibayer,
you have to add the ssh key to your server. Try this:

```tf
# Configure the Hetzner Cloud Provider
provider "hcloud" {
  token = "xxx"
}

resource "hcloud_server" "node1" {
  name = "node1"
  image = "debian-9"
  server_type = "cx31"
  ssh_keys = ["${hcloud_ssh_key.default.id}"] # <- add ssh key to server
}

# Create a new SSH key
resource "hcloud_ssh_key" "default" {
  name = "Terraform Example"
  public_key = "${file("~/.ssh/id_rsa.pub")}"
}
```

I will add a full example to the ssh key documentation to make this more clear.

**Comment by ibayer** [comment]
The password comes with the email confirming the server creation. :-D
But why is the password required in addition to ssh?

**Comment by thetechnick** [comment]
When the server is created with an ssh key, you will not receive a password via email.
A password will only be configured when the server is created without ssh keys.

**Comment by ibayer** [comment]
It's working now. :-)
