### ISSUE TITLE
Add support for Reverse DNS

### ISSUE THREAD

**Issue by dhoppeIT** [hetznercloud/terraform-provider-hcloud#19]
Hello, 

I use the "hcloud" provider to create an cloud instance and the "inwx" provider to set the DNS records (forward). It would be great, if the "hcloud" provider would have an resource to set the DNS records (reverse). 

The website already provides an option to manipulate the Reverse DNS settings for the primary or flotation IP addresses. 

With kind regards

Dennis Hoppe

**Comment by LKaemmerling** [comment]
We are currently working on this (#15) and hope, we can release a new version of the provider in the next two weeks.
