### ISSUE TITLE
Load balancer service: changing proxyprotocol does not work

### ISSUE THREAD

**Issue by aspettl** [hetznercloud/terraform-provider-hcloud#200]
When I want to change the `proxyprotocol` setting of an existing load balancer service (defined in a `hcloud_load_balancer_service` resource), terraform will correctly display the plan (and show it as executed), but the change is not applied.
* Running it again produces the same result.
* Hetzner UI shows that the load balancer was updated, but the proxyprotocol is still the old one.
* Making the same change with the hcloud cli tool works
* When I modify something else in the service like e.g. the health check, that other change is really applied

**Comment by LKaemmerling** [comment]
Thank you for reporting the bug! I opened a Merge Request containing a fix. We will catch up a few other issues and then release a new version containing the fix.
