### ISSUE TITLE
Load balancer: wrong service deleted, therefore state corrupted

### ISSUE THREAD

**Issue by aspettl** [hetznercloud/terraform-provider-hcloud#201]
I have a load balancer IP with two services, port 80 and port 443.

When I change port 80 to e.g. 81 and apply the changes, the plan is shown correctly (shows "forces replacement" for port 80). But an apply will delete the service for port 443, too.

On the next run, the state does not match and therefore I get `Error: load balancer 46977: no service for port 443` (which can be fixed like in https://github.com/hetznercloud/terraform-provider-hcloud/issues/199).

**Comment by LKaemmerling** [comment]
Hey @aspettl,

could you please provide a (minimal) terraform configuration? I just want to make sure that i understand the whole problem. You have one service with port 80 and one with port 443?

**Comment by aspettl** [comment]
Run `terraform apply` with the following `main.tf`:
```
resource "hcloud_load_balancer" "ingress" {
  name               = "ingress"
  load_balancer_type = "lb11"
  location           = "fsn1"
  algorithm {
    type             = "round_robin"
  }
}

resource "hcloud_load_balancer_service" "ingress_http" {
  load_balancer_id = hcloud_load_balancer.ingress.id
  protocol         = "tcp"
  listen_port      = 80
  destination_port = 80
  proxyprotocol    = true
}

resource "hcloud_load_balancer_service" "ingress_https" {
  load_balancer_id = hcloud_load_balancer.ingress.id
  protocol         = "tcp"
  listen_port      = 443
  destination_port = 443
  proxyprotocol    = true
}
```

This works. Then change `listen_port      = 80` to `listen_port      = 81` and reapply. You can see in the Hetzner cloud console that the service for listen port 443 does not exist anymore.

**Comment by LKaemmerling** [comment]
@aspettl thank you, i found the issue. I will prepare a Merge request with that change.
