### ISSUE TITLE
missing attributes reference in docs

### ISSUE THREAD

**Issue by malud** [hetznercloud/terraform-provider-hcloud#21]
As seen for all major provider its best practice to describe the attributes for output or reference usage.

**Comment by thetechnick** [comment]
Hi @malud!
Isn't this covered by the docs?
https://github.com/hetznercloud/terraform-provider-hcloud/blob/master/docs/readme.md

If there is something missing let me know.

**Comment by malud** [comment]
totally overseen this in subdocs, sorry ;)
