### ISSUE TITLE
Using Floating-IPs with Load Balancer

### ISSUE THREAD

**Issue by DominikTrenz** [hetznercloud/terraform-provider-hcloud#215]
Right now it's not possible to assign a floating IP to a load balancer. But imo that should be possible. What's the purpose of Floating IPs if i can't use them with a load balanced service?

The only workaround is implementing an own load balancer, but i guess the hetzner load balancer should be usable :)

**Comment by fhofherr** [comment]
Hi @DominikTrenz,

this is a request we received a few times already. Therefore we added an entry to our [FAQs](https://docs.hetzner.com/cloud/load-balancers/faq/#can-i-assign-a-floating-ip-to-my-load-balancer) today:

> Floating IPs only support Cloud Servers as targets. Load Balancers themselves are highly available so using a Floating IP is not necessary to achieve the best uptime.
>
> Because we receive this feature request quite often we are thinking about extending Load Balancers to support this feature in the future.

Since this is related to Hetzner Cloud in general and not specific to the Terraform Provider I'm closing this issue.

**Comment by DominikTrenz** [comment]
@fhofherr The main reason i want to use floating ips with load balancers is that i need to have a stable, permanent ip on the outside, because some of my enterprise users have to configure their corporate firewalls for that ip. So being able to change infrastructure at a later point without changing the ip is very important.

**Comment by fhofherr** [comment]
The IP of a Load Balancer remains assigned to the Load Balancer as long as it exists. Therefore, as with Floating IPs, the IP remains stable until you delete the Load Balancer.

During the life time of the load balancer you can add/remove services and targets to it, and they would be reachable from clients within the corporate network.

**Comment by DominikTrenz** [comment]
Yes but scaling the Load Balancer (changing the LB type) or changing the datacenter wouldn't be possible as far as i understand. It would be nice to have that extra flexibility

**Comment by LKaemmerling** [comment]
> Yes but scaling the Load Balancer (changing the LB type) or changing the datacenter wouldn't be possible as far as i understand. It would be nice to have that extra flexibility

Changing the Type is possible as of Tuesday (when the LBs went GA). Changing the Location is not possible that’s correct. But actually if the whole location is down you might have the same problem with a floating IP.
