### ISSUE TITLE
"exec format error" when running terraform

### ISSUE THREAD

**Issue by maxigs** [hetznercloud/terraform-provider-hcloud#22]
Hi, 

I've been trying out the plugin a couple days ago and everything worked nicely.

Today however it does not work anymore. Not on a new fresh project, or the old project that worked a few days ago.

Not i receive the following error:

```
$ terraform apply

Error: Error asking for user input: 1 error(s) occurred:

* provider.hcloud: fork/exec /Users/maxigs/.terraform.d/plugins/terraform-provider-hcloud: exec format error
```

I have re-downloaded the plugin, but nothing changed.

**Comment by thetechnick** [comment]
Hi @maxigs,
can you please add the Terraform version you are using?

**Comment by maxigs** [comment]
Sorry, forgot to include this information. Here you go:

```
$ terraform -v
Terraform v0.11.3
+ provider.hcloud (unversioned)
```

**Comment by thetechnick** [comment]
Can you also add your OS name, version and architecture?
The cause of this error may be a mismatch of the plugins compile target and your operating system.

**Comment by maxigs** [comment]
It's the latest OSX
```
uname -a
Darwin ..... 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

**Comment by thetechnick** [comment]
@maxigs,
we cannot reproduce this issue on the same OSX version.
Are you sure you are using the right binary release?

Can you execute the `file` command on the plugin binary and post the output?

**Comment by maxigs** [comment]
As it seems i was using the wrong release, i must have overwritten my initially correct darwin version with the linux version when copying the url from the manual.

I corrected it and now it's working.

Thanks for your help and sorry to keep you busy for my error!
