### ISSUE TITLE
Data source hcloud_network_subnet missing

### ISSUE THREAD

**Issue by svenhertle** [hetznercloud/terraform-provider-hcloud#223]
Hi,

there is no data source for `hcloud_network_subnet`.

Currently, I query a network id with the `hcloud_network` data source and use it to create a `hcloud_server_network` resource. The `network_id` parameter is deprecated there, so I need to get the `subnet_id` instead.

Thank you!

**Comment by LKaemmerling** [comment]
The subnet_id is a string concatenation from `<network_id>-<subnet-ip-range>`, so you could "calculate" it by yourself.

**Comment by LKaemmerling** [comment]
I will close this issue, as we won't add a hcloud_network_subnet datasource.

**Comment by anbraten** [comment]
I solved it by using:

```terraform
data "hcloud_network" "kube_net" {
  name = "kube-net"
}

resource "hcloud_server_network" "server" {
  server_id  = hcloud_server.server.id
  subnet_id = "${data.hcloud_network.kube_net.id}-10.0.0.0/24"
  ip         = "10.0.0.200"
}
```

Maybe a hint in the docs would be helpful.
