### ISSUE TITLE
Resource hcloud_certificate is not updating the certificate

### ISSUE THREAD

**Issue by eidam** [hetznercloud/terraform-provider-hcloud#224]
We are using ACME provider to provision Lets Encrypt, I need to concat `issuer_pem` to the certificate, so Terraform shows in-place change which seems to pass successfully after apply. However, the change is not reflected in real state and its now always in the terraform plan.

Re-creating the cert is also not possible hotfix as there is `uniqueness_error` being thrown.

**Comment by LKaemmerling** [comment]
Updating the certificate itself is not possible, you need to recreate it, i just saw that there is a "ForceNew: true" missing @fhofherr

**Comment by LKaemmerling** [comment]
@adam-janis we just published v1.20.1 which fixes this bug. Within the next few minutes, it should be available through terraform init -upgrade

**Comment by eidam** [comment]
thank you! 👍
