### ISSUE TITLE
hcloud_server does not depend on hcloud_ssh_key

### ISSUE THREAD

**Issue by patrickvale** [hetznercloud/terraform-provider-hcloud#23]
I just created a terraform file with one hcloud_server and one hcloud_ssh_key, with the server configured to use the ssh key:

```
# Configure the Hetzner Cloud Provider
provider "hcloud" {
  token = "${var.hcloud_token}"
}

resource "hcloud_server" "node1" {
  name = "node1"
  image = "debian-9"
  server_type = "cx11"
  ssh_keys = ["PPV Terraform Example"]
}

# Create a new SSH key
resource "hcloud_ssh_key" "default" {
  name = "PPV Terraform Example"
  public_key = "${file("~/.ssh/id_rsa.pub")}"
}
```

I would expect terraform to create the SSH key first, as the server depends on it, but when I run terraform apply, I see:

```
Error: Error applying plan:

1 error(s) occurred:

* hcloud_server.node1: 1 error(s) occurred:

* hcloud_server.node1: SSH key not found: PPV Terraform Example
```

Am I using the wrong syntax?

**Comment by patrickvale** [comment]
To answer my own question - yes, I was using the wrong syntax.
For terraform to be able to infer dependencies, you must specify the implicit dependency by using variable interpolation to target the required resource - in this case, the ssh_keys key name:

```
resource "hcloud_server" "node1" {
  name = "node1"
  image = "debian-9"
  server_type = "cx11"
  ssh_keys = ["${hcloud_ssh_key.default.name}"]
}
```

**Comment by thetechnick** [comment]
Hi @patrickvale,
just started to write the answer.
I will add this to the ssh key example, so this question does not come up again.
