### ISSUE TITLE
Block Storage Support

### ISSUE THREAD

**Issue by ibayer** [hetznercloud/terraform-provider-hcloud#24]
I couldn't find any reference on how to configure storage with terraform. Is this a limitation of the
terraform-provider or doesn't hetzner provide additional storage to the server?
https://www.hetzner.de/storage-box

**Comment by thetechnick** [comment]
Hi @ibayer,
this tools scope is the Hetzner Cloud API and Storage Boxes are not part of it.
New features like blockstorage to mount additional disks will be announced on twitter:
https://twitter.com/hashtag/HetznerCloud?src=hash

**Comment by ibayer** [comment]
Nice blockstorage is really what I'm looking for (hard to work without it).
Can you just keep this issue open and close it as soon as the blockstorage is available? Its much simpler way to track progress this way.

**Comment by thetechnick** [comment]
Can do, I will use this issue to track blockstorage implementation into the Terraform Provider

**Comment by thetechnick** [comment]
Moved to https://github.com/terraform-providers/terraform-provider-hcloud/issues/4
