### ISSUE TITLE
Lookup by name for 'hcloud_floating_ip' data source

### ISSUE THREAD

**Issue by peterpramb** [hetznercloud/terraform-provider-hcloud#243]
All available `hcloud` provider data sources support resource lookups by name, just `hcloud_floating_ip` has no `name` argument.

Would be great if this could be added to make behaviour consistent, and allow for floating IP lookup by `name`.

**Comment by peterpramb** [comment]
Ok, looks like it is already implemented, it's just missing from the [documentation](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/data-sources/floating_ip).

**Comment by LKaemmerling** [comment]
Thank you for the hint, i opened an MR (#245) with a fix for that.
