### ISSUE TITLE
Documentation about how to remove public ips from servers which are in a network

### ISSUE THREAD

**Issue by pesarkhobeee** [hetznercloud/terraform-provider-hcloud#246]
Hi
I couldn't find how should I create a server which is isolated in our network and access to that from the outside is impossible.
what I am planing is trying to define just one node with a public address and other nodes should be protected from the outside world:
https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/server_network
The only way is after spinning up the servers I can edit servers' network interfaces and remove the public one but is there any standard way for that?

**Comment by LKaemmerling** [comment]
Currently, you can not remove public IPs from a server, you need to disable the interface on-host.
