### ISSUE TITLE
Load balancer targets not using private ips altough instructed to do so.

### ISSUE THREAD

**Issue by valentin-fischer** [hetznercloud/terraform-provider-hcloud#249]
Hi guys, 

Found another issue... this time regarding to the usage of private ips by the load balancer.

For some reason, when I create a tcp load balancer and add to it server targets that have private ip addresses, they are not used.
I use use_private_ip = true in the configuration but it seems to have no effect on the creation part. 

```
resource "hcloud_load_balancer" "web_lb" {
  name               = "web_lb"
  load_balancer_type = "lb11"
  location           = var.location
  labels = {
    type = "web"
  }

  dynamic "target" {
    for_each = hcloud_server.web
    content {
      type      = "server"
      server_id = target.value["id"]
      use_private_ip = true
    }
  }
  algorithm {
    type = "round_robin"
  }
}
```

**Comment by LKaemmerling** [comment]
The targets part does not support use_private_ip. 

You need to use https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/load_balancer_target

The targets value on the `hcloud_load_balancer` resource is for "easy" setups only.

**Comment by valentin-fischer** [comment]
Thanks for the fast reply.

I understand. 

I've changed to the recommended resource and the following code does the job.

```
resource "hcloud_load_balancer_target" "target_web_lb" {
   load_balancer_id = hcloud_load_balancer.web_lb.id
   count = var.instances
   type      = "server"
   server_id = hcloud_server.web[count.index].id
   use_private_ip = true
    depends_on = [
     hcloud_server_network.web_network
  ]
}
```
br

**Comment by valentin-fischer** [comment]
Thank you for the support!
