### ISSUE TITLE
SSH key with the same fingerprint already exists (uniqueness_error)

### ISSUE THREAD

**Issue by ibayer** [hetznercloud/terraform-provider-hcloud#25]
I don't understand why this has to throw an error, can this be avoided?

```
Error: Error applying plan:

1 error(s) occurred:

* hcloud_ssh_key.ibayer: 1 error(s) occurred:

* hcloud_ssh_key.ibayer: SSH key with the same fingerprint already exists (uniqueness_error)
```

**Comment by thetechnick** [comment]
Hi @ibayer,
the Hetzner Cloud API does not allow to create an ssh key with the same fingerprint twice.
So you have to use another ssh key for Terraform or import the ssh key via `terraform import`.

**Comment by ibayer** [comment]
I have multiple independent project that I manage with terraform.
Both options

* creating a separate ssh for each project and
* creating dependencies between projects with terraform import

doesn't feel right. Wouldn't it be better if `"hcloud_ssh_key"` checks if the SSH key is present and doesn't upload if it's already there. I don't get way failing is necessary. Even a option like `skip_if_key_exists` would make things much simpler.

**Comment by thetechnick** [comment]
Terraform's center feature is that it manages project state in the .tfstate file. If you want to work with resources they need to be present in Terraforms state (either by importing or by letting terraform itself create the resource)

The dependency between the projects is created by referencing the same SSH Key in the Hetzner Cloud.

If you need a tool that does not need state you will need a tool like ansible.

**Comment by thetechnick** [comment]
If you dont want to import the ssh key into terraform you can also hardcode the ssh-keys name or id into the terraform configuration without using the `hcloud_ssh_key` resource.

**Comment by ibayer** [comment]
Thanks for the input!
it's still not clear to me why the hetzner cloud doesn't allow multiple instances of `"hcloud_ssh_key"` with "SSH key with the same fingerprint" but thats a design decision we have to live with.

You are right, in my situation managing the ssh key by other means is probably the best idea .
