### ISSUE TITLE
rDNS + Load Balancer

### ISSUE THREAD

**Issue by DominikTrenz** [hetznercloud/terraform-provider-hcloud#255]
How can i change the reverse DNS of a load balancer? I understand that it is not possible to point a floating ip to a load balancer so   this is not possible right now? The only option that i can see is implementing an own load balancer and pointing a floating ip to that.

**Comment by LKaemmerling** [comment]
> How can i change the reverse DNS of a load balancer? I understand that it is not possible to point a floating ip to a load balancer so this is not possible right now? The only option that i can see is implementing an own load balancer and pointing a floating ip to that.

Hey @DominikTrenz, LoadBalancers does not support setting the RDNS entry yet. 

Just out of curiosity: What would be your use case for this?

**Comment by DominikTrenz** [comment]
The main use case would be that it looks nicer/more professional. I think the only real use case would be a high availability mail service... I was just surprised that it is not possible at the moment because floating ips and server support it

**Comment by LKaemmerling** [comment]
Okay thank you. Using a HA (sending) mail service wouldn’t be possible, because the loadbalancers are more or less „inbound“ (they need a request going in, while smtp would be outbound. Of course IMAP/POP3 should work.

**Comment by LKaemmerling** [comment]
Hey @DominikTrenz,

I passed your request to our internal teams. I will close the issue here now because it is not directly Terraform provider related.
