### ISSUE TITLE
Slow load balancer target detection when using labels

### ISSUE THREAD

**Issue by DominikTrenz** [hetznercloud/terraform-provider-hcloud#256]
I'm trying to use a load balancer with labels and it takes up to 30 minutes until the load balancer picks up a fully functional new server. And the health status of that server takes even longer to refresh. Is there a problem with labeled targets?

**Comment by LKaemmerling** [comment]
Could you please write a support ticket for this? This issue is not Terraform Provider specific/related :)

**Comment by DominikTrenz** [comment]
Alright. Sorry :)
