### ISSUE TITLE
Import existing floating ip

### ISSUE THREAD

**Issue by namxam** [hetznercloud/terraform-provider-hcloud#26]
I am quite new to terraform, so i might be doing it wrong, but I am trying to import an existing floating ip into my setup. The official guide at https://www.terraform.io/docs/providers/hcloud/r/floating_ip.html notes that this should be possible via `terraform import hcloud_floating_ip.myip <id>`.

I guess `<id>` refers to hetzner's internal id. So I fetched it via `hcloud floating-ip list` and replaced it in above command. But when I run it I get:

```
hcloud_floating_ip.public_ip: Importing from ID "702"...
hcloud_floating_ip.public_ip: Import complete!
  Imported hcloud_floating_ip (ID: 702)
hcloud_floating_ip.public_ip: Refreshing state... (ID: 702)

Error: hcloud_floating_ip.public_ip (import id: 702): 1 error(s) occurred:

* import hcloud_floating_ip.public_ip result: 702: import hcloud_floating_ip.public_ip (id: 702): Terraform detected a resource with this ID doesn't
exist. Please verify the ID is correct. You cannot import non-existent
resources using Terraform import.
```

It looks as if it works as expected but then fails. I have no idea what is happening here 😭

**Comment by LKaemmerling** [comment]
I have tried it, it looks like your api key does not have access to the floating ip ID 702. Are you sure, that the ID 702 is correct?

**Comment by LKaemmerling** [comment]
@namxam do you still have issues with this?

**Comment by namxam** [comment]
Sorry, I should have replied earlier. I just tested it and realised, that I have not changed the context. I saw it when I inspected the output and saw that the IPs did not match. Only then it dawned on me, that I have to add another context for my project so `hcloud` command line tool was listing the appropriate resources. My bad. Please close!
