### ISSUE TITLE
Document how to log into servers created by terraform through console admin view

### ISSUE THREAD

**Issue by DanielMSchmidt** [hetznercloud/terraform-provider-hcloud#260]
Hi there,

I am experiencing problems with one of my servers, it can not be accessed anymore (including SSH).
I can resolve the issue by restarting the server through https://console.hetzner.cloud but I am not able to debug the issue. My plan was to log in through the console view in that UI, but I don't have a username and password.
If this is exposed somewhere already a bit of documentation would be great, if not having this piece of information exposed could help a lot 😇

**Comment by LKaemmerling** [comment]
@DanielMSchmidt for the Cloud Console (https://console.hetzner.cloud) you need your Hetzner Account credentials. Within the Cloud Console, you are able to go to the project and to the specific server and then you can open up a VNC console, which is basically the screen of your server and you can type in like you were directly plugged in into this server.

**Comment by DanielMSchmidt** [comment]
I'm sorry, the term console was a bit ambiguous here. My problem is that when I start the VNC console the server needs username and password. I never provided those through terraform, I only use ssh Auth.

**Comment by LKaemmerling** [comment]
@DanielMSchmidt You can reset the Root PW through the Cloud Console, then the credentials are normally "root" and the given PW.

**Comment by LKaemmerling** [comment]
@DanielMSchmidt I hope your problem is solved. I will close this issue, as it isn't a terraform provider related issue. If you still encounter problems, feel free to open up a new issue or a support ticket.
