### ISSUE TITLE
wrong subnet assignment when using Terraform provider

### ISSUE THREAD

**Issue by selfscrum** [hetznercloud/terraform-provider-hcloud#265]
Possibley there is a bug in the way how the terraform provider creates subnet assignments.

I want to create a 2 tier network structure and create 2 subnets for that. 3 servers are created as well, 2 of them attached to the public subnet, one to the private subnet.

The real assignment is best described as "somehow". IT seems to be randomly assiged. in some cases, all machines were in one subnet, after disconneting them and rerunning Terraform, 2 were in private, and 1 in public, and so on. No pattern recognizable for me. 

A second terraform run against the wrong configuration shows no need for change.

I am using cx11 ubuntu, terraform 0.13.5

The network-related code is:

```
resource "hcloud_network" "mynet" {
  name = "zcluster"
  ip_range = "10.0.0.0/16"
}

resource "hcloud_network_subnet" "public" {
  network_id = hcloud_network.mynet.id
  type = "cloud"
  network_zone = "eu-central"
  ip_range   = "10.0.1.0/24"
}

resource "hcloud_network_subnet" "private" {
  network_id = hcloud_network.mynet.id
  type = "cloud"
  network_zone = "eu-central"
  ip_range   = "10.0.2.0/24"
}

### 
servers defs omitted
###

resource "hcloud_server_network" "internal_postgres" {
  subnet_id = hcloud_network_subnet.private.id
  server_id  = hcloud_server.postgres.id
}

resource "hcloud_server_network" "external_worker" {
  subnet_id = hcloud_network_subnet.public.id
  server_id  = hcloud_server.worker.id
}

resource "hcloud_server_network" "external_controller" {
  subnet_id = hcloud_network_subnet.public.id
  server_id  = hcloud_server.controller.id
}


```

NB: I just found the sentence hidden in the provider doc:

> Note: if the ip property is missing, the Server is currently added to the last created subnet.

But even if I assign proper IP addresses, those aasignments are ignored.

checking the API shows consistently the same wrong assignments in networks and in network-actions.

**Comment by LKaemmerling** [comment]
Can you share your terraform configuration with the direct assignment? If you use `cidrhost` (https://www.terraform.io/docs/configuration/functions/cidrhost.html) to calculate your IPs it should work. 

Sample:

```hcl
resource "hcloud_server_network" "external_controller" {
  subnet_id = hcloud_network_subnet.public.id
  server_id  = hcloud_server.controller.id
  ip = cidrhost(hcloud_network_subnet.private.ip_range, 1) # First host in the private_range
}
```

Using `subnet_id` is a bit strange. The property is only a "bridge" for Terraform so that we ensure that always at least one subnet is available within the network. Subnet's itself doesn't have an ID. The Terraform ID of the subnets is a concatenated string based on `<network-id>-<subnet-ip-range>`.

**Comment by selfscrum** [comment]
Thanks for the hints. 

I think the subnet_id was the problem. Switching to network id solved the issue. However, I changed now to cidrhost, too, had previously a fixed manual string as assignment of the IP. I append the whole code of my component for reference.

I was misled by my perception of subnet as an entity of its own as I know it from other providers. Seeing it as an overlay, the approach to use the network id makes more sense.

[hetzner.txt](https://github.com/hetznercloud/terraform-provider-hcloud/files/5493830/hetzner.txt)
