### ISSUE TITLE
hcloud_network_subnet should warn if netmask masks away part of "ip_range"

### ISSUE THREAD

**Issue by flokli** [hetznercloud/terraform-provider-hcloud#266]
I created a network with a wrong netmask, using the following resource(s):

```
resource "hcloud_network" "nodes" {
  name     = "nodes"
  ip_range = "10.0.0.0/8"
}

resource "hcloud_network_subnet" "nodes" {
  network_id   = hcloud_network.nodes.id
  type         = "cloud"
  network_zone = "eu-central"
  ip_range     = "10.0.1.0/23"
}
```

The API accepted the request, silently applied the netmask, and created a network_subnet with `ip_range` `10.0.0.0/23`.

However, on a second `terraform apply`, terraform saw that `10.0.0.0/23` as `ip_range` from the backend, which differs from the local values in the `.tf` files, and wanted to change this to the `10.0.1.0/23` written down there (and due to that, also wanted to recreate all the child `hcloud_server_network` resources:

```
  # hcloud_network_subnet.nodes must be replaced
-/+ resource "hcloud_network_subnet" "nodes" {
      ~ gateway      = "10.0.0.1" -> (known after apply)
      ~ id           = "188660-10.0.0.0/23" -> (known after apply)
      ~ ip_range     = "10.0.0.0/23" -> "10.0.1.0/23" # forces replacement
        network_id   = 188660
        network_zone = "eu-central"
        type         = "cloud"
    }
```

Instead of this confusing behaviour, the hcloud provider should probably complain if you want to create an `ip_range` where the netmask would actually mask something away in first place.

**Comment by LKaemmerling** [comment]
Thank you for your issue request. 

The problem is that terraform makes a string comparison here (before it calls the provider), so we are not able to normalize it within the provider. 

For the API it is valid because your range is within the given network range, so everything is fine. How you write the range, is your part.

So it is not "fixable" on our site (because of terraform), the only thing that would solve the issue would be a normalized step before terraform run.

**Comment by flokli** [comment]
I didn't meant to normalize, but to simply refuse creating a `hcloud_network_subnet` resource with something that'd cause unstable terraform plans:

> the hcloud provider should probably complain if you want to create an ip_range where the netmask would actually mask something away in first place.

As in, parse `ip_range` in the provider, see if applying the netmask would change the output, if so, refuse creating the resource.
