### ISSUE TITLE
Load balancer is not attached to a network

### ISSUE THREAD

**Issue by selfscrum** [hetznercloud/terraform-provider-hcloud#268]
There seems to be another timing issue in the tf provider:

when trying to create a labelled target for the load balancer, I get an TF error saying `"Error: add label selector target: load balancer is not attached to a network (load_balancer_not_attached_to_network)"`. 

On a second run of the same script, the target can be created. So it seems that `hcloud_load_balancer_network` is not yet finished when tf returns from it. I am using an LB11.

Fun fact - I cannot add my configured network for the load balancer via the web gui. It says "there is no subnet in the network (altough there is). API and Terraform provider work, though, so it is a minor nuisance for me.

load balancer code snippet: 

```
resource "hcloud_load_balancer" "external_interface" {
  name = "external-interface"
  load_balancer_type = var.lb_type
  network_zone = var.network_zone
}

resource "hcloud_load_balancer_network" "frontnet" {
  load_balancer_id = hcloud_load_balancer.external_interface.id
  network_id = hcloud_network.mynet.id
  ip = cidrhost(hcloud_network_subnet.public.ip_range, 3) 
}

resource "hcloud_load_balancer_service" "load_balancer_service" {
    load_balancer_id = hcloud_load_balancer.external_interface.id
    protocol = "https"
    listen_port = 9200
    destination_port = 9200
    http { certificates = [ data.hcloud_certificate.selftest.id ] }
}

resource "hcloud_load_balancer_target" "load_balancer_target" {
  type             = "label_selector"
  load_balancer_id = hcloud_load_balancer.external_interface.id
  label_selector   = "CONTROLLER"
  use_private_ip   = true
}

```

**Comment by LKaemmerling** [comment]
You need to use `depens_on` in some cases, have a look at https://github.com/hetznercloud/terraform-provider-hcloud/issues/170#issuecomment-651789377 for more details.
