### ISSUE TITLE
Network route cannot be set to 0.0.0.0/0

### ISSUE THREAD

**Issue by selfscrum** [hetznercloud/terraform-provider-hcloud#269]
When trying to set a route to 0.0.0.0/0 from within a network with subnets, terraform provider returns an `Error: network route gateway not part of the network IP range (10.0.0.0/16) (invalid_input)`.  Both GUI and API allow that call.

Code snippet:
```
resource "hcloud_network_route" "to_router" {
  network_id = hcloud_network.mynet.id
  destination = "0.0.0.0/0"
  gateway = hcloud_server.router.ipv4_address
}

```

**Comment by LKaemmerling** [comment]
You specify the public IP of the server, not the private IP. The error message says exactly that :) You need to specify the `private` IP of your server as gateway.

**Comment by selfscrum** [comment]
thanks will give it a try

**Comment by selfscrum** [comment]
Ok I'm back. How would I find out about the second IP then? The hcloud_server object has only one, and the alias_ips array of the server network is empty.

Do I have to enter the IP of the second adapter manually? 

I am surprised about this since when applying the same parameters to the API Gateway, it worked like a charme.
