### ISSUE TITLE
LoadBalancer. Error: invalid input in field 'health_check' (invalid_input)

### ISSUE THREAD

**Issue by AndreiPaulau** [hetznercloud/terraform-provider-hcloud#270]
Dear Support,
hetznercloud/hcloud v1.23.0

```
resource "hcloud_load_balancer_service" "app_lb_service" {
  load_balancer_id = hcloud_load_balancer.app_lb.id
  protocol         = "https"
  listen_port      = 443
  destination_port = 8080

  http {
    certificates = [hcloud_certificate.certificate.id]
    redirect_http = true
  }

  health_check {
    protocol = "http"
    port     = 8080
    interval = 5
    retries  = 3
    timeout  = 15

    http {
      path         = "/api/ping"
      status_codes = ["2??", "3??"]
      tls = false
    }

  }
}
```

Can you please help me to figure out the issue:

With preconfigured health_check, I'm getting Error: invalid input in field 'health_check' (invalid_input) (targets added, but the service isn't created)

If a health_check section is commented - everything deployed without an issue.
Meanwhile, I can easily configure the service manually with the same options mentioned above. 
Just let me know if you need full template.

Thanks!

**Comment by fhofherr** [comment]
Hi @AndreiPaulau,

thanks for your issue report. Can you try to remove the `tls = false` and see if it works. If this does not help I'll try to reproduce your issue, but it might take me a few days to get around to it.

**Comment by AndreiPaulau** [comment]
Hi, no luck.

**Comment by fhofherr** [comment]
Ok. I'll try to reproduce it. Your snippet should be enough to start.

**Comment by fhofherr** [comment]
Hi @AndreiPaulau,

I was able to reproduce your issue. Could you please try to set your `interval` to a value greater or equal to your `timeout`?

For example:

```
resource "hcloud_load_balancer_service" "app_lb_service" {
  load_balancer_id = hcloud_load_balancer.app_lb.id
  protocol         = "https"
  listen_port      = 443
  destination_port = 8080

  http {
    certificates = [hcloud_certificate.certificate.id]
    redirect_http = true
  }

  health_check {
    protocol = "http"
    port     = 8080
    interval = 30
    retries  = 3
    timeout  = 15

    http {
      path         = "/api/ping"
      status_codes = ["2??", "3??"]
      tls = false
    }

  }
}
```

**Comment by AndreiPaulau** [comment]
Hm, well, I've tried different ratio between interval and timeout (and even default values (15 interval/10timeout/3retries) which are proposed while UI creation), but still no luck.

Also found that there is an alert at UI limiting interval-timeout values. Would be great to mention this as well at docs to avoid such Q.

**Comment by fhofherr** [comment]
```

**Comment by fhofherr** [comment]
```
terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
    }
  }
  required_version = ">= 0.13"
}

resource "hcloud_certificate" "certificate" {
    name = "test-certificate"

    private_key =<<-EOT
...
    EOT

    certificate =<<-EOT
...
    EOT
}


resource "hcloud_server" "myserver" {
  name       = "myserver"
  server_type = "cx11"
  image = "ubuntu-20.04"
}

resource "hcloud_load_balancer" "app_lb" {
  name       = "app-lb"
  load_balancer_type = "lb11"
  location   = "nbg1"
  target {
    type = "server"
    server_id = hcloud_server.myserver.id
  }
}

resource "hcloud_load_balancer_service" "app_lb_service" {
  load_balancer_id = hcloud_load_balancer.app_lb.id
  protocol         = "https"
  listen_port      = 443
  destination_port = 8080

  http {
    certificates = [hcloud_certificate.certificate.id]
    redirect_http = true
  }

  health_check {
    protocol = "http"
    port     = 8080
    interval = 30
    retries  = 3
    timeout  = 15

    http {
      path         = "/api/ping"
      status_codes = ["2??", "3??"]
      tls = false
    }
  }
}
```

I tested it with the following HCL, which works. Can you please re-test on your side with it? However, I redacted the certificate so you will need to add your own.

We are aware that the error message is not ideal. We are working on improving it for a future release.

**Comment by AndreiPaulau** [comment]
Ferdinand - your template works well.
Finally... I've just retyped the "health_check" section once again - and it worked...
Indentation, encoding or something else, anyway... Many thanks for pointing out for interval/timeout relationship that still was my issue!
And sorry for taking your time for a such a stupid thing.

**Comment by fhofherr** [comment]
You are welcome :slightly_smiling_face: I'm glad I could help.
