### ISSUE TITLE
hcloud_certificate. Terraform forces replacement even without changes.

### ISSUE THREAD

**Issue by AndreiPaulau** [hetznercloud/terraform-provider-hcloud#271]
Dear Support,

Can you please help to figure out what I'm doing wrong.

In my understanding, if i don't touch certificate/key in hcloud_certificate it shouldn't be recreated/updated.
But if I run the same template two times without changes I got the following.
```
  # hcloud_certificate.certificate must be replaced
-/+ resource "hcloud_certificate" "certificate" {
      ~ certificate      = <<~EOT # forces replacement
            -----BEGIN CERTIFICATE-----
...
  EOT
      ~ created          = "2020-11-20 06:58:41.899186 +0000 +0000" -> (known after apply)
      ~ domain_names     = [
          - "*.example.com",
          - "example.com",
        ] -> (known after apply)
      ~ fingerprint      = "85:...:48" -> (known after apply)
      ~ id               = "35409" -> (known after apply)
        labels           = {
            "component"   = "certifcate"
            "environment" = "dev"
        }
        name             = "dev-certificate-%d"
      ~ not_valid_after  = "2021-06-16T23:59:59Z" -> (known after apply)
      ~ not_valid_before = "2019-06-03T00:00:00Z" -> (known after apply)

        private_key      = (sensitive value)
    }
```
and of course then :
```
Error: certificate with ID 35409 is still in use (service_error)
```

Terraform template:
```
resource "hcloud_load_balancer_service" "app_lb_service" {
  load_balancer_id = hcloud_load_balancer.app_lb.id
  protocol         = "https"
  listen_port      = 443
  destination_port = 8080

  http {
    certificates  = [hcloud_certificate.certificate.id]
    redirect_http = true
  }

  health_check {
    protocol = "http"
    port     = 8080
    interval = 30
    retries  = 3
    timeout  = 15

    http {
      path         = "/api/ping"
      status_codes = ["2??", "3??"]
      tls          = false
    }
  }
}

resource "hcloud_load_balancer_target" "app_lb_target" {
  count = var.worker_count

  type             = "server"
  load_balancer_id = hcloud_load_balancer.app_lb.id
  server_id        = hcloud_server.app_workers[count.index].id
  use_private_ip   = true
  depends_on = [
    hcloud_server_network.server-network
  ]
}

resource "hcloud_certificate" "certificate" {
  name = "${var.environment}-certificate-%d"

  private_key = file("./certificate/file.pem")
  certificate = file("./certificate/file.crt")

  labels = {
    environment = var.environment
    component   = "certifcate"
  }
}
```

**Comment by fhofherr** [comment]
Hi @AndreiPaulau,

are you sure you did not change anything on the `hcloud_certificate` resource? I can execute the following as often as I want:

```
terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
    }
  }
  required_version = ">= 0.13"
}

resource "hcloud_certificate" "certificate" {
    name = "test-certificate"

    private_key =<<-EOT
REDACTED
    EOT

    certificate =<<-EOT
REDACTED
    EOT
}
```

Changing the `name` property seems to work as expected and renames the certificate. Also renaming the resource from `certificate` to `certificate-2` works.

Could you please insert your certificate into the snippet above and try the following:

1. Apply the plan and then re-apply it without changing the text.
2. Change value of the `name` property to something else and re-apply the plan.
3. Change the resource name from `certificate` to something else and re-apply the plan.

Do the above steps work for you?

Best regards

**Comment by AndreiPaulau** [comment]
I'm sure, I didn't change anythingin hcloud_certificate resource.
Maybe this is about the method of adding files via "file"? have you tried this or you were adding via EOT
  private_key = file("./certificate/file.pem")
  certificate = file("./certificate/file.crt")

Meanwhile, I'll try the snippet

**Comment by AndreiPaulau** [comment]
Finally your snippet works (if I paste certifcate as text), but it don't if I use private_key = file("./certificate/file.pem")
Meanwhile I use:
```
resource "hcloud_ssh_key" "user" {
  name       = "user"
  public_key = file("./keys/somekey.pub")
}
```
and it doesn't trigger to recreate resource.
Is that ok? Can you double check my snippet?

**Comment by fhofherr** [comment]
Just a question: do you have more than one certificate in your certificates file? For example the certificates and any intermediate certificates associated with it?

**Comment by AndreiPaulau** [comment]
It's a chain of 3 certificates in a file

**Comment by fhofherr** [comment]
Could you please try to reorder them to the following order in the file? `root` -> `intermediate` -> `actual certificate`?

**Comment by AndreiPaulau** [comment]
Seems like the chain in the right order
and I can easily add it via UI.

**Comment by fhofherr** [comment]
I guess without your certificate it is going to be hard for me to further analyze your issue. Would it be ok for you to send me your _certificate_ to ferdinand.hofherr@hetzner-cloud.de? The certificate should be public anyway. Please **do not** sent me your _private key_.

**Comment by AndreiPaulau** [comment]
Just sent you. Many thanks

**Comment by fhofherr** [comment]
For anyone else stumbling across this: the file needs unix line endings.

**Comment by AndreiPaulau** [comment]
Thanks for the assistance!
Feel free to close the issue

**Comment by LKaemmerling** [comment]
Hey @AndreiPaulau,

@fhofherr  prepared a solution (#282) which will be within our next release. I will close the issue now. If you encounter any other problems, feel free to open a new issue.

- Lukas
