### ISSUE TITLE
RFC: assing object to project

### ISSUE THREAD

**Issue by npajkovsky** [hetznercloud/terraform-provider-hcloud#272]
Hello,

Hetzner Cloud could divide objects (server/LB/networking, ...)  into projects, but that cannot be done in terraform, which is pitty.

I would like to have multiple projects and I would like assign servers to project.

**Comment by apricote** [comment]
You can do this by using the [provider `alias`](https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-configurations) and then using tokens for each project for the different providers.

**Comment by npajkovsky** [comment]
Thanks, that will work.
