### ISSUE TITLE
Terraform 0.14 issue

### ISSUE THREAD

**Issue by tkoeck** [hetznercloud/terraform-provider-hcloud#277]
terraform init

will show the following output

Warning: Additional provider information from registry

The remote registry returned warnings for
registry.terraform.io/terraform-providers/hcloud:
- For users on Terraform 0.13 or greater, this provider has moved to
hetznercloud/hcloud. Please update your source in required_providers.

In the documentation there aren't any information how to set it up for Terraform 0.14.

**Comment by tkoeck** [comment]
If I adjust that to

`
terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
    }
  }
}
`

I'll still get


Warning: Additional provider information from registry

The remote registry returned warnings for
registry.terraform.io/terraform-providers/hcloud:
- For users on Terraform 0.13 or greater, this provider has moved to
hetznercloud/hcloud. Please update your source in required_providers.
`

**Comment by LKaemmerling** [comment]
You should use https://www.terraform.io/docs/commands/0.13upgrade.html for upgrading your terraform configuration. As of terraform 0.13 the was a change over all terraform modules. This is nothing specific to our provider. You can find the whole snippet you need to use the provider within the terraform registry: https://registry.terraform.io/providers/hetznercloud/hcloud/latest (Use Provider button)

**Comment by tkoeck** [comment]
Hi,
I did make the upgrade before


tkoeck@tron-nb:~/gitlab/mail.someserver.info$ tf13 version
Terraform v0.13.5
+ provider registry.terraform.io/terraform-providers/hcloud v1.20.1

Your version of Terraform is out of date! The latest version
is 0.14.0. You can update by downloading from https://www.terraform.io/downloads.html

tkoeck@tron-nb:~/gitlab/mail.someserver.info$ tf13 0.13upgrade

This command will update the configuration files in the given directory to use
the new provider source features from Terraform v0.13. It will also highlight
any providers for which the source cannot be detected, and advise how to
proceed.

We recommend using this command in a clean version control work tree, so that
you can easily see the proposed changes as a diff against the latest commit.
If you have uncommited changes already present, we recommend aborting this
command and dealing with them before running this command again.

Would you like to upgrade the module in the current directory?
  Only 'yes' will be accepted to confirm.

  Enter a value: yes

-----------------------------------------------------------------------------

Upgrade complete!

Use your version control system to review the proposed changes, make any
necessary adjustments, and then commit.

tkoeck@tron-nb:~/gitlab/mail.someserver.info$ terraform version
Terraform v0.14.0
+ provider registry.terraform.io/hetznercloud/hcloud v1.23.0
+ provider registry.terraform.io/terraform-providers/hcloud v1.23.0
tkoeck@tron-nb:~/gitlab/mail.someserver.info$ terraform init

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hetznercloud/hcloud from the dependency lock file
- Reusing previous version of terraform-providers/hcloud from the dependency lock file
- Installing terraform-providers/hcloud v1.23.0...
- Installed terraform-providers/hcloud v1.23.0 (signed by HashiCorp)
- Installing hetznercloud/hcloud v1.23.0...
- Installed hetznercloud/hcloud v1.23.0 (signed by a HashiCorp partner, key ID 5219EACB3A77198B)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html


Warning: Additional provider information from registry

The remote registry returned warnings for
registry.terraform.io/terraform-providers/hcloud:
- For users on Terraform 0.13 or greater, this provider has moved to
hetznercloud/hcloud. Please update your source in required_providers.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

**Comment by LKaemmerling** [comment]
@tkoeck you still download the old provider:
```
Initializing provider plugins...

Reusing previous version of hetznercloud/hcloud from the dependency lock file
Reusing previous version of terraform-providers/hcloud from the dependency lock file
Installing terraform-providers/hcloud v1.23.0...
Installed terraform-providers/hcloud v1.23.0 (signed by HashiCorp) <--- HERE
Installing hetznercloud/hcloud v1.23.0...
Installed hetznercloud/hcloud v1.23.0 (signed by a HashiCorp partner, key ID 5219EACB3A77198B)
```

**Comment by tkoeck** [comment]
I had to adjust the state file manually because the 0.13upgrade didn't upgrade the state file but only the provider configuration above. 

It should have worked. Don't know if it is Terraform related or is a problem in your provider. Thanks for the advice anyway.
