### ISSUE TITLE
Import existing servers forces replacement

### ISSUE THREAD

**Issue by ngoduykhanh** [hetznercloud/terraform-provider-hcloud#278]
Hello,

I am trying to import some of my existing servers to TF. However, it forces to recreate the VM after importing because of the missing `image` attribute.

```  # module.hcloud_vm.hcloud_server.main["myvm"] must be replaced
-/+ resource "hcloud_server" "main" {
      + backup_window = (known after apply)
        backups       = false
      ~ datacenter    = "fsn1-dc14" -> (known after apply)
      ~ id            = "7875xxx" -> (known after apply)
      + image         = "ubuntu-20.04" # forces replacement
      ~ ipv4_address  = "159.69.xxx.xxx" -> (known after apply)
      ~ ipv6_address  = "2a01:4f8:c17:xxxx" -> (known after apply)
      ~ ipv6_network  = "2a01:4f8:c17:xxxx" -> (known after apply)
      + keep_disk     = false
      ~ labels        = {
          + "terraform_module" = "production/infra"
        }
        location      = "fsn1"
        name          = "myvm"
        server_type   = "cx11"
      ~ status        = "running" -> (known after apply)
    }
```

This doesn't happen to all servers, just a few of them. I double check by using the `hcloud` cli to describe my server,  the `Image` is also empty.

```
Image:
  No Image
```

I am not sure if something can be adjusted from this terraform provider itself or from Hetzner API system. Any idea?
_p/s: I replaced some sensitive information with `xxx`_

**Comment by LKaemmerling** [comment]
Hey @ngoduykhanh,

thank you for your report. Do you remember with which image you created the server?

**Comment by ngoduykhanh** [comment]
Hi @LKaemmerling, it was Ubuntu 20.04.
I am not sure why it was empty from the Hetzner API return. As far as I understand, Hetzner makes it empty if the VM is created from a custom image or snapshot, but mine wasn't.
Btw, I managed to solve it by ignoring the changes for that attribute from terraform code. Feel free to close the issue if there is nothing you can do from your side.

**Comment by LKaemmerling** [comment]
Hey @ngoduykhanh,

within our logs, I can see that you created the server( i assume we are talking about `worker2`) from a snapshot. This snapshot was deleted at 2020-10-03 12:09:38.098021+00. 

We should improve this within the terraform provider, as it should not force a recreation here. I don't think it is doable this year, so we will look into it after the holidays. Thank you!

**Comment by ngoduykhanh** [comment]
@LKaemmerling aha, so I didn't remember what I have done since I deleted the snapshot :(.
If it is something we couldn't do with the Hetzner API, it is great to have a fix in the terraform provider or at least notes in the document.
Btw, thank you for checking.

**Comment by LKaemmerling** [comment]
I'm really unsure if we should improve this, as it would bring a lot of downsides.

We can terraform assume that when the image is empty, everything is fine, but this leads to the "problem", that we will always suppress the changes, so if you really want to as a sample rebuild the server using a newer image, we wouldn't see the change. (As we always suppress the error.). I personally think this is not worth the effort and brings a lot of downsides with it.

```golang
DiffSuppressFunc: func(k, old, new string, d *schema.ResourceData) bool {
	// With this we can allow importing servers with a deleted image
	if len(old) == 0 { // When the old "state" is empty, always think it is fine.
		return true
        }
	return false
},
```

@fhofherr what do you think?

**Comment by dstapp** [comment]
Having the same problem here. Imported my existing infrastructure, now TF would replace my production machines because of the image being changed (created it back then with ubuntu-18.04). For anyone looking to solve this in the future:

```
resource "hcloud_server" "app" {
  backups       = true
  datacenter    = "nbg1-dc3"
  labels        = {}
  image         = "ubuntu-18.04"
  location      = "nbg1"
  name          = "app"
  server_type   = "cx31"

  lifecycle {
    ignore_changes = [
      image
    ]
  }
}
```

makes TF ignore the image changes. `terraform plan` then shows no changes to the machine.

**Comment by sasoiliev** [comment]
I am hitting the same issue, although this discussion seems to be mostly about servers built from deleted images, while in my case the image is a snapshot and it's still there and is reported correctly by the API (`curl  -H "Authorization: Bearer $HCLOUD_TOKEN" https://api.hetzner.cloud/v1/servers/XXX` returns a fully-populated `image` object), but the Terraform import operation still fails to populate the image and `terraform plan` wants to re-create the server.

**Comment by rene-s** [comment]
I could work around this issue by creating a VM snapshot and then immediately rebuild the VM from that snapshot. Now the "image" attribute does not get reported as `null` anymore on import and I have a value to set so TF won't replace the VM.

**Comment by dvk1302dvk** [comment]
How import servers from not 'MISC' project? I don't have result when using **id** from another project folder.

**Comment by LKaemmerling** [comment]
> How import servers from not 'MISC' project? I don't have result when using **id** from another project folder.

You can not import servers that belongs to another project (& API token). The API token you pass is only valid for one project.

**Comment by dvk1302dvk** [comment]
> > How import servers from not 'MISC' project? I don't have result when using **id** from another project folder.
> 
> You can not import servers that belongs to another project (& API token). The API token you pass is only valid for one project.

Thank you.

**Comment by LKaemmerling** [comment]
Hey @dprandzioch and @ngoduykhanh,

could you please try out to remove the ignoring of the image field? We recently deployed a change of the API that fixes your issue.

As the underlying API issue was fixed I will close the issue. If you still have this issue feel free to reopen the issue (or comment under this issue)

**Comment by uovobw** [comment]
why has this been closed? this makes importing an existing instance into terraform impossible. i can confirm the issue still remains as of today (2021-10-01) and it's making it impossible for us to terraform our infrastructure (15+ projects, tens of vms).
