### ISSUE TITLE
SOLVED hcloud provider is missing from the terraform registry

### ISSUE THREAD

**Issue by ovitente** [hetznercloud/terraform-provider-hcloud#290]
### Issue short description
`terraform init` for `hcloud` provider says, that it can't be found in terraform registry.

### Expected behavior
To receive hcloud provider for further work

### Factial behavior
`terraform init` returned error.

### Details
```
terraform --version
Terraform v0.13.5
```

I have tried to do `terraform init` using official documentation - https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs as example.
Earlier I have successfully used simple tf code to deploy one server with volume attachment without any issues.

Tf file is
```
variable "hcloud_token" {}

provider "hcloud" {
  token = var.hcloud_token
}

resource "hcloud_server" "unisync" {
  name        = "unisync"
  image       = "ubuntu-20.04"
  server_type = "cx11"
  location    = "hel1"
  ssh_keys    = ["personal"]
}
```

And I received next error

```
# tf init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/hcloud...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/hcloud: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/hashicorp/hcloud

If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to Terraform v0.13 first and follow the upgrade guide for
that release, which might help you address this problem.

Did you intend to use hetznercloud/hcloud? If so, you must specify that source
address in each module which requires that provider. To see which modules are
currently depending on hashicorp/hcloud, run the following command:
    terraform providers
```

Output of the `terraform providers`
```
Providers required by configuration:
.
└── provider[registry.terraform.io/hashicorp/hcloud]
```
---
The error is the same even if I just have
```
provider "hcloud" {

}
```
in the file.
Internet connections is fine. I tested `tf init` on gcp project, with `google` provider.

**Comment by ovitente** [comment]
### SOLVED
My mistake was in the fact that I ignored 0.13 upgrade for the new provider reference from the documentation.
https://www.terraform.io/upgrade-guides/0-13.html#explicit-provider-source-locations

I have applied command
```
terraform 0.13upgrade
```
and file `versions.tf` was created with:
```terraform
terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
    }
  }
  required_version = ">= 0.13"
}
```
inside.

After that `terraform init` has passed.

`google` provider was just lucky to avoid those changes.

**Comment by Radiergummi** [comment]
Mentioning that in the docs would be neat!
