### ISSUE TITLE
Import existing snapshot

### ISSUE THREAD

**Issue by Somebi** [hetznercloud/terraform-provider-hcloud#31]
I have tried multiple ways to do it, but it doesn't see existing snapshot, then i found info about import, but how to import a snapshot?

Any working example would be nice.

Thank you.

**Comment by Somebi** [comment]
* data.hcloud_image.image_1: data.hcloud_image.image_1: no image found with name master-1

**Comment by Somebi** [comment]
```
data "hcloud_image" "image_1" {
  name = "master-1"
}

```
```
resource "hcloud_server" "master" {
  count       = "${var.master_count}"
  name        = "master-${count.index + 1}"
  server_type = "${var.master_type}"
  image       = "${data.hcloud_image.image_1.name}"
```

**Comment by Somebi** [comment]
It seems it's not supported... Too bad, because there is some strange issue with apt lock and i need to add 60 seconds sleep to avoid that issue, a snapshot would resolve that.

**Comment by Somebi** [comment]
Oh well, will have to work with api directly then...

**Comment by LKaemmerling** [comment]
Hello, does the image "master-1" exists in your Hetzner cloud-console? Via the data source, this should work.

**Comment by Somebi** [comment]
Indeed, found the part responsible for it here:
https://github.com/terraform-providers/terraform-provider-hcloud/blob/master/hcloud/data_source_hcloud_image.go#L65

Yes it is, here screenshot, i have even got id from their endpoint response...
![image](https://user-images.githubusercontent.com/474017/45622057-699e4280-ba8b-11e8-8296-cd1b2791aa85.png)

**Comment by Somebi** [comment]
`Error: data.hcloud_image.image_1: "type": this field cannot be set`
Type cannot be set, isn't it in the schema...


```
2 error(s) occurred:

* hcloud_server.master[1]: 1 error(s) occurred:

* hcloud_server.master.1: missing image
* hcloud_server.master[0]: 1 error(s) occurred:

* hcloud_server.master.0: missing image
```

**Comment by Somebi** [comment]
Is there any debugging, to see actual api calls?

**Comment by Somebi** [comment]
Aha! Now working, it seems it doesn't want to work with names, only with ids. And i was picking the wrong id.

![image](https://user-images.githubusercontent.com/474017/45622347-5d66b500-ba8c-11e8-95c8-d5632f43b757.png)

**Comment by Somebi** [comment]
```
data "hcloud_image" "image_1" {
  id = 973257
}

resource "hcloud_server" "master" {
  count       = "${var.master_count}"
  name        = "master-${count.index + 1}"
  server_type = "${var.master_type}"
  image       = "${data.hcloud_image.image_1.id}"
```

So this way it's working.

**Comment by LKaemmerling** [comment]
After talking with our technical guys, i can say "works as expected". The property "name" is for system images only. Snapshots/Backups does not have a name, they have a description. But currently, the API does not offer a way to filter thought the description.

**Comment by Somebi** [comment]
Strange...
https://docs.hetzner.cloud/#images query param `name` exist in api...
In hetzner lib seems everything ok:
https://github.com/hetznercloud/hcloud-go/blob/master/hcloud/image.go#L93

Maybe that escape doing something nasty...

**Comment by Somebi** [comment]
It's not a description, it's a name, i have attached screenshot with raw json of snapshots.
I'll try to call api directly with my api token.

**Comment by Somebi** [comment]
Indeed, only providing type it's returning the list of snapshots, by providing name it doesn't return anything...
`curl -H "Authorization: Bearer $API_TOKEN" https://api.hetzner.cloud/v1/images?type=snapshot`

**Comment by Somebi** [comment]
But via id it's working:
`curl -H "Authorization: Bearer $API_TOKEN" https://api.hetzner.cloud/v1/images/973257`

**Comment by Somebi** [comment]
I think this should be noted somewhere here in repo and here in docs:
https://www.terraform.io/docs/providers/hcloud/d/image.html

**Comment by LKaemmerling** [comment]
Hello,

as you can see on your screenshot, the property "name" is empty, but on the system images it is not empty. 
![45622347-5d66b500-ba8c-11e8-95c8-d5632f43b757](https://user-images.githubusercontent.com/4281581/45623141-9ef46180-ba86-11e8-80aa-15df429d41c7.png)

**Comment by Somebi** [comment]
Yea, i guess there should be some updates in the go hetzner lib. A new method to return snapshots list and find requested snapshot with the provided name.

**Comment by Somebi** [comment]
Guess this can be closed then for now. Thanks for the quick reply.

**Comment by Somebi** [comment]
Ah, i got this now, need more coffee :D
Strange that snapshots can be fetched only via id, that id is not listed anywhere in the UI, only in direct api call...

**Comment by gbrault** [comment]
might be a bit late, but I have found a way to address this issue

- After creating the image, add a label (via the hetzner UI like "type unbuntudocker")
- add then the following in the terraform main file
```
data "hcloud_image" "ubuntudocker" {
  with_selector = "type=ubuntudocker"
}
resource "hcloud_server" "ubuntu18" {
  name = "ubuntu18"
  image = data.hcloud_image.ubuntudocker.id
  ....
}
```
