### ISSUE TITLE
20 min timeout on hcloud_server

### ISSUE THREAD

**Issue by persho** [hetznercloud/terraform-provider-hcloud#312]
Hey team,

We have run into an issue which became a blocker for us. 

We are trying to create "hcloud_server" resources with a pre-built image (snapshot), which sometimes gets a "context deadline exceeded" error after 20 minutes.

In the Hetzner console we can see that these servers are being created, but this takes sometimes 40-60 minutes. When 20 minutes are reached, Terraform reaches an error, and as the error stopped the Terraform apply execution, we have to rerun it, but even then sometimes it fails with the same error, but sometimes it goes through, depending if Hetzner cloud will manage to deploy the servers within 20 min time frame.

We have tested this with small and large images too, tried different instance sizes and non of these made any difference. The only way to make it work fast is to use default Hetzner images (not custom snapshots), but that option is not ideal for our use case, as we have pre-build images ready to be deployed. Our images are fairly large 20-30GB in size if that is relevant.

Could you please tell us if we could increase the 20 minute timeout so at least Terraform would not stop running the apply? This would be an ideal solution. At the moment, we cannot find a way.

Are there any other alternatives?

`module.application-cluster.hcloud_server.ln-app[1]: Still creating... [19m30s elapsed]
module.application-cluster.hcloud_server.ln-app[2]: Still creating... [19m30s elapsed]
module.application-cluster.hcloud_server.ln-app[2]: Still creating... [19m40s elapsed]
module.application-cluster.hcloud_server.ln-app[0]: Still creating... [19m40s elapsed]
module.application-cluster.hcloud_server.ln-app[1]: Still creating... [19m40s elapsed]
module.application-cluster.hcloud_server.ln-app[2]: Still creating... [19m50s elapsed]
module.application-cluster.hcloud_server.ln-app[1]: Still creating... [19m50s elapsed]
module.application-cluster.hcloud_server.ln-app[0]: Still creating... [19m50s elapsed]

Error: context deadline exceeded
Error: context deadline exceeded
Error: context deadline exceeded
ERROR: Job failed: exit code 1`

Thank you
Gabrijel

**Comment by ksophocleous** [comment]
We're facing the same problem with out pipelines failing because of this timeout

@persho did you find a workaround?

**Comment by persho** [comment]
Hey @ksophocleous,

we wrote several support emails to Hetzner, and they said the issue is most likely in their hub being slow, and they cannot do anything about it.

We did not find a workaround, we made our pipelines restartable, so in case they fail, we can restart them until they pass. 

It is not a nice flow, and it is making us think to move away from Hetzner, or implement some kind of automated retry solution.

Sorry I cannot help, but if you do find a way around it, please I am all ears :)

Cheers
Gabrijel

**Comment by ksophocleous** [comment]
Thanks for the response @persho,

> We did not find a workaround, we made our pipelines restartable, so in case they fail, we can restart them until they pass.

For now we just keep ours running which is a worse solution than what you came up with. I hope we find the time to address this soon.

> Sorry I cannot help, but if you do find a way around it, please I am all ears :)

I'll keep you posted if we figure something out!
