### ISSUE TITLE
Reverse DNS configuration

### ISSUE THREAD

**Issue by aspettl** [hetznercloud/terraform-provider-hcloud#32]
Hi,

I am experimenting with Terraform and the Hetzner Cloud and I have a problem with the reverse DNS settings.

First: "hcloud_floating_ip" provides "reverse_dns", but "hcloud_server" does not.

Second: "reverse_dns" of "hcloud_floating_ip" expects a map where the key is the IP address. (Minor point: the documentation does not say anything about the type being a map.) Naturally, I do not know the IP address before allocating the resource. But I also cannot reference the "ip_address" output of the same resource (Terraform: "self reference not allowed").  This means essentially I cannot use this feature except hardcoding the IP after is is known - or am I missing something?

**Not working due to self reference:**
<pre>
resource "hcloud_floating_ip" "myname" {
    type = "ipv4"
    description = "my name"
    home_location = "fsn1"
    reverse_dns = { "${hcloud_floating_ip.myname.ip_address}" = "mydomain.abc" }
}
</pre>

**Proposal:**
* Make reverse DNS configuration its own resource type (where Terraform can infer the implicit dependency), or
* Let the provider automatically prefix the key or somehow substitute the obtained IPv4 address / IPv6 prefix in.

The second one feels like a hack...

**My workaround for now:**
Use manual API calls in a "null_resource":
<pre>
resource "null_resource" "myname-dns-reverse" {
    provisioner "local-exec" {
        command = &lt;&lt;CMD
            curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${var.hcloud_token}" -d '{"ip":"${hcloud_floating_ip.myname.ip_address}","dns_ptr":"mydomain.abc"}' https://api.hetzner.cloud/v1/floating_ips/${hcloud_floating_ip.myname.id}/actions/change_dns_ptr
        CMD
    }
}
</pre>

**Comment by thetechnick** [comment]
> Make reverse DNS configuration its own resource type (where Terraform can infer the implicit dependency)

Good idea, I will add this in a future release.

**Comment by thetechnick** [comment]
Moved to https://github.com/terraform-providers/terraform-provider-hcloud/issues/5
