### ISSUE TITLE
token argument is not read correctly

### ISSUE THREAD

**Issue by aponert** [hetznercloud/terraform-provider-hcloud#324]
Take following code as example:

```
variable "hcloud_token" {
  type = string
  sensitive = true
}

terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
      version = "1.24.1"
    }
  }
}

provider "hcloud" {
  token = var.hcloud_token
}
```

When this code is inside the root module, it just works. However, for structural reasons, I use the root module only for loading  other modules:

```
module "hetzner_prod" {
  source = "./terraform/hetzner_prod"
  hcloud_token = "thisisnotmyrealtoken"
}
```

When the first code block is inside another module, which is loaded from the root module, it seems, that the token variable of the provider is not taken into account.

Neither 

```
provider "hcloud" {
  token = var.hcloud_token
}
```

Nor

```
provider "hcloud" {
  token = "thisisnotmyrealtoken"
}
```

will work.

I know I could use _HCLOUD_TOKEN_ env var but how to get it to work with terraform variables?

**Comment by LKaemmerling** [comment]
Hey @theq86,

sorry for the late reply. Did you follow the information on https://www.terraform.io/docs/language/modules/develop/providers.html ? The configuration is needed for Terraform. The provider plugin itself does not know about where it was run - in a (sub) module or in the root module.

From our side there is nothing we can change, therefore I would like to close the issue. If you think there is something we can do, feel free to reopen the issue.
