### ISSUE TITLE
Provide a metafield to store external informations for destroy provisionner

### ISSUE THREAD

**Issue by StarpTech** [hetznercloud/terraform-provider-hcloud#327]
Hi, due to the limitation of the destroy provisioner (introduced with terraform 0.13) it would be great when every resource had a property to store information temporarily. The information isn't persisted on hetzner.

```tf
resource "hcloud_server" "node1" {
  name = "node1"
  image = "debian-9"
  server_type = "cx11"

  null_attributes (sensitive) = {
	private_key = var.private_key
  }

  provisioner "remote-exec" {
	private_key = self.null_labels.private_key 
  }
}
```

> Because using external references on destroy provisionner is deprecated by Terraform, storing information inside each resources will be mandatory in order to manage several features like auto-draining node and fields management. So, several fields like connection block will be available in your TF state. This means that used password or private key will be clearly readable in this TF state.

https://github.com/xunleii/terraform-module-k3s#security-warning

References: https://github.com/hashicorp/terraform/issues/23679

**Comment by LKaemmerling** [comment]
Hey @StarpTech,

after reading the terraform issue i think this isn't something a provider can/should provide/fix. This needs to be fixed in terraform or better terraform needs a way to handle this.
