### ISSUE TITLE
Add example to documentation how to set reverse dns for a floating ip

### ISSUE THREAD

**Issue by c33s** [hetznercloud/terraform-provider-hcloud#33]
tried it by setting `ip_address` to the server ip address and specifing the `floating_ip_id`. this works but only set the reverse dns for the server and not for the floating ip. 
then i tried to use the floating ip address as `ip_address` but then i get the following error message: `hcloud_rdns.master_float: IP does not belong to the server (forbidden)`

```
resource "hcloud_floating_ip" "main_ip" {
  type = "ipv4"
  home_location = "nbg1"
}

//this works but only sets the rdns for the server
resource "hcloud_rdns" "master" {
  server_id = "${hcloud_server.test01.id}"
  ip_address = "${hcloud_server.test01.ipv4_address}"
  floating_ip_id = "${hcloud_floating_ip.main_ip.id}"
  dns_ptr = "example.com"
}

//this produces the error stated above
resource "hcloud_rdns" "master_float" {
  server_id = "${hcloud_server.test01.id}"
  ip_address = "${hcloud_floating_ip.main_ip.ip_address}"
  floating_ip_id = "${hcloud_floating_ip.main_ip.id}"
  dns_ptr = "example.com"
}
```

**Comment by LKaemmerling** [comment]
You can only set a server or a floating ip rdns per rdns resource, not one resource containing both.

**Comment by c33s** [comment]
strange i tried it and the ide showed me its wrong but it works as you wrote above.

from the point of view of the question it can be closed but adding a copy and paste example to the docs would not hurt.
