### ISSUE TITLE
Multiple rules in firewall

### ISSUE THREAD

**Issue by marvinpascale** [hetznercloud/terraform-provider-hcloud#332]
Hi team,
I need to insert more rules in 1 firewall. how can I do this?

`resource "hcloud_firewall" "myfirewall" {
  name = "my-firewall"
  rule {
   direction = "in"
   protocol = "icmp"
   source_ips = [
      "0.0.0.0/0",
      "::/0"
   ]
  }
}`
thank you,
Marvin

**Comment by LKaemmerling** [comment]
hey @marvinpascale,

You can specify the rule Block multiple times

**Comment by marvinpascale** [comment]
It work!
Thank you so much.
