### ISSUE TITLE
Firewall port ranges

### ISSUE THREAD

**Issue by berni2288** [hetznercloud/terraform-provider-hcloud#335]
Hi!
In the Hetzner Cloud console I can specify a port range, can I also do this with the Terraform provider? If yes, please change the doc :)

Can I use "any" for the port?

Thanks!

**Comment by berni2288** [comment]
I've checked the Hetzner API documentation (https://docs.hetzner.cloud/#firewalls) and assume that you can specify a port range as string in the format "start-end" and also use "any" for the port.

**Comment by LKaemmerling** [comment]
Hey @berni2288,

yep, you are right, you can specify port ranges via `start_port-end_port` (sample: `1-65535`) and also via `any`.
