### ISSUE TITLE
Firewall: Referencing ipv4_address of hcloud_server not possible because of cycle problem

### ISSUE THREAD

**Issue by berni2288** [hetznercloud/terraform-provider-hcloud#336]
I propose creating a new resource "hcloud_firewall_assignment" to allow referencing the ip adresses of a hcloud_server resource.

Right now this doesn't seem to be possible because Terraform gives you a "Error: Cycle" message because the hcloud_server resource instance references the firewall ID and the Firewall rule references the ipv4_address of the hcloud_server.
Assigning the Firewall Ids after hcloud_server creation would solve the problem, but I wasn't able to find anything in the Terraform documentation that this is supported.

Example code:

```
resource "hcloud_server" "node1" {
  name = "node1"
  image = "debian-9"
  server_type = "cx11"
  firewall_ids = [hcloud_firewall.myfirewall.id]
}

resource "hcloud_server" "node2" {
  name = "node2"
  image = "debian-9"
  server_type = "cx11"
  firewall_ids = [hcloud_firewall.myfirewall.id]
}

resource "hcloud_firewall" "myfirewall" {
  name = "myfirewall"

  rule {
    direction  = "in"
    protocol   = "tcp"
    port       = "any"
    source_ips = [
     format("%s/32", hcloud_server.node1.ipv4_address),
     format("%s/32", hcloud_server.node2.ipv4_address)
    ]
  }
}

```
Of course you could split it up into 2 rules for each IP, but I think this would make no difference.

**Comment by jekakm** [comment]
I'm also faced with this. I want to use IP addresses of created instances as source_ips

```
resource "hcloud_server" "master" {
  count = "${var.masters_count}"
  name = "master-${count.index + 1}"
  image = "debian-10"
  server_type = "${var.masters_type}"
  datacenter = "${var.cluster_datacenter}"
  keep_disk = true
  ssh_keys = ["${hcloud_ssh_key.default.id}"]
  user_data = "${file("master.conf")}"
  labels = {"k8s-nodetype" = "master"}
  firewall_ids = [hcloud_firewall.masters_firewall.id]
  lifecycle {
    ignore_changes = [
      user_data,
    ]
  }
}

resource "hcloud_firewall" "masters_firewall" {
  name = "masters_firewall"
  rule {
   direction = "in"
   protocol = "icmp"
   source_ips = [
      "0.0.0.0/0"
   ]
  }
  rule {
   direction = "in"
   protocol = "tcp"
   port = "22"
   source_ips = [
      "1.1.1.1/32",
      "2.2.2.2/32",
      "3.3.3.3/32"
   ]
  }
  rule {
   direction = "in"
   protocol = "tcp"
   port = "6443"
   source_ips = [
      "0.0.0.0/0"
   ]
  }
  rule {
   direction = "in"
   protocol = "tcp"
   port = "any"
   source_ips = hcloud_server.master.*.ipv4_address
  }
  rule {
   direction = "in"
   protocol = "udp"
   port = "any"
   source_ips = hcloud_server.master.*.ipv4_address
  }
}
```

And got Error: Cycle: hcloud_firewall.masters_firewall, hcloud_server.master. Have no idea how avoid this

**Comment by Sebbo94BY** [comment]
Same problem here:
```terraform
module "zabbix_server" {
  source = "./generic-server"

  hostname       = "zabbix"
  host_subdomain = var.host_subdomain
  domain         = var.domain

  server_type = "cx11"

  ssh_keys = [
    hcloud_ssh_key.ansible.id,
  ]

  keep_disk = true
  backups   = true

  firewall_ids = [
    hcloud_firewall.default_server.id,
    hcloud_firewall.zabbix_server.id,
  ]

  additional_labels = {
    "Environment" = "Develop",
  }

  instance_count = 1
}

resource "hcloud_firewall" "zabbix_agent" {
  name = "zabbix_agent"

  # Zabbix Agent (active)
  rule {
    direction = "in"
    protocol  = "tcp"
    port      = "10050"
    source_ips = [
      "${module.zabbix_server.hcloud_server["zabbix-1"].ipv4_address}/32",
      "${module.zabbix_server.hcloud_server["zabbix-1"].ipv6_address}/128",
    ]
  }

  # NTP
  rule {
    direction = "in"
    protocol  = "udp"
    port      = "123"
    source_ips = [
      "${module.zabbix_server.hcloud_server["zabbix-1"].ipv4_address}/32",
      "${module.zabbix_server.hcloud_server["zabbix-1"].ipv6_address}/128",
    ]
  }

  depends_on = [
    module.zabbix_server
  ]

  labels = merge(
    local.default_labels,
    var.additional_labels,
    {
      Description = "Allows-Zabbix-agent-traffic"
    },
  )
}

module "webserver" {
  source = "./generic-server"

  hostname       = "webserver"
  host_subdomain = var.host_subdomain
  domain         = var.domain

  server_type = "cx11"

  ssh_keys = [
    hcloud_ssh_key.ansible.id,
  ]

  keep_disk = true
  backups   = true

  firewall_ids = [
    hcloud_firewall.default_server.id,
    hcloud_firewall.zabbix_agent.id,
  ]

  additional_labels = {
    "Environment"      = "Develop",
  }

  instance_count = 1
}
```

Causes this error:
> Error: Cycle: module.zabbix_server.hcloud_rdns.ipv4, module.zabbix_server.hcloud_rdns.ipv6, module.zabbix_server (close), hcloud_firewall.zabbix_server, module.zabbix_server.var.firewall_ids (expand), module.zabbix_server.hcloud_server.generic_server, module.zabbix_server.output.hcloud_server (expand), hcloud_firewall.zabbix_agent, module.webserver.var.firewall_ids (expand), module.webserver.hcloud_server.generic_server, module.webserver.output.hcloud_server (expand)

I guess introducing the proposed Terraform resource `hcloud_firewall_assignment` would be the best solution. Are there already any plans to solve this issue?

**Comment by Sebbo94BY** [comment]
Any news regarding this issue? Due to this, we are unable to build some re-useable firewall rules. My current workaround is for example, to attach the firewall manually to all required hosts as Terraform reports this cycle problem.

@LKaemmerling did you already check this with your team?

**Comment by pier4r** [comment]
+1 I was planning to use this as well

**Comment by reperis** [comment]
Have the same issue with our deployment as well. Let us know if there is any workaround or when is this going to be fixed. Thanks!

**Comment by vaisov** [comment]
Same here. Would be great to get this fixed sooner as this is related to security.

**Comment by ambis** [comment]
I solved this via the new `apply_to` property in `hcloud_firewall`.

My use case is 5 kubernetes masters which want to talk to each others.

For each server I create a `hcloud_firewall` that has the server's IP address as source_ips and all the relevant ports.

Then I apply this rule via a common server label to all kubemasters. This finally stops the cyclic dependency issue because of the firewall being applied via a label.

**Comment by Sebbo94BY** [comment]
Any news regarding this topic after +6 months?
