### ISSUE TITLE
user_data - change should not force recreate

### ISSUE THREAD

**Issue by rosscdh** [hetznercloud/terraform-provider-hcloud#338]
Hi there thanks for the good provider.

One problem. i have noticed constantly especially with new setup is the cloud init usualy evoves.

Changing the user_data (cloud-init) should not force a recreate (should be an option). Rather leave the user to decide if the server should be recreated or not. either via destroy or an extra option.

Regards and thanks

**Comment by jekakm** [comment]
Just add to hcloud_server
```
lifecycle {
    ignore_changes = [
      user_data,
    ]
  }
```
And it will ignore changes in cloud init.

**Comment by rosscdh** [comment]
Perfect thanks!
