### ISSUE TITLE
Server gets assigned ip from wrong subnet

### ISSUE THREAD

**Issue by Zachu** [hetznercloud/terraform-provider-hcloud#340]
Howdy!

In a network divided into two subnets sometimes IP is assigned to the server from wrong subnet. Here we can see it in short:
```hcl
$ terraform state show 'module.k3s-server-0.module.main.hcloud_server_network.main[0]'
# module.k3s-server-0.module.main.hcloud_server_network.main[0]:
resource "hcloud_server_network" "main" {
    id          = "11122322-1083878"
    ip          = "10.90.0.129"
    mac_address = "86:00:00:a7:f7:65"
    server_id   = 11122322
    subnet_id   = "1083878-10.90.0.0/25"
}
```
As one can see, the subnet id shows that the ip assigned to the server `10.90.0.129` is outside of the cidr of that subnet which is supposed to be `10.90.0.0-10.90.0.127`.

The server has been assigned to the subnet with following resource that does not assign the ip manually:
```hcl
resource "hcloud_server_network" "main" {
  count = var.subnet != null ? 1 : 0

  server_id = hcloud_server.main.id
  subnet_id = var.subnet.id
}
```

Peeking into few more relevant resources:
```hcl
$ terraform state show 'module.k8s-net.hcloud_network.main'
# module.k8s-net.hcloud_network.main:
resource "hcloud_network" "main" {
    id       = "1083878"
    ip_range = "10.90.0.0/24"
    name     = "k8s-net"
}

$ terraform state show 'module.k8s-net.hcloud_network_subnet.main[0]'
# module.k8s-net.hcloud_network_subnet.main[0]:
resource "hcloud_network_subnet" "main" {
    gateway      = "10.90.0.1"
    id           = "1083878-10.90.0.0/25"
    ip_range     = "10.90.0.0/25"
    network_id   = 1083878
    network_zone = "eu-central"
    type         = "server"
}

$ terraform state show 'module.k8s-net.hcloud_network_subnet.main[1]'
# module.k8s-net.hcloud_network_subnet.main[1]:
resource "hcloud_network_subnet" "main" {
    gateway      = "10.90.0.1"
    id           = "1083878-10.90.0.128/25"
    ip_range     = "10.90.0.128/25"
    network_id   = 1083878
    network_zone = "eu-central"
    type         = "server"
}
```

and other meta information:
```sh
$ terraform --version
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hetznercloud/hcloud v1.26.0
```

I noticed I did the tests with old `terraform` version, but I can confirm that the same applies to `terraform v0.14.9`

**Comment by Zachu** [comment]
Ahh, further digging got me into this older issue https://github.com/hetznercloud/terraform-provider-hcloud/issues/265, and the note here https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/server_network:

> `subnet_id` - (Optional, string) ID of the sub-network which should be added to the Server. Required if network_id is not set. Note: if the ip property is missing, the Server is currently added to the last created subnet.

**Comment by Zachu** [comment]
So should I assume that the only way right now would be to manually assign the ip to the correct subnet range? `cidrhost` will help a bit but it's a bit cumbersome still when having many server resources defined here and there.

**Comment by LKaemmerling** [comment]
Hey @Zachu,

the `subnet_id ` is basically a `hack` to make sure that a subnetwork within the network exists, it is not directly an identifier to put a sever in a specific subnet. As you wrote you can use `cidrhost` for this, there is currently not way around it, sorry!

I will close the issue  as the problem seems to be resolved for me. If you still have any question feel free to write under this issue or, if it is another problem, open a new issue.

**Comment by Zachu** [comment]
@LKaemmerling Thanks for the answer. No need to reopen this one but do you think automatic IP assignment that would obey subnet assignments could be a possible feature in upcoming releases? Should there be a separate feature request for that?

**Comment by process0** [comment]
> the `subnet_id ` is basically a `hack` to make sure that a subnetwork within the network exists, it is not directly an identifier to put a sever in a specific subnet. As you wrote you can use `cidrhost` for this, there is currently not way around it, sorry!

This should be made clear in the documentation

**Comment by MartinNowak** [comment]
> the `subnet_id ` is basically a `hack` to make sure that a subnetwork within the network exists, it is not directly an identifier to put a sever in a specific subnet. As you wrote you can use `cidrhost` for this, there is currently not way around it, sorry!

When you already use `cidrhost` to calculate the IP address, what's the point of hcloud_server_network?
Referencing the `network_id` and `ip_range` through the subnet resource will already create the necessary dependencies.

```hcl
resource "hcloud_server" "myserver" {
  count = 2
  network {
    network_id = hcloud_network_subnet.foonet.network_id
    ip = cidrhost(hcloud_network_subnet.foonet.ip_range, count.index + 2)
 }
}
```
Would only "help" with a setup that obviously does not depend on subnet.
```hcl
resource "hcloud_server" "node1" {
  count = 2
  network {
    # does not depend on subnet
    network_id = hcloud_network.my-net.network_id
    ip = '10.51.0.2'
 }
}
```
