### ISSUE TITLE
Terraform S3 Backend Storage and state locking

### ISSUE THREAD

**Issue by Sebbo94BY** [hetznercloud/terraform-provider-hcloud#344]
Usually I'm storing my state file(s) in S3, so that the current state is always available to everyone in the team.

Additional - at AWS - we are also locking the state using DynamoDB, when someone is doing a `terraform apply` for example, that nobody else can do it at the same time.

Will there be similar features in the Hetzner Cloud in the future?

I don't want to mix the Hetzner Cloud with AWS, so I don't want to use AWS S3 and DynamoDB to solve this in the Hetzner Cloud.

**Comment by LKaemmerling** [comment]
Hey @Sebi94nbg,

as i see this isn't a Terraform specific request (it is more a general feature request) i would like to close the issue here, but i added a +1 (or better +5 based on the current upvotes) to the S3 on our Wishes List.
