### ISSUE TITLE
Label limits and Terraform error message

### ISSUE THREAD

**Issue by Sebbo94BY** [hetznercloud/terraform-provider-hcloud#345]
First of all: Why is the limit for labels only 63 characters? That's sometimes too less in my opinion.

AWS tags has for example these limits and requirements:
- Each resource can have a maximum of 50 user created tags.
- For each resource, each tag key must be unique, and each tag key can have only one value.
- The tag key must be a minimum of 1 and a maximum of 128 Unicode characters in UTF-8.
- The tag value must be a minimum of 0 and a maximum of 256 Unicode characters in UTF-8.

Besides the Hetzner Cloud label limits: When something is not valid, the error message only returns `Error: invalid input in field 'labels' (invalid_input)`. It would be much better when it could return something like "exceeds limit of maximum 63 characters" or "Invalid characters. Valid characters are ...".

```terraform
resource "hcloud_server" "generic_server" {
  name        = each.value
  server_type = var.server_type
  image       = data.hcloud_image.debian.name
  location    = var.location
  ssh_keys    = var.ssh_keys
  keep_disk   = var.keep_disk
  backups     = var.backups

  lifecycle {
    ignore_changes = [
      image,
      ssh_keys
    ]
  }

  labels = merge(
    local.default_labels,
    var.additional_labels,
    {
      hostname = each.value
      FQDN = "${each.value}.${var.domain}" # eg. "webserver-external-13.host.production.infrastructure.example.com"
    },
  )

  for_each = local.hostname
}
```
Would be very cool, when you could improve the labels and make them more useable. :)

**Comment by LKaemmerling** [comment]
Hey @Sebi94nbg,

i improved the error messages with #384, this will be part of the next release and therefore should improve the situation. For the label limits: I passed it to the team. As this is already improved by a lot with #384 i will close the issue here.
