### ISSUE TITLE
hcloud_server documentation

### ISSUE THREAD

**Issue by holgerson97** [hetznercloud/terraform-provider-hcloud#349]
In the newest version the network block is not described in argument reference.

**Comment by papanito** [comment]
There seems some reference but details are missing. See also https://discuss.hashicorp.com/t/how-to-access-network-attribute-for-hcloud-server/24538

**Comment by Adi146** [comment]
The missing network block was added here ad88a85f0be2e8477fab2b9e0351821ac0376574
