### ISSUE TITLE
How to set "poll_interval" provider option

### ISSUE THREAD

**Issue by EisenRatte** [hetznercloud/terraform-provider-hcloud#354]
The documentation says that you can set a "poll_interval" on the provider. 
When i try to set it like this, i get an error.
my.tf:
> provider "hcloud" {
    token = var.hcloud_token
    poll_interval = "1000ms"
}

error:
> Error: Unsupported argument 
An argument named "poll_interval" is not expected here.

i guess it has to be added to the provider schema in hcloud/provider.go ?

**Comment by LKaemmerling** [comment]
Hey @EisenRatte,

thank you for the issue, you are right it is/was missing there. I submitted an MR to fix it.
