### ISSUE TITLE
Version 1.26.1: Error: Failed to install provider

### ISSUE THREAD

**Issue by sasoiliev** [hetznercloud/terraform-provider-hcloud#362]
Hi,

I am getting the following error with the latest release of the provider:

```
❯ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding hetznercloud/hcloud versions matching "~> 1.26.0"...
- Installing hetznercloud/hcloud v1.26.1...

Error: Failed to install provider

Error while installing hetznercloud/hcloud v1.26.1: checksum list has
unexpected SHA-256 hash
9ca94fb8dd3dee5f56dc110e07681d39142154f08a34fb1392b2c085ac5c80b0 (expected
1b163bca4a5a7647be55217fa1dc4497895473f8faf707bf981958d3f0fda812)
```

Here's the Terraform code that reproduces the issue:

```
terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
      version = "~> 1.26.0"
    }
  }
  required_version = ">= 0.13"
}

provider hcloud {}

resource "hcloud_server" "test" {
  image = "debian-10"
  name = "test"
  location = "fsn1"
  server_type = "cx11"
}
```

For the time being I'd worked around the problem by requiring 1.26.0 explicitly, but this is obviously not ideal.

Thanks!

**Comment by fhofherr** [comment]
Hi @sasoiliev ,

we had some issues during the release of 1.26.1. The release 1.26.2 should fix this problem as soon as its pipeline finishes. Technically there are no changes, it is just a re-release of 1.26.1.

**Comment by sasoiliev** [comment]
Hi @fhofherr, indeed 1.26.2 works as expected. Thanks for the quick reaction!
