### ISSUE TITLE
Firewall for Load Balancer

### ISSUE THREAD

**Issue by sergelogvinov** [hetznercloud/terraform-provider-hcloud#365]
Hello.

Is it possible to add capabilities to set firewall rules (ip white list) to load balancer services?
Then you use tcp-lb, we lost the source ip address. 

```yaml
resource "hcloud_load_balancer_service" "api" {
  load_balancer_id = hcloud_load_balancer.example.id
  protocol         = "tcp"
  listen_port      = 443
  destination_port = 443

  # cidr white list
  source_ips = [
    "a.b.c.d/e",
    "a:b:c:d::/64"
  ]

  health_check {
    protocol = "tcp"
    port     = 443
    interval = 15
    timeout  = 5
    retries  = 3
  }
}
```

**Comment by LKaemmerling** [comment]
Hey @sergelogvinov,

this is currently not possible, but i added a +1 from you to the wishes list for "Firewall for Load Balancers". As this repo is used for our terraform provider and your request is more "generic" i will close it.

**Comment by sebastiangaiser** [comment]
+1
