### ISSUE TITLE
Document server import

### ISSUE THREAD

**Issue by Luzifer** [hetznercloud/terraform-provider-hcloud#37]
Add import of resources to documentation.

In case this is the web URL for the server:
```
https://console.hetzner.cloud/projects/<project_id>/servers/<server_id>/graphs
```

The import for the server would be:
```console
$ ./terraform import hcloud_server.<server_name> <server_id>
```

**Comment by thetechnick** [comment]
Hi @Luzifer,
import is now documented here:
https://github.com/hetznercloud/terraform-provider-hcloud/blob/master/website/docs/r/server.html.md#import

The documentation was updated in #36
