### ISSUE TITLE
Terraform hcloud_server doc does not inform about the firewall_ids

### ISSUE THREAD

**Issue by pier4r** [hetznercloud/terraform-provider-hcloud#370]
https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/server does not have as argument the firewall_ids , I know it is a new feature (as of 2021-06-02) but it can help.

**Comment by LKaemmerling** [comment]
Hey @pier4r,

thank you for your issue. I opened up an MR to fix the issue.
