### ISSUE TITLE
Fix documentation about hcloud_rdns

### ISSUE THREAD

**Issue by ThomasLandauer** [hetznercloud/terraform-provider-hcloud#371]
https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/rdns#argument-reference says that **both** `server_id` and `floating_ip_id` are required:

> Argument Reference
    dns_ptr - (Required, string) The DNS address the ip_address should resolve to.
    ip_address - (Required, string) The IP address that should point to dns_ptr.
    server_id - (**Required**, int) The server the ip_address belongs to.
    floating_ip_id - (**Required**, int) The Floating IP the ip_address belongs to.

But at https://github.com/hetznercloud/terraform-provider-hcloud/issues/33#issuecomment-423947740 you're saying that this is wrong:

> You can only set a server or a floating ip rdns per rdns resource, **not one resource containing both.**

So please fix the documentation!

**Comment by LKaemmerling** [comment]
Hey @ThomasLandauer,

thank you for your Issue. I opened up an MR to improve this.
