### ISSUE TITLE
hcloud_server: user_data change = "must be replaced"

### ISSUE THREAD

**Issue by src386** [hetznercloud/terraform-provider-hcloud#372]
hetznercloud/hcloud v1.26.2

According to the [documentation](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/server):

> user_data - (Optional, string) Cloud-Init user data to use during server creation

However if you create a server with a cloud-init then make changes and apply, it will be replaced.

Steps to reproduce:
- Create a hcloud_server resource with a `user_data`
- Edit `user_data` and run `terraform plan`

```
# hcloud_server.kubernetes-0 must be replaced
-/+ resource "hcloud_server" "kubernetes-0" {
      + backup_window = (known after apply)
      ~ datacenter    = "hel1-dc2" -> (known after apply)
      ~ id            = "hidden" -> (known after apply)
      ~ ipv4_address  = "hidden" -> (known after apply)
      ~ ipv6_address  = "hidden" -> (known after apply)
      ~ ipv6_network  = "hidden" -> (known after apply)
        name          = "vm-prod-kubernetes-0"
      ~ status        = "running" -> (known after apply)
      ~ user_data     = "2b0nBEwRjGDq7wGwUg3Jzy80FJE=" -> "5ueysdsAQtDmX+SKTy0OIP9t0x8=" # forces replacement
        # (8 unchanged attributes hidden)

      - network {
          - alias_ips  = [] -> null
          - network_id = hidden -> null
        }
      + network {
          + alias_ips   = []
          + ip          = (known after apply)
          + mac_address = (known after apply)
          + network_id  = hideen
        }
    }

```

What I expect:
- Existing servers should not updated at all, `cloud-init` should be used (according to documentation) only at creation.

**Comment by LKaemmerling** [comment]
Hey @src386,

i would suggest you using https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#ignore_changes . Based on the feedback we got so far, the most wanted behavior would be "create the server completely new when we change the userdata". With the ignore_changes meta argument you can explicitly ignore changes on the userdata.
