### ISSUE TITLE
Provider fails to initialize in modules

### ISSUE THREAD

**Issue by dminaev** [hetznercloud/terraform-provider-hcloud#378]
Hello,
I try to organize my code in modules, but if a module attempts to create a resource using hcloud, `terraform init` gives this error:
```
Initializing provider plugins...
- Reusing previous version of hetznercloud/hcloud from the dependency lock file
- Reusing previous version of hashicorp/aws from the dependency lock file
- Finding latest version of hashicorp/hcloud...
- Using previously-installed hashicorp/aws v3.45.0
- Using previously-installed hetznercloud/hcloud v1.26.2
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/hcloud: provider registry registry.terraform.io does not have a provider named
│ registry.terraform.io/hashicorp/hcloud
│ 
│ Did you intend to use hetznercloud/hcloud? If so, you must specify that source address in each module which requires that provider. To see which modules
│ are currently depending on hashicorp/hcloud, run the following command:
│     terraform providers
```
Here's the output of `terraform providers`:
```
Providers required by configuration:
.
├── provider[registry.terraform.io/hetznercloud/hcloud]
├── provider[registry.terraform.io/hashicorp/aws]
└── module.mod_zookeeper
    ├── provider[registry.terraform.io/hashicorp/hcloud]
    └── provider[registry.terraform.io/hashicorp/aws]
```
Redefining the provider in the module is impossible, because the module is used in `count` block:
```
│ Providers cannot be configured within modules using count, for_each or depends_on.
```
Outside of modules, the providers works alright.
Not sure if this problem is caused by the provider or Terraform itself, frankly speaking, but the provider details are not correctly inherited in modules, it seems.

**Comment by LKaemmerling** [comment]
Hey @dminaev,

can you provide a minimal configuration that shows this behavior? The provider itself does not know about how it is called, so this looks like a terraform issue for me. Please also have a look at https://www.terraform.io/docs/language/modules/develop/providers.html, this might help you.

**Comment by dminaev** [comment]
Sorry, I didn't specify provider source in the module. Please, delete this issue.
