### ISSUE TITLE
Creating 5 servers timeout

### ISSUE THREAD

**Issue by snapo** [hetznercloud/terraform-provider-hcloud#38]
Hi ,
I created a simple terraform script to create 5 servers with ubuntu.
The first 4 get created successfully but the 5. one did timeout.

What is the timeout set for the API to respond?
Or is there a specific limit from hetzner not more then X requests?

Project:
https://github.com/snapo/tfhcloud <-- switched back to 1 server, i did just copy 5 times the create server resource then startet everything... but the maximum i can create at a time is 4 servers...

Thanks already

**Comment by thetechnick** [comment]
Hi @snapo,
sorry that it took so long I somehow missed this issue.

There was an issue with `hcloud-go` that resulted in running into the rate limits of our API, this could lead to the timeouts you have encountered.
In the meantime we have released a new provider that should not run into this problem
