### ISSUE TITLE
Properly set hcloud_server.ipv6_address

### ISSUE THREAD

**Issue by thcyron** [hetznercloud/terraform-provider-hcloud#39]
Related issue: https://github.com/hetznercloud/hcloud-go/pull/101

TL;DR: The provider sets `ipv6_address` to the IPv6 network address, but it should set it to the first IPv6 address (i.e. network + 1) which actually is configured on the server.

**Comment by LKaemmerling** [comment]
We decided to currently not change this, because it is a breaking change. 

With the next version of terraform (0.12) we will release a version, that will contain this bugfix/change.

**Comment by danielgrant** [comment]
Hi @LKaemmerling, any update on this?

Up until now, I've just been working around this with a bit of a hack by hardcoding a `1` onto the end of `ipv6_address`:

```
"${hcloud_server.server.ipv6_address}1"
```

Now that 0.12 has been released, I've upgraded:

```
$ terraform --version
Terraform v0.12.2
+ provider.hcloud v1.10.0
```

But the provider is still exhibiting the same issue. If I remove the `1` from the end of `ipv6_address`:

```
Terraform will perform the following actions:

  # hcloud_rdns.example_com-ipv6 must be replaced
-/+ resource "hcloud_rdns" "example_com-ipv6" {
        dns_ptr    = "example.com"
      ~ id         = "s-xxxxxxx-xxxx:xxx:xxxx:xxxx::1" -> (known after apply)
      ~ ip_address = "xxxx:xxx:xxxx:xxxx::1" -> "xxxx:xxx:xxxx:xxxx::" # forces replacement
        server_id  = xxxxxxx
    }
```

**Comment by LKaemmerling** [comment]
@danielgrant currently not, I asked the terraform guys because of this breaking change. They wanted to don't have a breaking change introduced in the same version with the terraform 0.12 upgrade.

**Comment by invidian** [comment]
It seem that what `ipv6_address` returns is correct from API point of view. Perhaps one could just use `cidrhost(ipv6, 1)`?

Alternatively, perhaps having additional parameter named` ipv6_network` could be added for convenience and then `ipv6_address` could return the address with :1.
