### ISSUE TITLE
`hcloud_snapshot` documentation stops mid sentence

### ISSUE THREAD

**Issue by athre0z** [hetznercloud/terraform-provider-hcloud#397]
https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/snapshot

This paragraph currently stops mid-sentence:

```
Provides a Hetzner Cloud snapshot to represent a image with type snapshot in the Hetzner Cloud. This resource makes it easy to create 
```

**Comment by LKaemmerling** [comment]
Hey @athre0z,

thank you! I fixed it with https://github.com/hetznercloud/terraform-provider-hcloud/pull/398.
