### ISSUE TITLE
Block Storage Support

### ISSUE THREAD

**Issue by thetechnick** [hetznercloud/terraform-provider-hcloud#4]
Moved from https://github.com/hetznercloud/terraform-provider-hcloud/issues/24

**Comment by ghost** [comment]
@thetechnick is future block storage on Hetzner going to be flexible size like EBS or fixed size like OVH in chunks of 100GB, 500GB etc...?

**Comment by LKaemmerling** [comment]
@pouledodue currently, we can not provide information about it. When there is a new state on our system, we will publish more information about it.

**Comment by solidnerd** [comment]
Any updates for this ?

**Comment by LKaemmerling** [comment]
@solidnerd currently there are no updates on this. We does not announce a roadmap for our cloud, but you can grab new information from our Twitter account: https://twitter.com/Hetzner_Online

**Comment by rahulmukati** [comment]
Really needed block storage badly. Hope you guys bring it really soon. 😊

**Comment by lfrancke** [comment]
The Volume feature has just been [announced](https://www.hetzner.com/news/10-18-cloud-volumes/) and a beta has started. The docs are already [available](https://docs.hetzner.cloud/#volumes).

They are flexible in size in 1GB increments from 10GB to 10TB.

**Comment by ghost** [comment]
no Falkenstein :(

**Comment by rahulmukati** [comment]
Wow! Hetzner heard me fast! 😛
Thanks! That what we needed! ❤️

**Comment by voron** [comment]
300MB/s random read + 300MB/s random write, up to 10k IOPS, awesome!

**Comment by LKaemmerling** [comment]
The new hcloud terraform provider version (1.4.0) is now released. It contains support for our volumes.
