### ISSUE TITLE
Setting a route on hcloud_server_network

### ISSUE THREAD

**Issue by rightaway** [hetznercloud/terraform-provider-hcloud#403]
Shouldn't there be a way to add a route for a particular server (not just on `hcloud_network` for the whole network) in `hcloud_server_network`? Otherwise we have to go into the server and mess with various config files to add it, which interferes with the defaults that hcloud sets, like ip address, default gateway and dhcp settings.

For example if I create `hcloud_network_route` with like `destination = "10.1.0.0/16"` and `gateway = "ip of hcloud server"`, I need to add a route on all other hcloud servers to set `destination = "10.1.0.0/16"` and set the `gateway` to the ip address of the `hcloud_network` for it to route that destination through the main gateway. It makes sense for hcloud to set the route at the same time it assigns the ip address and other things.

I could try to set routes in cloudinit but then the server doesn't keep up to changes with cloudinit since it's just run when first initialized. How exactly does hcloud set the network details within the server?

**Comment by LKaemmerling** [comment]
Hey @rightaway,

the network interface is only attached one time (similar to cloud init), so when you change the routes you would need to change it on the server as well. Also, we don't want to change something of the server configuration (or: We don't want to have software running in those servers that would enable us to do something on the server), as this is not how we think about our platform. A customer should maintain his server completely and we just gave you the "hardware", that is why we basically just plug in the network card/volume and let an [autoconfiguration](https://github.com/hetznercloud/hc-utils) run.
