### ISSUE TITLE
[Bug]: wrong network mask ot target host

### ISSUE THREAD

**Issue by avkovalevs** [hetznercloud/terraform-provider-hcloud#410]
### What happened?

Hi!
I use the terraform code for infrastructure deployment like this:

`resource "hcloud_network" "network" {
  name     = "network"
  ip_range = "10.0.1.0/24"
}

resource "hcloud_network_subnet" "private-network" {
  network_id   = hcloud_network.network.id
  type         = "server"
  network_zone = "eu-central"
  ip_range     = "10.0.1.0/26"
  #vswitch_id   = 400
  depends_on = [hcloud_network.network]
}

resource "hcloud_server" "pg" {
  count       = "2"
  name        = "pgnode-${count.index}"
  server_type = "cx11"
  image       = "ubuntu-18.04"
  location    = "hel1"
  keep_disk   = true
  ssh_keys    = ["${hcloud_ssh_key.avkovalevs.id}"]
  network {
    network_id  = hcloud_network.network.id
  }
  depends_on = [hcloud_network_subnet.private-network]
}
`
However, when I connected to target host I saw IP like  this:
3: ens10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc fq_codel state UP group default qlen 1000
    link/ether 86:00:00:ca:66:fa brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.2/32 brd 10.0.1.2 scope global ens10

IP has a wrong network mask. I expected to see IP like 10.0.1.2/26
I don't know this is my error in the code or typical behavior of Hetzner API.
Is there a way to get ip like  10.0.1.2/26 on a target node?

### What did you expect to happen?

I want to get IP with right netmask /26

### Please provide a minimal working example

resource "hcloud_network" "network" {
  name     = "network"
  ip_range = "10.0.1.0/24"
}

resource "hcloud_network_subnet" "private-network" {
  network_id   = hcloud_network.network.id
  type         = "server"
  network_zone = "eu-central"
  ip_range     = "10.0.1.0/26"
  #vswitch_id   = 400
  depends_on = [hcloud_network.network]
}

resource "hcloud_server" "pg" {
  count       = "2"
  name        = "pgnode-${count.index}"
  server_type = "cx11"
  image       = "ubuntu-18.04"
  location    = "hel1"
  keep_disk   = true
  ssh_keys    = ["${hcloud_ssh_key.avkovalevs.id}"]
  network {
    network_id  = hcloud_network.network.id
  }
  depends_on = [hcloud_network_subnet.private-network]
}

**Comment by LKaemmerling** [comment]
Hey @avkovalevs,
The server always gets a /32 up, the subnet you configure I basically just a frame within the network where you can group your servers. Technically the server gets one ip of a subnet from the network (or the ip you configured that must be part of a subnetwork), the server can (per default) reach all servers in the network through the configured gateway. I hope this explanation helps you to understand the behavior. I would like to close the issue for now, if you still have questions feel free to write here again.
