### ISSUE TITLE
[Bug]: Unable to retrieve Network.id through CDKTF

### ISSUE THREAD

**Issue by ZakHargz** [hetznercloud/terraform-provider-hcloud#413]
### What happened?

I'm looking at trailing Terraform CDK with the provider of `"terraformProviders": ["hetznercloud/hcloud@~> 1.27.2"]`

I'm trying to create a simple Network and attach a subnet to id, but when I try and retrieve the NetworkID from the network, it's coming through as a string and not Number:

Please see below: 

This is my Typescript

`const SwarmNetwork = new Network(this, 'DockerSwarmPrivNetwork', { name: 'Docker_Swarm_Network', ipRange: '10.10.10.0/24' });
    new NetworkSubnet(this, 'MainSwarmSubnet', { networkId: SwarmNetwork.id, ipRange: '10.10.10.0/24', networkZone: 'eu-central', type: 'cloud' });`

This is my synth output:

`⠼ planning Dev-DockerSwarmStack...
[2021-07-22T11:33:47.305] [DEBUG] default - ╷
│ Error: Missing required argument
│ 
│   with hcloud_network_subnet.MainSwarmSubnet,
│   on cdk.tf.json line 61, in resource.hcloud_network_subnet.MainSwarmSubnet:
│   61:         "network_id": null,
│ 
│ The argument "network_id" is required, but no definition was found.
╵

╷
│ Error: Missing required argument
│ 
│   with hcloud_network_subnet.MainSwarmSubnet,
│   on cdk.tf.json line 61, in resource.hcloud_network_subnet.MainSwarmSubnet:
│   61:         "network_id": null,
│ 
│ The argument "network_id" is required, but no definition was found.
╵
non-zero exit code 1`

It would be great if we could return this value as Number and allow us to pass the ids through various consts in the stack. 

I can provide the source code if required. 

### What did you expect to happen?

I would expect the network_id to be pulled and accepted as an allowed value. 

### Please provide a minimal working example

N/A

**Comment by LKaemmerling** [comment]
Hey @ZakHargz,

we do not officially support the CDK. In addition on our "side" the network_id is always an integer (it was never a string).  In Terraform all IDs from resources (e.g. your `SwarmNetwork.id`) are always strings.

I think there is nothing we can do here.

**Comment by gc-ss** [comment]
> I'm trying to create a simple Network and attach a subnet to id, but when I try and retrieve the NetworkID from the network, it's coming through as a string and not Number:


@ZakHargz Attempt to use the `Token().asNumber` on the attribute that's a resolvable at runtime
