### ISSUE TITLE
[Feature]: Inject authorized key for non-root user

### ISSUE THREAD

**Issue by cedws** [hetznercloud/terraform-provider-hcloud#417]
### What would you like to see?

The `hcloud_server` resource provides the `ssh_keys` parameter for injecting authorized SSH keys for the `root` user. I would like to instead inject an authorized key for another user, such as `ubuntu`. This is the way GCP does it, and it also create a sudoers `NOPASSWD` rule for the user to my understanding.

The reason I would like this is because our Ansible provisioning process immediately toggles  `AllowRootLogin` to `no` for security, but can cause lockouts if another user or authentication mechanism is not yet set up. Why not fix our process? Because I think it would be generally good practice to not allow root login to begin with.

I understand that this module ultimately relies on the Hetzner API which might not be able to achieve this.

**Comment by LKaemmerling** [comment]
Hey @cedws,

You can already to this by using a cloud init script (userdata).
