### ISSUE TITLE
[Bug]: hcloud_server.xxx must be replaced when add new SSH key

### ISSUE THREAD

**Issue by FrolovVyacheslav** [hetznercloud/terraform-provider-hcloud#428]
### What happened?

Hi. I'm trying to add a new SSH key to the server, but terraform apply is re-creating that server. How to avoid this behavior?

Terraform *v1.0.4*
on linux_amd64
+ provider registry.terraform.io/hetznercloud/hcloud *v1.29.0*

### What did you expect to happen?

Adding a key without re-creating the server

### Please provide a minimal working example

My simple main.tf file:

terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
      version = "1.29.0"
    }
  }
}

variable "hcloud_token" {}
provider "hcloud" {
  token = var.hcloud_token
}

resource "hcloud_ssh_key" "id_rsa" {
  name = "id_rsa"
  public_key = file("pubKeys/id_rsa.pub")
}
resource "hcloud_ssh_key" "id_rsa_2" {
  name = "id_rsa_2"
  public_key = file("pubKeys/id_rsa_2.pub")
}

resource "hcloud_server" "server01" {
  image = "ubuntu-20.04"
  name = "ubuntu"
  server_type = "cx11"
  location = "hel1"

  ssh_keys = [
    hcloud_ssh_key.id_rsa.id,
    hcloud_ssh_key.id_rsa_2.id  # need to add this key
  ]
}

**Comment by LKaemmerling** [comment]
Hey @FrolovVyacheslav,

this is not a bug, it "works" as expected. Terraform always tries to reach the state you define. You define that this Server should be created with two SSH Keys now. As we can not update the ssh keys (only on the creation of the server), we need to recreate it. 

From provider side it works as expected. You can of course use https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#ignore_changes to limit this.
