### ISSUE TITLE
provisioner stopping in the middle when apt-get running

### ISSUE THREAD

**Issue by micwin** [hetznercloud/terraform-provider-hcloud#43]
apt-get doesnt seem to work properly when called in a remote_exec provisioner with hcloud:

This is the resource:

    resource "hcloud_server" "kvstore" {
      count = 1
      name = "kvstore-${count.index}"
      image = "${var.small_image}"
      server_type = "${var.small_server_type}"
      datacenter = "${var.datacenter}"
      ssh_keys = [ "${hcloud_ssh_key.local.id}" ]

      connection {
        type     = "ssh"
        user     = "root"
        private_key = "${file("~/.ssh/id_rsa")}"
      }

      # copy over systemd unit
      provisioner "file" {
           source = "consul.service"
           destination = "/etc/systemd/system/consul.service"
      }

      provisioner "remote-exec" {
        inline = [
          "apt-get update && apt-get upgrade -y && apt-get install -y unzip",
          "wget https://releases.hashicorp.com/consul/1.3.0/consul_1.3.0_linux_amd64.zip",
          "unzip /tmp/consul_*.zip && mv /tmp/consul /usr/bin/consul",
          "mkdir /etc/consul.d",
          "mkdir /var/lib/consul",
          "# systemctl enable consul" ,
          "# systemctl start consul"
        ]
      }
    }

this is what I get

```
/usr/bin/terraform apply -var-file=wikids.tfvars -auto-approve
hcloud_ssh_key.local: Creating...
  fingerprint: "" => "<computed>"
  name:        "" => "local"
  public_key:  "" => "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCw2nRi/u1VoA2HTdOyX9e7ew40d6WjpjXzQHUzwS1GEYe+Q84Qs8y7Z3eROnTQzkb5Tmp24o0P2YIMFKiKa/l3Ovp8ef9jq3NPi2oXP08+4BH+YtWArARHvBCeHIU8CPlmv7sheKWnbDcyoa8gLsioeSpVer+tOxlL5elLdfA8/Oz18jSN0UYhHGX15zJHO693ITazbrvnl3oG1f3mGtbgS4itiLG5+e7xvDdc+3a35EcVi4ttGIkvuDN8Uw4GAatpsrufyVB9FElmEHu0rM4+HSKwlDPrgAxbA2rMKnFo/qeJJgGXqiDf8IQm6jUrM9DK4x6CTJP7T+uwvGKNoyYx micwin"
hcloud_ssh_key.local: Creation complete after 0s (ID: 166314)
hcloud_server.kvstore: Creating...
  datacenter:   "" => "hel1-dc2"
  image:        "" => "ubuntu-16.04"
  ipv4_address: "" => "<computed>"
  ipv6_address: "" => "<computed>"
  ipv6_network: "" => "<computed>"
  keep_disk:    "" => "false"
  location:     "" => "<computed>"
  name:         "" => "kvstore-0"
  server_type:  "" => "cx11"
  ssh_keys.#:   "" => "1"
  ssh_keys.0:   "" => "166314"
  status:       "" => "<computed>"
hcloud_server.kvstore: Still creating... (10s elapsed)
hcloud_server.kvstore: Provisioning with 'file'...
hcloud_server.kvstore: Still creating... (20s elapsed)
hcloud_server.kvstore: Provisioning with 'remote-exec'...
hcloud_server.kvstore (remote-exec): Connecting to remote host via SSH...
hcloud_server.kvstore (remote-exec):   Host: 95.216.190.46
hcloud_server.kvstore (remote-exec):   User: root
hcloud_server.kvstore (remote-exec):   Password: false
hcloud_server.kvstore (remote-exec):   Private key: true
hcloud_server.kvstore (remote-exec):   SSH Agent: true
hcloud_server.kvstore (remote-exec):   Checking Host Key: false
hcloud_server.kvstore (remote-exec): Connected!
hcloud_server.kvstore: Still creating... (30s elapsed)
hcloud_server.kvstore (remote-exec): Reading package lists... 0%
hcloud_server.kvstore (remote-exec): Reading package lists... 0%
hcloud_server.kvstore (remote-exec): Reading package lists... 19%
hcloud_server.kvstore (remote-exec): Reading package lists... Done
hcloud_server.kvstore (remote-exec): E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
hcloud_server.kvstore (remote-exec): E: Unable to lock directory /var/lib/apt/lists/
hcloud_server.kvstore (remote-exec): --2018-11-08 21:57:03--  https://releases.hashicorp.com/consul/1.3.0/consul_1.3.0_linux_amd64.zip
hcloud_server.kvstore (remote-exec): Resolving releases.hashicorp.com (releases.hashicorp.com)... 151.101.13.183, 2a04:4e42:3::439
hcloud_server.kvstore (remote-exec): Connecting to releases.hashicorp.com (releases.hashicorp.com)|151.101.13.183|:443... connected.
hcloud_server.kvstore (remote-exec): HTTP request sent, awaiting response... 200 OK
hcloud_server.kvstore (remote-exec): Length: 34158878 (33M) [application/zip]
hcloud_server.kvstore (remote-exec): Saving to: ‘consul_1.3.0_linux_amd64.zip’

hcloud_server.kvstore (remote-exec):       consu   0%       0  --.-KB/s
hcloud_server.kvstore (remote-exec):      consul   2% 811.74K  3.93MB/s
hcloud_server.kvstore (remote-exec):     consul_   6%   2.28M  5.66MB/s
hcloud_server.kvstore (remote-exec):    consul_1  14%   4.64M  7.69MB/s
hcloud_server.kvstore (remote-exec):   consul_1.  25%   8.36M  10.4MB/s
hcloud_server.kvstore (remote-exec):  consul_1.3  43%  14.17M  14.1MB/s
hcloud_server.kvstore (remote-exec): consul_1.3.  71%  23.44M  19.4MB/s
hcloud_server.kvstore (remote-exec): consul_1.3. 100%  32.58M  24.3MB/s    in 1.3s

hcloud_server.kvstore (remote-exec): 2018-11-08 21:57:05 (24.3 MB/s) - ‘consul_1.3.0_linux_amd64.zip’ saved [34158878/34158878]

hcloud_server.kvstore (remote-exec): /tmp/terraform_363884108.sh: 4: /tmp/terraform_363884108.sh: unzip: not found
hcloud_server.kvstore: Creation complete after 33s (ID: 1347622)

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Process finished with exit code 0

```

Same result if I separate the apt-get sequence like so:

```
provisioner "remote-exec" {
    inline = [
      "apt-get update",
      "apt-get upgrade -y",
      "apt-get install -y unzip",
      "wget https://releases.hashi.....
```

If I modify the provisioner to this:

```
provisioner "remote-exec" {
    inline = [
      "apt-get install -y unzip",
      "wget https://releases.hashicorp.com/consul/1.3.0/consul_1.3.0_linux_amd64.zip",
      "unzip /tmp/consul_*.zip && mv /tmp/consul /usr/bin/consul",
      "mkdir /etc/consul.d",
      "mkdir /var/lib/consul",
      "# systemctl enable consul" ,
      "# systemctl start consul"
    ]
  }
```

then the result looks different:

```
hcloud_server.kvstore (remote-exec):   Checking Host Key: false
hcloud_server.kvstore (remote-exec): Connected!
hcloud_server.kvstore (remote-exec): Reading package lists... 0%
hcloud_server.kvstore (remote-exec): Reading package lists... 100%
hcloud_server.kvstore (remote-exec): Reading package lists... Done
hcloud_server.kvstore (remote-exec): Building dependency tree... 0%
hcloud_server.kvstore (remote-exec): Building dependency tree... 0%
hcloud_server.kvstore (remote-exec): Building dependency tree... 50%
hcloud_server.kvstore (remote-exec): Building dependency tree... 50%
hcloud_server.kvstore (remote-exec): Building dependency tree
hcloud_server.kvstore (remote-exec): Reading state information... 0%
hcloud_server.kvstore (remote-exec): Reading state information... 1%
hcloud_server.kvstore (remote-exec): Reading state information... Done
hcloud_server.kvstore (remote-exec): E: Unable to locate package unzip
hcloud_server.kvstore (remote-exec): --2018-11-08 2
```

btw, completely silencing the output doesnt help.

Does this make any sense to you?

Greetings,

Michael

**Comment by LKaemmerling** [comment]
The server needs some time to come up. You should place a "sleep" in front of the "apt-get update" to avoid this:
```
hcloud_server.kvstore (remote-exec): E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
hcloud_server.kvstore (remote-exec): E: Unable to lock directory /var/lib/apt/lists/
```

See https://github.com/terraform-providers/terraform-provider-hcloud/issues/29#issuecomment-420959704 for more information about this (the last paragraph).

**Comment by micwin** [comment]
Tried that, 5 secs before each apt-get; same result. What is the time I should wait before calling an apt-get?

Anyway, corresponding to openstack api, isnt the server supposed to be ready for provisioners at the moment provisioners are activated? Sounds a little bit odd,...

**Comment by micwin** [comment]
when putting a sleep 30 at the beginning, everything is wprking fine:

```
provisioner "remote-exec" {
    inline = [
      "echo sleeping 30s to make sure server has been booted",
      "sleep 30",
      "apt-get ..."
```

but I have 2000 mins of build time each month in gitlab, really dont want to waste 30secs each build for waiting.

Still consider it a bug that provisioners run at boot time.

**Comment by LKaemmerling** [comment]
A sleep of 10 seconds should be enough. 

From our side, the server is "ready" when it has the status "running". Cloud Init performs some actions on the first boot, that takes some little time.

**Comment by micwin** [comment]
Being ready in the midst of initialization sounds odd to me.

Am not so long in the terraform business to know, but what's the behavior here of other providers like aws or  gcp? If the behavior is the same here (ready before cloud-init finish), it's okay by me as well.

**Comment by micwin** [comment]
sleeping  10s to get apt-get stable are still not enough. 20s look fine.

**Comment by micwin** [comment]
with rising complexity now 20s isnt enough too. Using 30s.

**Comment by LKaemmerling** [comment]
@micwin can you please write us a ticket over the cloud console with this problem? I'll close it here, since this is not a problem with the terraform provider (directly).

**Comment by chriskosch** [comment]
Havent u seen that is complaining about uzip?¿.
hcloud_server.kvstore (remote-exec): /tmp/terraform_363884108.sh: 4: /tmp/terraform_363884108.sh: unzip: not found

Use user-data to install it first:

#cloud-config
users:
  - name: XXXXX
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa <>
package_update: true
package_upgrade: true
packages:
  - unzip
  - gzip
  - zip
 runcmd:
  - sed -ie '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -ie '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -ie '/^X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -ie '/^#MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - sed -ie '/^#AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -ie '/^#AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -ie '/^#AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers XXXXXX' /etc/ssh/sshd_config
  - systemctl restart ssh
