### ISSUE TITLE
Question: How to activate backups using terraform? 

### ISSUE THREAD

**Issue by spommerening** [hetznercloud/terraform-provider-hcloud#44]
I tried to use the `backup_window` parameter when creating a server but this did not work any more. 
Then I found this Pull Request:
 #34 

Did you remove this from the API? Why? And what is the replacement? 
Activating backups using the console still works, but shouldn't there be an automatic option?

**Comment by LKaemmerling** [comment]
We removed the option to specify the window (time frame) for the backup. See https://docs.hetzner.cloud/#overview-changelog for more information. In the next version, there will be a new flag to enable backups.

**Comment by spommerening** [comment]
Looking forward to the upcoming new release ;-)
