### ISSUE TITLE
import server force delete of resource

### ISSUE THREAD

**Issue by giovannicandido** [hetznercloud/terraform-provider-hcloud#46]
I cloned and moved a server from available zones.
Then a removed the server from terraform state, import and run plan.
Terraform is trying to destroy and create the server, more strage it has imported hte ips and sshkeys.

```
terraform state rm hcloud_server.worker1
terraform import hcloud_server.worker1 xxxxxx
terraform refresh
terraform apply
```

output:

```

Resource actions are indicated with the following symbols:
  + create
-/+ destroy and then create replacement

Terraform will perform the following actions:

  + ansible_host.worker1
      id:                 <computed>
      groups.#:           <computed>
      inventory_hostname: "${hcloud_server.worker1.ipv4_address}"

-/+ hcloud_server.worker1 (new resource required)
      id:                 "xxx" => <computed> (forces new resource)
      datacenter:         "fsn1-dc8" => <computed>
      image:              "" => "ubuntu-16.04" (forces new resource)
      ipv4_address:       "xx.xx.xx.xx" => <computed>
      ipv6_address:       "xx:xx:xx:xx::" => <computed>
      keep_disk:          "" => "false"
      location:           "fsn1" => "fsn1"
      name:               "worker1" => "worker1"
      server_type:        "cx31" => "cx31"
      ssh_keys.#:         "" => "3" (forces new resource)
      ssh_keys.0:         "" => "xx" (forces new resource)
      ssh_keys.1:         "" => "xx" (forces new resource)
      ssh_keys.2:         "" => "xx" (forces new resource)
      status:             "running" => <computed>


Plan: 2 to add, 0 to change, 1 to destroy.
```

**Comment by giovannicandido** [comment]
Work around:
Edit terraform state, add other information (copy from other servers):

ssh_keys
keep_disk
image

**Comment by thetechnick** [comment]
Hi @giovannicandido,
terraform cannot import server properties like the assigned ssh_keys.

In your terraform configuration you specify the server to have 3 ssh keys assigned, because terraform cannot know that these ssh keys are indeed assigned to the server, it will recreate the server to make sure that the configured ssh keys are configured on the server.

**Comment by giovannicandido** [comment]
Hi @thetechnick,
Thanks for explanation.
Force the server to be recreated, is not convenient or desirable. From a user point of view, import the server means I want to work with a existing resource.
Fortunately there is the work around I mentioned editing terraform state.
Would be a better solution to import the associated information, but I understand that in case of ssh keys this is not trivial.
I think at least a documentation on how to import a server as is should be provided.

Thanks.

**Comment by thetechnick** [comment]
I will try to improve the documentation in this case, but as far as I am aware it is not recommended to manually edit the terraform state.
