### ISSUE TITLE
Document possible values for `hcloud_server.location`

### ISSUE THREAD

**Issue by alvaroaleman** [hetznercloud/terraform-provider-hcloud#46]
Currently the docs only tell that the `location` property of `hcloud_server` is a string, it would be useful to know which possible locations there are

**Comment by flecno** [comment]
This locations are available for me. Terraforms location property accepts the name of the location

```
$ hcloud location list
ID   NAME   DESCRIPTION             COUNTRY   CITY
1    fsn1   Falkenstein DC Park 1   DE        Falkenstein
2    nbg1   Nuremberg DC Park 1     DE        Nuremberg
3    hel1   Helsinki DC Park 1      FI        Helsinki
```

**Comment by LKaemmerling** [comment]
I have added a list of locations to the docs. Will be online with the next release of the terraform provider.
