### ISSUE TITLE
[Bug]: Fails to unmarshal server price for specific type of server

### ISSUE THREAD

**Issue by phfroidmont** [hetznercloud/terraform-provider-hcloud#460]
### What happened?

When creating a `hcloud_server` of type `cpx11` it fails with the following error.
```
│ Error: json: cannot unmarshal number into Go struct field Price.server.server_type.prices.price_hourly.net of type string
│ 
│   with hcloud_server.test,
│   on instances.tf line 5, in resource "hcloud_server" "test":
│    5: resource "hcloud_server" "test" {
```
This happens specifically when `terraform apply`is ran for a new server or when `terraform plan` is ran for an existing server.
In the case of a new server, its created despite the error, making the Terraform state inconsistent.
The problem doesn't occur with all server types but it does for `cpx11`

I'm suspecting a change in the hcloud API since I was able to create a server of this type a few hours ago.

### What did you expect to happen?

The server should be created without error.

### Please provide a minimal working example

I was able to reproduce with the following example using version `1.31.0` of the provider.
```
resource "hcloud_server" "test" {
  name        = "test"
  image       = "debian-9"
  server_type = "cpx11"
}
```

**Comment by LKaemmerling** [comment]
Hey @phfroidmont ,

this will be fixed in a couple of minutes (from API side so nothing to do for you here).

**Comment by LKaemmerling** [comment]
This was fixed from API Side.

**Comment by phfroidmont** [comment]
I confirm it is fine now, thanks for the quick answer!
