### ISSUE TITLE
[Bug]: Firewall `apply_to` block runs into errors on deletion or repeated apply.

### ISSUE THREAD

**Issue by FriesPascal** [hetznercloud/terraform-provider-hcloud#461]
### What happened?

I just created a firewall and applied it to a group of servers using the new `apply_to` block. Going this route (instead of using the servers' `firewall_ids` argument) was necessary because the firewall has a rule that creates a dependency on the servers.

Unfortunately, when trying to tear down the construct via `terraform destroy`, i run into
```
╷
│ Error: firewall with ID 134550 is still in use (resource_in_use)
│ 
│ 
╵
```
presumably because the provider does not remove the `apply_to` rule first, before deleting the firewall. 

So, I tried commenting out the contents of the block and `terraform apply` to delete it first. That did not work either, since the previous application of the firewall actually creates a new entry in the servers' `firewall_ids` argument, which is in conflict with the empty argument in my `main.tf`. This results in Terraform trying to "double remove" the firewall from the resource.

I could get repeated applies working by adding a 
```
lifecycle {
    ignore_changes = [
      firewall_ids
    ]
  }
```
block to the servers. But commenting out the `apply_to` blocks now results in Terraform doing nothing. Apparently, you cannot remove `apply_to` blocks by commenting them out.

### What did you expect to happen?

When destroying a firewall, is should first be removed from all associated resources.

Terraform should ignore `firewall_ids` that stem from an `apply_to` block.

### Please provide a minimal working example

```
resource "hcloud_server" "this" {
  count       = 3
  name        = "example-server"
  image       = "ubuntu-20.04"
  server_type = "cx11"
  location    = "nbg1"
  
  ssh_keys    = ["my-key"]

  labels = {
    cluster = "my-cluster"
  }
}

resource "hcloud_firewall" "this" {
  name = "example-firewall"

  apply_to {
    label_selector = "cluster=my-cluster"
  }

  rule {
    direction   = "in"
    protocol    = "tcp"
    port        = "443"
    description = "Create dependency on my-server"
    source_ips  = [for i in hcloud_server.this : "${i.ipv4_address}/32"]
  }
}
```

**Comment by LKaemmerling** [comment]
Hey @FriesPascal,

thank you for the report. I was able to reproduce the issue. I submitted a fix for this. We will issue a bugfix release shortly.

**Comment by FriesPascal** [comment]
Hey @LKaemmerling,

thx a lot for the super fast fix. However, this only seems to solve the second part of the issue. Destroying a firewall which depends on servers (explicit or implicit) still results in an error because it needs to be removed from them first.
