### ISSUE TITLE
[Bug]: Deleting firewall fails if fw applied via labels

### ISSUE THREAD

**Issue by ambis** [hetznercloud/terraform-provider-hcloud#463]
### What happened?

Version: v1.31.1

1. Create server
2. Create firewall (with apply_to)
3. terraform apply
4. Wait for UI to show firewall rule to be Fully applied
5. remove firewall rule from HCL
6. terraform apply
7. FAILS with: Error: firewall with ID 135843 is still in use (resource_in_use)
8. Remove label target from firewall in GUI
9. retry terraform apply
10. Firewall is now deleted

### What did you expect to happen?

`terraform apply` to first remove the firewall from applying to servers, then deleting the firewall itself.

### Please provide a minimal working example

```
resource "hcloud_server" "server" {
  name = "server"
  image = "debian-11"
  server_type = "cx11"
  labels = {
    fw = ""
  }
}

resource "hcloud_firewall" "firewall" {
  name = "firewall"
  apply_to {
    label_selector = "fw"
  }
}
```

Apply this, wait for being `Fully Applied`, then remove FW and apply again, it will

```

hcloud_firewall.firewall: Destroying... [id=135843]
hcloud_firewall.firewall: Still destroying... [id=135843, 10s elapsed]
hcloud_firewall.firewall: Still destroying... [id=135843, 20s elapsed]
hcloud_firewall.firewall: Still destroying... [id=135843, 30s elapsed]
hcloud_firewall.firewall: Still destroying... [id=135843, 40s elapsed]
hcloud_firewall.firewall: Still destroying... [id=135843, 50s elapsed]
╷
│ Error: firewall with ID 135843 is still in use (resource_in_use)

```

Again, if I remove the label target in GUI from the firewall and the re-apply, then it will delete the firewall.

**Comment by LKaemmerling** [comment]
Hey @ambis,

thank you for your detailed report. I was able to reproduce and fix it. The MR for the fix is open and my colleagues will review it.
