### ISSUE TITLE
[Feature]: Allow creating servers without public IPs, with only private network interfaces

### ISSUE THREAD

**Issue by pasikarkkainen** [hetznercloud/terraform-provider-hcloud#466]
### What whould you like to see?

It'd be nice to be able to provision hcloud servers with only private network interfaces, meaning with no public IP interface at all.  This is needed in the cases where one has for example custom firewall/router/vpn-gateways in the project for other VMs to use.

Currently one can of course manually remove the assigned public IP from each VM or disable the interface in operating system settings, but it'd be nice to be able to create the server without the public IP interface in the first place.

I tried reading the hcloud API specification but i'm not totally sure if this is possible today using the current API..

**Comment by LKaemmerling** [comment]
Hey @pasikarkkainen,

this is currently not possible. I placed a +1 from you on the feature roadmap for this feature. As this is not directly a Terraform related request I will close it here.

**Comment by ThWoywod** [comment]
+1

**Comment by LKaemmerling** [comment]
Hey @ThWoywod,

this is already possible ;)

**Comment by ThWoywod** [comment]
@LKaemmerling ok thanks for the hint. I didn't find any documentation on this for now unfortunately.  Do you have a link where I can find more info?

**Comment by 4ND3R50N** [comment]
@ThWoywod 
https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/server

Checkout the primary ip section + public_net block :-)

PS:
Currently the update process for the public_net block is not working, there will be a new release which fixes this. Stay tuned at:
https://github.com/hetznercloud/terraform-provider-hcloud/issues/547
