### ISSUE TITLE
wait for boot-finished when using custom user_data cloud-init

### ISSUE THREAD

**Issue by schubter** [hetznercloud/terraform-provider-hcloud#47]
currently when creating a instance with user_data and this cloud-init data
```
#cloud-config
package_update: true
package_upgrade: true
```
it brings up the instance and reports ready event tho cloud-init is still doing its thing

if then some module also tries to do package things everything breaks as locks are still in place because cloud-init is still running, forcing me to add this to any package scripts
```bash
while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo 'waiting for boot-finished'; sleep 5; done;
```

could the provider not return that the instance is created until the file exists?

**Comment by thetechnick** [comment]
Hi @schubter,
cloud init already runs after the machine is booted.

If you want the terraform provider to wait until all of initializing is done you could either add a [`remote-exec` provisioner](https://www.terraform.io/docs/provisioners/remote-exec.html) with your while loop.

Or you could just do the initialization with the provisioner itself `remote-exec`, `ansible`, whatever you like and don't use cloud init. This way you can wait for your setup scripts to complete before doing anything else.

The provider itself will not support a blocking wait on cloud init scripts.
