### ISSUE TITLE
[Bug?]: Terraform moves to the next resource before hcloud_server's user_data is done

### ISSUE THREAD

**Issue by stefandanaita** [hetznercloud/terraform-provider-hcloud#472]
### What happened?

Hi everyone! This might not be a bug, even though as far as I'm aware the aws provider is behaving as I would expect the hcloud provider to behave.

I'm using the [rke-cluster](https://registry.terraform.io/providers/rancher/rke/latest/docs/resources/cluster) resource from the rke provider to spin up a cluster on Hetzner nodes.

One of the requirements of RKE is that docker is installed on the nodes prior to the `rke-cluster` resource is picked up by terraform. I've done this using `runcmd` in the user_data file that I'm giving to the `hcloud_server` resource.

This is the cloud config I'm using:
```
#cloud-config

packages:
  - software-properties-common
  - htop
package_update: true
package_upgrade: true
runcmd:
  - curl https://releases.rancher.com/install-docker/20.10.sh | sh
```

The problem is that `hcloud_server` thinks it's done before the cloud config script is finished, so when RKE tries to connect and use docker, it's not there. Waiting a minute and running `terraform apply` again makes it work.

### What did you expect to happen?

I would expect `hcloud_server` resource to only be done when the user_data stuff is finished. Is there a workaround that I'm not aware of? I'm trying to avoid doing `remote-exec`.

### Please provide a minimal working example

This can easily be proved by doing something that takes a while in the cloud config script (like installing docker) and then trying to fetch/use the output in the next terraform resource.

**Comment by LKaemmerling** [comment]
Hey @stefandanaita,

the API can not know when cloud init is done. We could do it by installing something like an agent and then send information back to the API, but this isn't something we want to do as we do not want to install meaningless software on customer servers. The only thing you could do is running `cloud-init status --wait > /dev/null` before you install the rke-cluster.

**Comment by stefandanaita** [comment]
Hi @LKaemmerling! Ok, no problem, thank you for the alternative suggested!
