### ISSUE TITLE
[Bug]: Teardown of empty subnet takes 5 minutes

### ISSUE THREAD

**Issue by backstreetkiwi** [hetznercloud/terraform-provider-hcloud#474]
### What happened?

I launched a bunch of servers in their own network and subnet. The launch went without problems and very fast!
However, the `terraform destroy` only went smooth and quick when I had 2 or 3 servers. With more servers, the destruction of the subnet (which was blocking the network from being destructed) took pretty much exactly 5 minutes (or a multitude of that). 
When I manually delete the network in the Hetzner Cloud UI, the destruction continues immediately.
All of this also happens when I do not interact with the machines at all but instead do `terraform destroy` right after `terraform apply`. 
I had a look at known problems and found #343 and #388 to be similar. But they are fixed, merged and released and my problem persists. I use the provider in version 1.31.1
I tested this with two different projects.
Thanks for your great work, I'd appreciate if you could look into this. If I can provide further information, I'd be happy to.

### What did you expect to happen?

I did expect the subnet to be destroyed as fast as the other resources.

### Please provide a minimal working example

```
terraform {
  required_version = ">= 0.15, < 2.0.0"
}

terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
      version = "1.31.1"
    }
  }
}

variable "hcloud_token" {
  description = "Token to be used with Hetzner cloud"
  type        = string
  sensitive   = true
}

provider "hcloud" {
  token = var.hcloud_token
}

resource "tls_private_key" "cluster_key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "hcloud_ssh_key" "master_keypair" {
  name       = "demo-master-key"
  public_key = tls_private_key.cluster_key.public_key_openssh
}

resource "hcloud_network" "network" {
  name     = "demo-network"
  ip_range = "10.0.0.0/16"
}

resource "hcloud_network_subnet" "subnet" {
  type         = "cloud"
  network_id   = hcloud_network.network.id
  network_zone = "eu-central"
  ip_range     = "10.0.1.0/24"
}

resource "hcloud_server" "node" {
  count       = 10 
  name        = "node-${count.index+1}"
  server_type = "cx11"
  image       = "centos-8"
  location    = "nbg1"
  ssh_keys    = [ hcloud_ssh_key.master_keypair.id ]

  network {
    network_id = hcloud_network.network.id
  }

  depends_on = [
    hcloud_network.network,
    hcloud_network_subnet.subnet
  ]
}

```

**Comment by fhofherr** [comment]
Hi @backstreetkiwi,

This was related to an issue in the implementation of our backend API. We deployed a fix to our backend API today which should greatly speed up removing empty subnets. I'm therefore closing this issue.

**Comment by backstreetkiwi** [comment]
Hello @fhofherr 
Confirmed! And thank you for the quick fix.
