### ISSUE TITLE
[Bug]: failed: Unknown Error

### ISSUE THREAD

**Issue by re-thc** [hetznercloud/terraform-provider-hcloud#483]
### What happened?

Failed with the following error:

`hcloud_server.sta_statestashs0_B80921B8: Creating...`
`hcloud_server.sta_statestashs0_B80921B8: Still creating... [10s elapsed]`
`╷`
`│ Error: hcclient/WaitForActions: action 321907966 failed: Unknown Error (unknown_error)`
`│`
`│   with hcloud_server.sta_statestashs0_B80921B8,`
`│   on cdk.tf.json line 178, in resource.hcloud_server.sta_statestashs0_B80921B8:`
`│  178:       }`

### What did you expect to happen?

Works

### Please provide a minimal working example

Provisioned server with user_data

**Comment by fhofherr** [comment]
Hi @re-thc,

please provide a minimal working example. Otherwise we are not able to analyze the issue.

**Comment by fhofherr** [comment]
Closing as the provided information is not enough to reproduce or analyze the issue.
