### ISSUE TITLE
[Bug]: Image should not be mandatory for server resource

### ISSUE THREAD

**Issue by vincentbernat** [hetznercloud/terraform-provider-hcloud#490]
### What happened?

When using Pulumi (which ultimately uses this Terraform provider), I am unable to import older servers because they have no image attached to them:

```
Missing required argument: The argument "image" is required, but no definition was found.. Examine values at 'Server.Image'.
```

In `internal/server/resource.go`, `image` is marked as `Required: true`.

### What did you expect to happen?

I should be able to import the server, even when no image is attached to it.

### Please provide a minimal working example

Here is a server without an image (I have shortened a bit the output to make it easier to read).

```
 18:22 ❱ curl -s \
        -H "Authorization: Bearer $HCLOUD_TOKEN" \
        'https://api.hetzner.cloud/v1/servers/1413514' | json
{
  "server": {
    "id": 1413514,
    "name": "web04.luffy.cx",
    "status": "running",
    "created": "2018-11-24T11:24:05+00:00",
    "public_net": {
      "ipv4": {
        "ip": "116.203.18.48",
        "blocked": false,
        "dns_ptr": "web04.luffy.cx"
      },
      "ipv6": {
        "ip": "2a01:4f8:1c0c:5eb5::/64",
        "blocked": false,
        "dns_ptr": [
          {
            "ip": "2a01:4f8:1c0c:5eb5::1",
            "dns_ptr": "web04.luffy.cx"
          }
        ]
      },
      "floating_ips": [],
      "firewalls": []
    },
    "private_net": [],
    "server_type": {
      "id": 1,
      "name": "cx11",
      "description": "CX11",
      "cores": 1,
      "memory": 2.0,
      "disk": 20,
      "deprecated": null,
      "storage_type": "local",
      "cpu_type": "shared"
    },
    "datacenter": {
      "id": 2,
      "name": "nbg1-dc3",
      "description": "Nuremberg 1 DC 3",
      "location": {
        "id": 2,
        "name": "nbg1",
        "description": "Nuremberg DC Park 1",
        "country": "DE",
        "city": "Nuremberg",
        "latitude": 49.452102,
        "longitude": 11.076665,
        "network_zone": "eu-central"
      },
    },
    "image": null,
    "iso": null,
    "rescue_enabled": false,
    "locked": false,
    "backup_window": null,
    "outgoing_traffic": 13273345000,
    "ingoing_traffic": 1377915000,
    "included_traffic": 21990232555520,
    "protection": {
      "delete": true,
      "rebuild": true
    },
    "labels": {},
    "volumes": [],
    "load_balancers": [],
    "primary_disk_size": 20,
    "placement_group": null
  }
}
```

**Comment by fhofherr** [comment]
Hi @vincentbernat,

thanks for your issue report. This issue happens in three cases:

1. Servers whose image was deleted before May 2021
2. Servers that get moved from one project to another project
3. Servers created from snapshot, if the snapshot was afterwards moved to a different project. Internally snapshots and images are treated similarly.

In those cases we deleted the image_id from the server. Especially in cases 2 and 3 we need to do this, as the snapshot now belongs to a different project. This leads to resources in the project of the server in questions not being allowed to see it.

I'm currently experimenting with marking the image_id as optional. So far it looks promising. However, there may be some corner cases in which this will lead to errors. One such case will be a change to the imported server that requires it to be destroyed and re-created. In this case the request for server creation will be denied by our API, as it is mandatory for the create server call.
