### ISSUE TITLE
[Bug]: Cannot start/provision servers on new USA location: Ashburn, VA 

### ISSUE THREAD

**Issue by saulmmendoza** [hetznercloud/terraform-provider-hcloud#493]
### What happened?

I tried to start/provision a server on the new USA location and it throws an error

- If I change the location to `hel1` it works perfectly
- I think we will need to add `ash` to an array or list of some kind
  - If you can point me to the correct file I will do the commit/PR 👍 
- Tried with `ash`, `ash1`, `ash-dc1` as locations

```
Terraform will perform the following actions:

  # hcloud_server.general will be created
  + resource "hcloud_server" "general" {
      + backup_window = (known after apply)
      + backups       = false
      + datacenter    = (known after apply)
      + id            = (known after apply)
      + image         = "ubuntu-20.04"
      + ipv4_address  = (known after apply)
      + ipv6_address  = (known after apply)
      + ipv6_network  = (known after apply)
      + keep_disk     = false
      + labels        = {
          + "type" = "general"
        }
      + location      = "ash"
      + name          = "server-general"
      + server_type   = "cx11"
      + ssh_keys      = [
          + "xxx",
        ]
      + status        = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
hcloud_server.general: Creating...
╷
│ Error: location 'ash' not found (invalid_input)
│ 
│   with hcloud_server.general,
│   on servers.tf line 1, in resource "hcloud_server" "general":
│    1: resource "hcloud_server" "general" {
│ 
```

### What did you expect to happen?

To provision a server on the new USA location

### Please provide a minimal working example

```tf
resource "hcloud_server" "general" {
  name        = "server-general"
  image       = "ubuntu-20.04"
  server_type = "cx11"
  location    = "ash"
  ssh_keys    = [data.hcloud_ssh_key.default.id]
  labels = {
    type = "general"
  }
}
```

**Comment by LKaemmerling** [comment]
Hey @saulmmendoza,

interesting error, i will look deeper into it. My first assumption: the cx11 types are not available in Ashburn. Only CPX (and CCX Generation 2) types are available there.

**Comment by saulmmendoza** [comment]
@LKaemmerling you're goddamn right, I feel so newbie but I was excited to try the new location XD

Im closing this because its not an issue at all

![](https://static.wikia.nocookie.net/ff4cf0f2-cad6-4865-9dd4-337e3f5613b4)
