### ISSUE TITLE
[Bug]: hcloud_locations data source is missing important properties

### ISSUE THREAD

**Issue by staticvoid255** [hetznercloud/terraform-provider-hcloud#507]
### What happened?

When I use the hcloud_locations data source the "network_zone" property seems to be missing from the result.  The official Hetzner API does however let you do see network zones for corresponding locations.
![image](https://user-images.githubusercontent.com/59235486/154863506-113d37e4-aae0-4dfd-a8a8-85c0fe9b48c8.png)

There are also other missing (but useful) properties) [see here](https://docs.hetzner.cloud/#locations-get-all-locations)
![image](https://user-images.githubusercontent.com/59235486/154859928-971e1804-f03c-4a20-849a-966f4234bb5f.png)

I checked [location/datasource.go](https://github.com/hetznercloud/terraform-provider-hcloud/blob/21267191315c2fec3f7f36ae6af5acba36faa709/internal/location/data_source.go) and it's correct that these values aren't included in the schema

### What did you expect to happen?

I'd expect the response from the hcloud_locations data source to contain all the same properties for locations as the Cloud API. This would allow me to do additional validation between locations and network zones and also provide useful info for logging and monitoring like country, city as well as really cool geomapping of my resources in Grafana.

### Please provide a minimal working example

The output should be an array of objects containing all the same properties as provided by the API, something like:

```terraform
data "hcloud_locations" "data" {
}

If outputted should look something like 
    [ 
      {
        city: "Falkenstein"
        country: "DE"
        description: "Falkenstein DC Park 1"
        id: 1
        latitude: 50.47612,
        longitude: 12.370071
        name: "fsn1"
        network_zone: "eu-central"
      },
      {
        city: "Ashburn"
        country: "US"
        description: "Ashburn DC Park 1"
        id: 4
        latitude: 39.017836
        longitude: -77.465563
        name: "ash"
        network_zone: "us-east"
      }
   ]
```

**Comment by LKaemmerling** [comment]
Hey @staticvoid255,

except of `network_zone` all fields are available under the `locations` list. Network Zone will be available with the next release (I will prepare a MR).
