### ISSUE TITLE
[Feature]: Allow automatic unmounting of iso images on reboot

### ISSUE THREAD

**Issue by phaer** [hetznercloud/terraform-provider-hcloud#514]
### What whould you like to see?

Hello,

Thanks for this provider! I am using the `iso` attribute of `hcloud_server` to boot new servers with a NixOS iso provided by hetzner, which is useful to install NixOS to the servers harddisk.

The issue is that this setting seems to survive reboots; the server boots the iso image not only on first boot but on its second boot as well. This is in contrast to `rescue` which applies to the first boot only.

My suggestion would be to either change the behavior of `iso`, or - to avoid a breaking change - introduce a new attribute, named e.g., `detach_iso` to enable users to specify an ISO image for first boot only.

**Comment by phaer** [comment]
If I read the source correctly, the way `rescue` works is that it's activated in this provider, but deactivation seems to happen implicitly on the other side of the API - so this terraform provider might be the wrong place for this feature request?

**Comment by apricote** [comment]
The terraform way-of-life does not really work well with this, your terraform configuration describes the "desired state of the world". So it can either be attached or detached. This would only be possible if all the setup happens within the provider code.

One-boot Rescue Mode is implemented in the [API](https://docs.hetzner.cloud/#server-actions-enable-rescue-mode-for-a-server):

> Rescue Mode is automatically disabled when you first boot into it or if you do not use it for 60 minutes.
