### ISSUE TITLE
[Bug]: networkId and firewallId type issues

### ISSUE THREAD

**Issue by aress31** [hetznercloud/terraform-provider-hcloud#518]
### What happened?

The `networkId` and `firewallId` should both be `int` as per the documentation, however when creating a new instance of these two `classes`, the second positional parameter must be a `string` this introduce a bug with the types and the `ts linter` does not like that.

### What did you expect to happen?

Either to define these ids as an `integer` or `string` and be consistent with the typing.

### Please provide a minimal working example

```typescript
    const networkId: number = Math.random();
    const network = new hcloud.Network(this, networkId, {
      name: "x",
      ipRange: "10.0.0.0/16",
    });

    const subnetId = uuidv4();
    const subnet = new hcloud.NetworkSubnet(this, subnetId, {
      networkId: networkId,
      type: "cloud",
      networkZone: "eu-central",
      ipRange: "10.0.1.0/24",
    });
```

See the screenshots:

![image](https://user-images.githubusercontent.com/11601622/162595714-177d5247-8608-4985-8f9c-00285077b087.png)

The underlined error is:

```typescript
const networkId: number
Argument of type 'number' is not assignable to parameter of type 'string'.ts(2345)
```

Note that if I change the `id` to a string; then I am getting this:

![image](https://user-images.githubusercontent.com/11601622/162595741-be8c79f0-be76-40ce-ac60-f79e44db0bab.png)

And the error now becomes:

```typescript
(property) NetworkSubnetConfig.networkId: number
Docs at Terraform Registry: [NetworkSubnet#network_id]()

Type 'string' is not assignable to type 'number'.ts(2322
```

Seems like a catch 22 to me...

**Comment by apricote** [comment]
Hi @aress31,

this repository is for the `terraform-provider-hcloud` project. You seem to be using [`pulumi-hcloud`](https://github.com/pulumi/pulumi-hcloud), please try to open your issue on that repository instead.
