### ISSUE TITLE
Feature request: allow creation of a server instance from a snapshot (hcloud_server)

### ISSUE THREAD

**Issue by maja-hh** [hetznercloud/terraform-provider-hcloud#526]
As far as I can see from the current documentation there seems to be not way to create a server instance from a previously created snapshot. Would be great if this could be implemented (maybe as an attribute to the hcloud_server resource.

Thanks!

**Comment by LKaemmerling** [comment]
Hey @maja-hh,

this is possible by using the image ID on server creation as `image`: https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/server#image

**Comment by maja-hh** [comment]
Thanks! Maybe it would make sense to update the documentation and describe this solution. @LKaemmerling

**Comment by maja-hh** [comment]
@LKaemmerling I tried your suggested solution but failed, because terraform tells me that the image can't be found. I have an existing snapshot with a description of "my-snap-2022-04-08". How can I get the  "name"  or "id" attribute of this snapshot via the web-interface (or via terraform)? I was not able to find any information about this. When I try to use "my-snap-2022-04-08" or "hcloud_snapshot.my-snap-2022-04-08" as the "image" terraform can not find it.

**Comment by keremispirli** [comment]
I have the same problem. How can we find out the image id of our existing snapshot?
