### ISSUE TITLE
[Docs]: document how to specify empty labels

### ISSUE THREAD

**Issue by cortex3** [hetznercloud/terraform-provider-hcloud#528]
Hi,
the hetzner api allows empty values to be set for labels:  https://docs.hetzner.cloud/#labels
How can this be achieved via terraform?
I've tried
```           
"kubernetes_first_master"    =  ""
"kubernetes_first_master"    = null
"kubernetes_first_master"    = true
```

but none of this produce a label with no value.

**Comment by ambis** [comment]
I ran into this myself. 

When I add a "value only" label from the GUI and run terraform plan (with v1.33.2) I get

```
      ~ labels                     = {
          - "test"              = "" -> null
```

which means that the GUI still generates labels with empty values. But the provider no longer allows this.

**Comment by rwojsznis** [comment]
> But the provider no longer allows this

Upgraded provider today, indeed seems some sort of breaking change happened as terraform started to complain about

`label value '' (key: MyLabel) is not correctly formatted`

I gave up and changed `labels = { "MyLabel" : "" }` to `labels = { "MyLabel" : "MyLabel" }` on `hcloud_server`. I have load balancer/firewall rules that had `MyLabel` set to `label_selector` - but it seems it did not break anything - label rules are still properly applied without any changes, just FYI - maybe you will find it useful!

edit: seems the breaking change happened in `1.33.2` - `1.33.1` seemed to allow blank strings for labels; [probably related change](https://github.com/hetznercloud/terraform-provider-hcloud/compare/v1.33.1...v1.33.2#diff-7378c7d462221547688e0d724658c2450b4489a0b02abcd83ad57b30ffa530c4R136-R141)

**Comment by msltwtf** [comment]
I ran into this issue today as well and I think I found the source of the problem within the hcloud-go library.
The keys and values of labels are validated here and it seems that the regex for the values is just missing the options for an empty string.

I already filed an [issue](https://github.com/hetznercloud/hcloud-go/issues/206) in the corresponding hcloud-go project.
I hope this helps. 😃

**Comment by 4ND3R50N** [comment]
@msltwtf Thank you for pointing that out!

I will update the hcloud go + tf provider soon!
