### ISSUE TITLE
[Feature]: Allow creation of API tokens via terraform

### ISSUE THREAD

**Issue by Boeller666** [hetznercloud/terraform-provider-hcloud#529]
### What would you like to see?

When creating infrastructure using terraform it's ok to create an initial "terraform API token".
But it would also be nice to have more API tokens for different use cases, eg. a special API token when adding the hetznercloud csi driver to a kubernetes cluster.

Example of a resource:
```hcl
resource "hcloud_api_token" "csi" {
    description = "csi-driver"
    rights      = "read-write" # can be read or read-write 
}
```

Output:
+ token

**Comment by ambis** [comment]
I'm curious, wouldn't the TF-created token need to be stored in the Terraform state? Since the token cannot be re-read from the API, it must be stored in the terraform state? Otherwise you wouldn't be able to use the value in any of the following terraform runs.
