### ISSUE TITLE
[Bug]: Get stuck while creating resource

### ISSUE THREAD

**Issue by nico01f** [hetznercloud/terraform-provider-hcloud#531]
### What happened?

terraform apply:

```
module.app.module.hcloud_server.server["app-fsn1-04"]: Creating...

Error: error during placement (resource_unavailable)

  on main.tf line 14, in resource "hcloud_server" "server":
  14: resource "hcloud_server" "server" {

```

### What did you expect to happen?

Create resources in hetzner.

### Please provide a minimal working example

```
resource "hcloud_server" "server" {
  for_each = local.server_set

  image       = var.image
  server_type = var.server_type
  location    = var.dc
  ssh_keys    = var.ssh_key_ids
}
```

**Comment by nico01f** [comment]
I had to create a ticket on hetzner to know what happened. And there's an issue on FSN dc which not appears in status page.

**Comment by yajo** [comment]
I'm having this problem. What was the fix?

**Comment by 4ND3R50N** [comment]
This is oftenly only a temporary problem which happens on datacenter related issues.

A quick fix (for debugging) would be to use a different datacenter for deployment. Otherwhise, check out the status page or report such issues so we can help you out :-)

**Comment by moreinhardt** [comment]
Just had the same issue. It seems like they indeed don't have the selected server type available at that datacenter at the moment. I checked via the browser UI.

**Comment by gsaslis** [comment]
I'm hitting this today. 

Trying 3 different locations / datacenters and I'm still getting 

`Error: error during placement (resource_unavailable, f5ea34ce6e4f3f68)`

**Comment by jooola** [comment]
@gsaslis We are experiencing a resource shortage, see https://status.hetzner.com/incident/aa5ce33b-faa5-4fd0-9782-fde43cd270cf

**Comment by gsaslis** [comment]
thanks @jooola ! 

that's very helpful to know - I was very close to dropping Hetzner from this particular use case because of this reason. Good to know about the outage.
