### ISSUE TITLE
[Bug]: It is not clear how to get the necessary information to import an existing ssh key into the Terraform state

### ISSUE THREAD

**Issue by exarkun** [hetznercloud/terraform-provider-hcloud#533]
### What happened?

I tried to import an SSH key already configured on my account.  First I tried importing by name:

```
terraform import hcloud_ssh_key.mykey myname@myhost
```

but this failed.  Then I looked at the API documentation: https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/ssh_key

This says keys can be imported by "id" and then gives this example:

> terraform import hcloud_ssh_key.mykey 

There is no id in the example so I tried importing with no id:

```
terraform import hcloud_ssh_key.mykey
```

but terraform itself refused this form.

Then I found the source for the documentation: https://github.com/hetznercloud/terraform-provider-hcloud/blob/1dbb289398f19ca52b6b772501630381fc601fa0/website/docs/r/ssh_key.html.md

and saw that the actual example is:

```
terraform import hcloud_ssh_key.mykey <id>
```

and it is just mis-rendered in the published documentation.

Then I looked at the Hetzner console (https://console.hetzner.cloud/projects/.../security/sshkeys) to try to find the id of the key I want to import.  However, the key id is nowhere to be seen.

### What did you expect to happen?

I expected to be able to import an existing ssh key using some piece of easily-available information - such as the key comment or fingerprint.

### Please provide a minimal working example

```
terraform {
  required_version = "~> 0.13.6"

  required_providers {
    hcloud = {
      source = "nixpkgs/hcloud"
      version = "= 1.33.1"
    }
}

resource "hcloud_ssh_key" "mykey" {
  name = "myname@myhost"
  public_key = "ssh-... ... myname@myhost"
}
```

**Comment by KosrenDQ** [comment]
You can extract the id from brower using the inspect feature and looking at the http requests.
![grafik](https://user-images.githubusercontent.com/6208682/180403312-55e6d78e-d223-42c8-99ea-ff5d3b99d835.png)

Then you can use the id with the terraform import comomand like this
`terraform import hcloud_ssh_key.MyKey 133742`

**Comment by sebandgo** [comment]
There are many missing IDs from the web console, this is what I'm facing as well.
The only workaround is to obtain that from their API (as per the documentationhttps://docs.hetzner.cloud/#ssh-keys):

```
curl \
	-H "Authorization: Bearer $API_TOKEN" \
	'https://api.hetzner.cloud/v1/ssh_keys'
```

Using the above you'll be able to get the SSH Key ID.

**Comment by apricote** [comment]
You can usually use the [`hcloud` CLI](https://github.com/hetznercloud/cli) to find out these IDs:

```shell
$ hcloud ssh-key list
ID         NAME            FINGERPRINT                                       AGE
8748679    julian.toelle   99:70:10:19:47:e9:73:e6:de:c9:63:59:9d:00:04:fa   338d
15263879   csi-dev         b3:e5:51:8d:a2:16:a5:cf:97:56:94:de:33:58:0a:fd   27d 
```
