### ISSUE TITLE
[Feature]: Documentation for primary IPs

### ISSUE THREAD

**Issue by troethe** [hetznercloud/terraform-provider-hcloud#539]
### What whould you like to see?

The last release seems to have added support for primary IPs, but I couldn't seem to find any documentation for it.
Could you add it or tell me where I can find it?

**Comment by 4ND3R50N** [comment]
Hey @troethe ,

sorry for that, here u can find the documentation :-)

https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/primary_ip
https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/data-sources/primary_ip
https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/data-sources/primary_ips

lg,
Lars
