### ISSUE TITLE
[Feature]: create server without primary ip

### ISSUE THREAD

**Issue by askarsabyrov** [hetznercloud/terraform-provider-hcloud#541]
### What whould you like to see?

Now in version 1.31.4 primary ip is created with a server implicitly. There are no opportunities to create server without primary ip. It would be great if creation of primary ip would be explicitly defined with argument in `hcloud_server` resource, `primary_ip_create` with bool value for instance.

**Comment by 4ND3R50N** [comment]
Hey! 

Thank you for your report, i will take care of this!

LG
Lars

**Comment by svenstaro** [comment]
Ideally, it would allow us to choose to create a server with `both`, `ipv4`, `ipv6`, `none`. Currently the way to create it is a bit annoying so it'd be great if it could be done more neatly.

**Comment by 4ND3R50N** [comment]
This requested feature can be used with the `public_net` block in server. please checkout the docs for that!

If you encounter any buggy behavior, please report this as a new issue :-)

**Comment by moelllerniklas** [comment]
My  resource block looks like:

```terraform
resource "hcloud_server" "node" {
        name = "${var.hcloud_project}-node-1.${var.domain_name}"
        server_type = "cx21"
        image = "ubuntu-20.04"
        datacenter = var.hcloud_datacenter
        ssh_keys = [hcloud_ssh_key.default.id]

        network {
                network_id = hcloud_network.cluster.id
        }

        public_net {
                ipv4_enabled = false
                ipv6_enabled = false
        }

        depends_on = [
                hcloud_ssh_key.default,
                hcloud_network.cluster
        ]
}
```

Imo the expected behaviour should be that if terraform requests to create the `hcloud_server` neither a public ipv4 nor a public ipv6 should be assigned. 

The creation results in a created server resource which has both public ipv4 and ipv6 enabled:

![image](https://user-images.githubusercontent.com/89383596/177308283-243da195-2757-4a83-9727-ff00a189b501.png)

@4ND3R50N is this expected?

**Comment by 4ND3R50N** [comment]
Hey!

```
resource "hcloud_server" "server_test" {
  name        = "test-server"
  image       = "ubuntu-20.04"
  server_type = "cx11"
  datacenter  = "hel1-dc2"
  labels = {
    "test" : "tessst1"
  }

  network {
      network_id = hcloud_network.privNet.id
  }
  public_net {
    ipv4_enabled = false
    ipv6_enabled = false
  }
}

resource "hcloud_network" "privNet" {
  name     = "my-net"
  ip_range = "10.0.0.0/8"
}

resource "hcloud_network_subnet" "foonet" {
  network_id   = hcloud_network.privNet.id
  type         = "cloud"
  network_zone = "eu-central"
  ip_range     = "10.0.1.0/24"
}
```
![image](https://user-images.githubusercontent.com/22675741/177311403-f6652b96-6824-4081-a8ef-5ad043a0c41a.png)

With this example its working fine! Can you show me your network resources?

EDIT:
I think youre not using the newest version 1.34.3 (there was a second PR which fixed a small issue you might currently encounter)

**Comment by niklaspm** [comment]
My hcloud terraform provider version is:
```bash
Using previously-installed hetznercloud/hcloud v1.34.2
```

My network resources look like:
```terraform
resource "hcloud_network" "cluster" {
        name = "${var.hcloud_project}-network"
        ip_range = "${var.hcloud_network_cidr}"
}

resource "hcloud_network_subnet" "default" {
        network_id = hcloud_network.cluster.id
        type = "cloud"
        network_zone = "${var.hcloud_network_zone}"
        ip_range = "${var.hcloud_network_cidr}"

        depends_on = [
                hcloud_network.cluster
        ]
}                               
```

Variables are set to:
`hcloud_network_cidr` is set to `10.0.0.0/16`
`hcloud_network_zone` is set to `eu-central`

**Comment by moelllerniklas** [comment]
Thanks @4ND3R50N my terraform provider still remains on version `1.34.2`. After updating the provider everything applies as expected.

**Comment by LKaemmerling** [comment]
@niklaspm did you specify the correct version in your module configuration? The release was just pushed 15 minutes ago: https://registry.terraform.io/providers/hetznercloud/hcloud/1.34.3

**Comment by 4ND3R50N** [comment]
@niklaspm Absolutely no problem, the release of 1.34.3 just some minutes ago, try again :-)

**Comment by moelllerniklas** [comment]
@LKaemmerling terraform wasn't aware of version 1.34.3 back then but now after updating everything applies as expceted. Thanks.

**Comment by colinwilson** [comment]
Everything working as expected once I upgraded to 1.34.3. 👍 . Thanks @4ND3R50N & @LKaemmerling
