### ISSUE TITLE
[Bug]: docs for public_net

### ISSUE THREAD

**Issue by yajo** [hetznercloud/terraform-provider-hcloud#542]
### What happened?

I was creating servers and I wanted to know how to disable the ipv4 public address that is created automatically.

Accidentally I found out a mention over `public_net`, but that argument is not properly documented where it should be.

I guess [the official docs](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/server#argument-reference) come from: https://github.com/hetznercloud/terraform-provider-hcloud/blob/1937ee9da59e6ffa6248c684e53e746056c5e704/website/docs/r/server.html.md?plain=1#L93-L123

The only mention found doesn't explain how to disable the default ipv4 address creation. It just tells you how to enable it (weird, as it is the default behaviour): https://github.com/hetznercloud/terraform-provider-hcloud/blob/1937ee9da59e6ffa6248c684e53e746056c5e704/website/docs/r/server.html.md?plain=1#L17-L52

### What did you expect to happen?

This use case should be supported and documented.

### Please provide a minimal working example

N/A

**Comment by yajo** [comment]
I just found [the api docs, which seem to suggest you can use `enable_ipv4 = false`](https://docs.hetzner.cloud/#servers-create-a-server). However, the terraform plugin fails with that:

```hcl
resource "hcloud_server" "my-node" {
  public_net {
    enable_ipv4 = false
  }
  # ... stuff ...
}
```

Error:

```
> terraform -chdir=terraform apply
Acquiring state lock. This may take a few moments...
╷
│ Error: Unsupported argument
│ 
│   on k3s.tf line 76, in resource "hcloud_server" "my-node":
│   76:     enable_ipv4 = false
│ 
│ An argument named "enable_ipv4" is not expected here.
╵
```

**Comment by 4ND3R50N** [comment]
Hey :-) the doc is now more specific (see server docs).

In short: u can use the following attributes for `public_net`:
```
public_net {
  ipv4_enabled = true | false
  ipv6_enabled = true | false
  ipv4  = <TF resource>
  ipv6 = <TF resource>
}
```
Keep in mind: when disabling both IPvX, your server needs to be attached to a network!

If you have any further questions, just tell me :-)
