### ISSUE TITLE
[Feature]: Implement 'location' argument for hcloud_primary_ip

### ISSUE THREAD

**Issue by peterpramb** [hetznercloud/terraform-provider-hcloud#545]
### What whould you like to see?

`hcloud_primary_ip` currently only supports the `datacenter` argument, in contrast to other resource types which allows for either `datacenter` or `location`:
* `hcloud_floating_ip`
* `hcloud_load_balancer`
* `hcloud_server`
* `hcloud_volume`

Please add support for the `location` argument as well for more flexibility and consistency.

**Comment by 4ND3R50N** [comment]
Hey @peterpramb ,

sadly, you can only create primary IPs per datacenter, so this wont be possible (for now).
