### ISSUE TITLE
[Bug]: Changes in public_net does nothing

### ISSUE THREAD

**Issue by msltwtf** [hetznercloud/terraform-provider-hcloud#547]
### What happened?

Hi there, I am not really sure if this is the right spot for this issue or if this is a problem with the [hcloud-go library](https://github.com/hetznercloud/hcloud-go/)...

---

I created a server with a public and a private network connection. Then I removed the public network connection in the terraform code and applied it.
After terraform reported `Apply complete!` I took a look in the web ui and saw that nothing changed. The server still had a public IPv4 and IPv6 address.
The activity overview only shows two actions for this terraform apply run. `server.stop` and `server.start` nothing indicates that a removal of the IPv4 and IPv6 addresses took place.

Furthermore it seems that the server is forcibly powered off instead of shutting it down via ACPI which seems a little harsh and unsave.

### What did you expect to happen?

- Graceful (acpi) shutdown of the server in question.
- Removal of the public IPs
- Boot of the server.

### Please provide a minimal working example

Apply the following

```hcl
terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
    }
  }
}

provider "hcloud" {}
resource "hcloud_network" "primary" {
  name     = "primary_network"
  ip_range = "10.0.0.0/8"
}

resource "hcloud_network_subnet" "primary" {
  network_id   = hcloud_network.primary.id
  type         = "cloud"
  network_zone = "eu-central"
  ip_range     = "10.0.1.0/24"
}
resource "hcloud_server" "test" {
  name        = "test"
  server_type = "cx11"
  image       = "debian-11"
  location    = "nbg1"
  public_net {
    ipv4_enabled = true
    ipv6_enabled = true
  }
  network {
    network_id = hcloud_network.primary.id
    ip         = "10.0.1.20"
  }
}
```

Then change `ipv4_enabled` and `ipv6_enabled` to `false` and apply again.

---

I tested this with:
- terraform: 1.2.3
- hetznercloud/hcloud: v.1.34.3

**Comment by 4ND3R50N** [comment]
Hey @msltwtf 

Just want to inform u, that we are currently working on this! Stay tuned
