### ISSUE TITLE
ssh connection through the bastion host doesn't work?

### ISSUE THREAD

**Issue by medicol69** [hetznercloud/terraform-provider-hcloud#550]
### What happened?

I'm using the newest terraform-provider-hcloud version **v1.35.0**, and terraform version **v1.0.7**

I'm trying to create a rancher cluster using only the private ip's because I don't need them and the workers shouldn't be accessed from the internet. So I created a bastion host (with a public ip ofc) but it can't connect to the private interfaces of the worker nodes through ssh??

 I always get this error when using Terraform:

```
│ Error: remote-exec provisioner error
│
│   with module.cluster_init.hcloud_server.rancher_management_nodes[1],
│   on module-cluster-init/resources_hetzner.tf line 74, in resource "hcloud_server" "rancher_management_nodes":
│   74:   provisioner "remote-exec" {
│
│ timeout - last error: ssh: rejected: connect failed (Connection refused)
```
But it all works if I use public ips??

tnx,
Tom

### What did you expect to happen?

I expect that the connection through the bastion host would be able to ssh into the private instances (their private interfaces) of the worker nodes. Like its shown in this example https://www.terraform.io/language/resources/provisioners/connection

### Please provide a minimal working example

```
provisioner "remote-exec" {
    inline = ["cloud-init status --wait > /dev/null"]
    connection {
      type        = "ssh"
      host        = var.servers[count.index]
      user        = "root"
      private_key = file(var.hcloud_ssh_key_path)

      bastion_user        = "root"
      bastion_private_key = file(var.hcloud_ssh_key_path)
      bastion_host = hcloud_server.bastion_host.ipv4_address
    }
  }
```

**Comment by 4ND3R50N** [comment]
Hey @medicol69 

one question: 
**are/is your bastion host & your worker nodes all in the same network?** 
Because servers that have no public ips (primary ips) **has to be in a network** to be turned on & running, because theire just living / communicating in the hetzner cloud network. So, you could add your bastion server to the same network (ofc with public ip so you can reach it) to only use internal IPs ([checkout the network block](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/server#server-creation-with-network)) for server -> server communication.


If you still have problems or questions (or maybe i just misunderstood you), just leave a message here (Maybe provide also the server / network configuration)

Have a nice evening :-)

**Comment by medicol69** [comment]
@4ND3R50N they are in the same network, but just ssh-ing from the bastion host doesn't work against the private interfaces of the worker nodes with terraform....and even when I ssh into the bastion host I can't even netcat the 22 port on the private interfaces (if happens every other time with the error "Server starting has failed")....

My guess is that the instances created without the primary ip's behave very buggy....

**Comment by 4ND3R50N** [comment]
@medicol69 Sounds strange.

So let me summerize:

You have at least 2 Servers, both in a network. One is accessible from the outside, the other is completly private. 
And its not possible to SSH the private server from the bastion (the server which is accessible from the outside)? (Bastion -> ssh -> private server)

**Comment by medicol69** [comment]
Yap, but that happens only when I disable the primary ip (public ips) on the working nodes....if I let them have the public ips then everything works https://i.gifer.com/jVp.gif

**Comment by 4ND3R50N** [comment]
@medicol69 

Can u show me based on your TF configuration the IP youre using to connect to the worker node? Are you sure youre using the private IP (located in `hcloud_server.network.ip`) of this worker node?

**Comment by medicol69** [comment]
I'm using the 172.16.1.0/24 range for the private ips....

Just try to create say 3 hosts, one with a public address and the other two without the public ip, and see if you can ssh from the bastion host to the ones without the public ip.....

**Comment by hameno** [comment]
I'm having the same problem, new server without public ip does not start SSH, there seem to be no host keys generated. Looking at cloud-init it also looks like cloud-init is not working at all - is this expected?

**Comment by LKaemmerling** [comment]
@medicol69 @hameno which OS do you use?  I just tested it with ubuntu22.04 & ubuntu 20.04 and everything works. Even Cloud init runs as expected.

**Comment by medicol69** [comment]
@LKaemmerling I'm using ubuntu 20, can you please share your example so that I can see that maybe I'm not doing something wrong?

**Comment by hameno** [comment]
Using 22.04. It's happening randomly, but very often. I create multiple instances without public ips connected to a private network and more than half of the instances start without running cloud init (hostname not even applied). Ot really looks like the network is not attached while cloud init ist running

**Comment by tmikulin** [comment]
guys, any progress on this stuff?

**Comment by selfscrum** [comment]
I have a similar issue. In my case I created 3 servers (from a snapshot, with a for_each statement in terraform, so all of those should be identical), and tried to connect via a bastion with ProxyJump. Randomly, some servers were accesible but most often not. after an ACPI shutdown and restart via the cloud console, the servers are accessible now, but I feel not confident to push that script in an automation pipeline.
Here's the creation excerpt:
```

locals {
  system = jsondecode(file("./assets/system.json"))
  ips = [ " 10.0.0.20", "10.0.0.21", "10.0.0.22"]
}

resource "hcloud_server" "nc_cluster" {
  count       = 3
  name        = format("%s-%d",local.system["server_name"], "${count.index}")
  server_type = local.system["server_type"]
  location    = local.system["server_location"]
  image       = local.system["snapshot"]
  ssh_keys    = [ local.system["key_name"] ]
  
  public_net {
    ipv4_enabled = false
    ipv6_enabled = false
  }

  network {
    network_id = hcloud_network.private_network.id
    ip         = local.ips["${count.index}"]
  }

  user_data   = templatefile (
                      "${path.module}/assets/user-data.mm",
                        {
                        admin_user          = "root"
                        ssh_key = file( format( "./assets/%s.pub", local.system["key_name"] ) )
                        }
                      )
  depends_on = [
    hcloud_network_subnet.network-subnet
  ]
}

```

nb: it might not be related to the terraform provider but the HCLOUD API or some underlying provisioning mechanisms. At one server that I couldn't access, I created a rescue root password and logged on with it. I found that the hostname was still set to the name of the temporary server name of the packer server instance. This changed after the reboot. Other irregular behaviour while testing is that the first IP in the array is never used. Mostly the server ends up with 10.0.0.3, once it even got 10.0.0.1. Sometimes the servers didn't start but stayed off and had to be switched on in the console.

**Comment by 4ND3R50N** [comment]
Hey!

I implemented a temporary workaround for this issue so the network interface is booting up correctly after creating a full private server.

At least for me, the following TF template is working 100% of all test runs after the second try of the SSH connect:

```
terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
    }
  }
}

# Configure the Hetzner Cloud Provider
provider "hcloud" {
  token = "<your token>"
}

resource "hcloud_network" "mynet" {
  name     = "my-net"
  ip_range = "10.0.0.0/16"
}
resource "hcloud_network_subnet" "foonet" {
  network_id   = hcloud_network.mynet.id
  type         = "cloud"
  network_zone = "eu-central"
  ip_range     = "10.0.0.0/24"
}

resource "hcloud_server" "bastion" {
  name        = "nwtest"
  image       = "ubuntu-22.04"
  server_type = "cx11"
  datacenter    = "fsn1-dc14"
  ssh_keys    = ["<your ssh key>"]
  network {
    network_id = hcloud_network.mynet.id
    ip         = "10.0.0.2"
  }
}


resource "hcloud_server" "client" {
  name        = "nwtest-2"
  image       = "ubuntu-22.04"
  server_type = "cx11"
  datacenter    = "fsn1-dc14"
  ssh_keys    = ["<your ssh key>"]
  network {
    network_id = hcloud_network.mynet.id
    ip         = "10.0.0.3"
  }
  public_net {
    ipv4_enabled = false
    ipv6_enabled = false
  }

  depends_on = [
    hcloud_network_subnet.foonet
  ]
  
  connection {
    type         = "ssh"
    user         = "root"
    host         = one(self.network[*].ip)
    bastion_host = hcloud_server.bastion.ipv4_address
    private_key  = file("~/.ssh/id_ed25519")
  }

  provisioner "remote-exec" {
    inline = [
      "echo \"Hello World\" >> /root/test.txt",
    ]
  }

}

```

It may take a little bit longer since you have to wait for the second SSH connect, but in the end you can implement your solutions without being blocked completely.

If you still encounter any issues related to this, please post in this issue.

PS: the release of the new TF version happens in the next days.

Have a nice evening :-)
