### ISSUE TITLE
[Feature]: Ability to spin up instances without using Public IPs

### ISSUE THREAD

**Issue by sebandgo** [hetznercloud/terraform-provider-hcloud#555]
### What whould you like to see?

Ability to spin up instances without using Public IPv4 / IPv6 IPs.

Example (that doesn't work):

```
#
# MySQL Server(s)
#

resource "hcloud_server" "atb-htz-use-dev-mysql-01" {

    name        = "atb-htz-use-dev-mysql-01"
    image       = "debian-11"
    server_type = "cpx11"
    location    = "ash"
    keep_disk   = true

    public_net {

        ipv4_enabled    = false
        ipv6_enabled    = false

    }

}

#
# Internal Network
#

resource "hcloud_server_network" "atb-htz-use-dev-mysql-01" {

    server_id  = hcloud_server.atb-htz-use-dev-mysql-01.id
    network_id = hcloud_network.atb-htz-use-development-net.id
    ip         = "10.17.33.1"

}

```

Using the above code TF will fail as it can't spin up an instance without a public IP attached.

```
hcloud_server.atb-htz-use-dev-mysql-01: Creating...
╷
│ Error: missing networks or StartAfterCreate == false when EnableIPv4 and EnableIPv6 is false
│
│   with hcloud_server.atb-htz-use-dev-mysql-01,
│   on htz-server-mysql.tf line 5, in resource "hcloud_server" "atb-htz-use-dev-mysql-01":
│    5: resource "hcloud_server" "atb-htz-use-dev-mysql-01" {
```

**Comment by sebandgo** [comment]
Currently the only way of achieving this is by using the `network` feature:

```
#
# MySQL Server(s)
#

resource "hcloud_server" "atb-htz-use-dev-mysql-01" {

    name        = "atb-htz-use-dev-mysql-01"
    image       = "debian-11"
    server_type = "cpx11"
    location    = "ash"
    keep_disk   = true

    public_net {

        ipv4_enabled    = false
        ipv6_enabled    = false

    }

    network {

        network_id  = hcloud_network.atb-htz-use-development-net.id
        ip          = "10.17.33.1"

    }

}
```

**Comment by romanex** [comment]
Hello, @SebastianGogoasa example doesn't work fo me.

`Error: Unsupported argument
│
│   on modules\hcloud\servers.tf line 8, in resource "hcloud_server" "cp_server":
│    8:     ipv4_enabled = false
│
│ An argument named "ipv4_enabled" is not expected here.`

**Comment by romanex** [comment]
Upgrading hcloud proveder helps me!

**Comment by sebandgo** [comment]
I forgot to mention indeed, I'm using this:
```
terraform {

    required_providers {

        hcloud = {

            source = "hetznercloud/hcloud"

        }

    }

    required_version = ">= 1.2"

}
```

**Comment by LKaemmerling** [comment]
Hey @SebastianGogoasa,

creating Servers without any network interface is not supported (and would also make the server completely useless). Therefore we don't support it. (Exception: You can create *stopped* servers with this state, but then can't start this server).

**Comment by wondertalik** [comment]
> Currently the only way of achieving this is by using the `network` feature:
> 
> ```
> #
> # MySQL Server(s)
> #
> 
> resource "hcloud_server" "atb-htz-use-dev-mysql-01" {
> 
>     name        = "atb-htz-use-dev-mysql-01"
>     image       = "debian-11"
>     server_type = "cpx11"
>     location    = "ash"
>     keep_disk   = true
> 
>     public_net {
> 
>         ipv4_enabled    = false
>         ipv6_enabled    = false
> 
>     }
> 
>     network {
> 
>         network_id  = hcloud_network.atb-htz-use-development-net.id
>         ip          = "10.17.33.1"
> 
>     }
> 
> }
> ```

```
 public_net {
    ipv4_enabled = false
    ipv6_enabled = false
  }

  network {
    network_id = hcloud_network.private-network.id
  }

  connection {
    host        = self.ip # how to get ip??
    port        = var.ssh_port
    type        = "ssh"
    private_key = file(var.ssh_private_key_nodes)
    user        = var.user_name
  }
```

Hello, in this case how to get network ip?

**Comment by apricote** [comment]
Hey @wondertalik,

you can get the IP using a [`for expression`](https://developer.hashicorp.com/terraform/language/expressions/for) on `self.network`:

```hcl
  connection {
    host = [for network in self.network : network.ip][0]
  }
```

Depending on your needs, you should also filter for the correct network, in case you attach to multiple.

Please note that connecting to the private IP is only possible from inside the private network. So you either need to execute terraform on an existing server attached to the private network, or you need to use a [jump/bastion host](https://developer.hashicorp.com/terraform/language/resources/provisioners/connection#connecting-through-a-bastion-host-with-ssh) that is connected to the public internet and the private network.
