### ISSUE TITLE
[Feature]: add primary private_ipv4_address datasource for hcloud_server

### ISSUE THREAD

**Issue by marcoatenway** [hetznercloud/terraform-provider-hcloud#557]
### What whould you like to see?

**This is a copy of the closed ticket: #551 the ticket is not resolved. the mentioned object [...].network.ip does not exist**

the assigned private ip address should be exported as a datasource the same as the public IP address:

${hcloud_server.fancy-vm0.private_ipv4_address}

This is necessary to build highly dynamic infrastructure where you dont define any addresses because they are registered i.e. in DNS by terraform

**Comment by LKaemmerling** [comment]
Hey @marcoatenway,

there is no need to create a new issue. 

Duplicate of #551 551
