### ISSUE TITLE
Allow automount for volume and volume_attachment

### ISSUE THREAD

**Issue by apricote** [hetznercloud/terraform-provider-hcloud#57]
It would be great if you could add the `automount` argument to the `hcloud_volume` and `hcloud_volume_attachment` resources.

Depends On: hetznercloud/hcloud-go#105

**Comment by LKaemmerling** [comment]
This is already planned for the next release :)

**Comment by apricote** [comment]
Already wasted an hour yesterday writing a provisioning script to format and mount volumes. Can't wait for the next release :)
