### ISSUE TITLE
[Bug]: forced hcloud_server replacement

### ISSUE THREAD

**Issue by alekna** [hetznercloud/terraform-provider-hcloud#571]
### What happened?

Terraform v1.2.8 wants to re-create `hcloud_server` after `server_type` is changed manually and server is re-imported.

### What did you expect to happen?

I expected no forced replacement

### Please provide a minimal working example

1. deploy `cx11` `hcloud_server` using terraform:
```
resource "hcloud_server" "gamma" {
  name = "gamma"
  image = "debian-10"
  server_type = "cx11"
  keep_disk = true
  location = var.location
  ssh_keys = [
    hcloud_ssh_key.lauris.id
  ]
  firewall_ids = [
    hcloud_firewall.gamma.id
  ]
}
```
2. stop server and manually upgrade it to `cx21` using Hetzner Cloud Web Console
3. update hcloud_server's `server_type` to `cx21`
4. remove `hcloud_server` state using terraform:
```
$ terraform state rm hcloud_server.gamma
Removed hcloud_server.gamma
Successfully removed 1 resource instance(s).
```
5. re-import `hcloud_server` after manual upgrade to `cx21`:
```
$ terraform import hcloud_server.gamma <ID>
hcloud_server.gamma: Importing from ID "<ID>"...
hcloud_server.gamma: Import prepared!
  Prepared hcloud_server for import
hcloud_server.gamma: Refreshing state... [id=<ID>]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
6. run `terraform plan`. The expected result is no changes to the `hcloud_server`. The actual result is following:
```
  # hcloud_server.gamma must be replaced
-/+ resource "hcloud_server" "gamma" {
      + allow_deprecated_images    = false
      + backup_window              = (known after apply)
      ~ datacenter                 = "nbg1-dc3" -> (known after apply)
      ~ id                         = "<ID>" -> (known after apply)
      + ignore_remote_firewall_ids = false
      ~ ipv4_address               = "<IP>" -> (known after apply)
      ~ ipv6_address               = "<nil>1" -> (known after apply)
      ~ ipv6_network               = "<nil>" -> (known after apply)
      + keep_disk                  = true
      - labels                     = {} -> null
        name                       = "gamma"
      + ssh_keys                   = [
          + "3070965",
        ] # forces replacement
      ~ status                     = "running" -> (known after apply)
        # (7 unchanged attributes hidden)

      - timeouts {}
    }
```

**Comment by 4ND3R50N** [comment]
Hey @alekna ,

Thank you for reporting this. Unfortunatly there is no quick way to fix this issue. But its possible to prevent this forced replacement with the lifecycle management:

```
resource "hcloud_server" "gamma" {
  name = "gamma"
  image = "debian-10"
  server_type = "cx21"
  keep_disk = true
  ssh_keys = [
    data.hcloud_ssh_key.ssh_key_2.id,data.hcloud_ssh_key.ssh_key_3.id
  ]
  lifecycle {
    ignore_changes = [
      ssh_keys,
    ]
  }
}
```
This will still show you an update after `terraform plan` since some metadata is simply not provided by backend. But there wont be any changes / replacements of the necessary resource values.

I´ll keep you up to date!

**Comment by apricote** [comment]
I am going to close this issue, as @4ND3R50N explained the issue and provided a workaround.

If you still have issues with this, please feel free to reopen the issue or create a new one.
