### ISSUE TITLE
[Bug]: terraform execution is different from plan

### ISSUE THREAD

**Issue by talex-de** [hetznercloud/terraform-provider-hcloud#574]
### What happened?

I did a `terraform plan` to add a new server to my existing setup. The plans output was as expected such that a new machine will be created. After I run terraform to apply the changes all other existing machines have been deleted and recreated, although these delete actions were not listed in the output from terraform plan.

All resources in my HCloud project are part of the Terraform state. I increased the number of my worker nodes from 3 to 4. The plans output was that a new machine will be created and the firewall rules will be updated.

HCloud TF Provider v1.34.3

### What did you expect to happen?

I would expect that Terraform only applies the planned changes and nothing else.

### Please provide a minimal working example

```
resource "hcloud_placement_group" "worker-nodes" {
  name = "worker-placement-group"
  type = "spread"

  labels = {
    "target-nodes" = "worker",
    workspace      = terraform.workspace,
    builder        = var.builder_tag,
    scope          = var.cluster_name,
  }
}

resource "hcloud_server" "worker-node" {
  count = var.worker_count
  name = "worker${count.index + 1}"
  placement_group_id = hcloud_placement_group.worker-nodes.id
  location = var.datacenter
  image = var.os_image
  server_type = var.worker_server_type
  user_data = file("./${var.user_data_dir}/${terraform.workspace }/cloud-config.worker.yaml")
  ssh_keys = hcloud_ssh_key.wheels[*].id

  depends_on = [
    hcloud_network.k8s-cluster-network,
    hcloud_network_subnet.k8s-worker-nodes-subnet,
    hcloud_ssh_key.wheels,
  ]

  labels = {
    "node-role" = "worker",
    workspace   = terraform.workspace,
    builder     = var.builder_tag,
    scope       = var.cluster_name,
  }
}

resource "hcloud_server_network" "worker-node" {
  count = var.worker_count
  server_id = hcloud_server.worker-node[count.index].id
  subnet_id = hcloud_network_subnet.k8s-worker-nodes-subnet.id
  ip = "${var.subnet_worker_ip}.${count.index + var.subnet_all_offset}"
}

resource "hcloud_rdns" "worker-node" {
  count = var.worker_count
  server_id = hcloud_server.worker-node[count.index].id
  ip_address = hcloud_server.worker-node[count.index].ipv4_address
  dns_ptr = "${hcloud_server.worker-node[count.index].name}.${var.domain}"
}
```

**Comment by apricote** [comment]
Hi @talex-de

I am unable to reproduce your issue. Could you either add precise steps you follow to reproduce the issue, or send me your debug logs so I can check what happened here?

You can generate the debug logs by running `TF_LOG=DEBUG TF_LOG_PATH=execution-different-from-plan.log terraform apply ...`. You can then either upload the logs here, or send me an email to `julian.toelle <at> hetzner-cloud.de`

**Comment by apricote** [comment]
Closing this issue to keep the tracker clean. You may still respond here if you still experience the issue :)
