### ISSUE TITLE
[Feature]: hcloud_load_balancer_target import

### ISSUE THREAD

**Issue by b8dmin** [hetznercloud/terraform-provider-hcloud#578]
### What whould you like to see?

I would like to have the possibility of import in this resource.
So that other users do not have to somehow contrive.

**Comment by b8dmin** [comment]
This problem now is not actually for me,  but maybe someone help.
I have already manually added targets to terraform.state, but recommends - don't it..it's bad idea😃

**Comment by apricote** [comment]
Hello @cital,

I spent some time thinking about this today. The issue is that loadbalancer targets do not have an `id` which we could use to import them, but only the `type` and corresponding identifier/filter to identify them.

I came up with the following pattern to import the resources, before I implement this, it would be great if you (or anyone else) could give me some feedback:

> ## Import
> 
> Load Balancer Target entries can be imported using a compound ID with the following format:
> `<load-balancer-id>__<type>=<identifier>`
> 
> Where _identifier_ depends on the _type_:
> 
> - `server`: server id
> - `label_selector`: label selector
> - `ip`: ip address
> 
> ```
> terraform import hcloud_load_balancer_target.myloadbalancerservertarget 123__server=321
> terraform import hcloud_load_balancer_target.myloadbalancerlabeltarget 123__label_selector=env=prod
> terraform import hcloud_load_balancer_target.myloadbalanceriptarget 123__ip=203.0.113.123
> ```

**Comment by b8dmin** [comment]
@apricote 
Yes, this method also seems the most correct to me and I cannot think of any good alternative.

Well, unless it is possible to implement something like:
```shell
terraform import hcloud_load_balancer_target.myloadbalancerservertarget 123__321
terraform import hcloud_load_balancer_target.myloadbalancerlabeltarget 123__env=prod
terraform import hcloud_load_balancer_target.myloadbalanceriptarget 123__203.0.113.123
```

....and interpret
integer - server_id
KV - label_selector
ip - ip


Шn this way, you can reduce the number of letters in the import command... but is it worth it?)
