### ISSUE TITLE
unable to provision server node from snapshot[Bug]: 

### ISSUE THREAD

**Issue by lachnerd** [hetznercloud/terraform-provider-hcloud#581]
### What happened?

i'd like to provision a server from a previously packer built snapshot

### What did you expect to happen?

if i use "iso" with the snapshot name a server gets built

### Please provide a minimal working example

resource "hcloud_server" "node" {
  name = var.name
  image = var.image
  iso = var.iso (e.g. ubuntu-20.04-1667390890)
  #user data only on first disk
  user_data = length(var.disks) == 1 ? local.cloud_init : null
  #user_data = length(var.disks) == 1 local.cloud_init
  server_type = var.server_type
  location = var.location
  backups = var.backups
  ssh_keys = [hcloud_ssh_key.default.id]
  keep_disk   = var.keep_disk
  placement_group_id = var.placement_group_id
  delete_protection = var.delete_protection
  public_net {
    ipv4_enabled = true    
    ipv6_enabled = true
  }
}

Server Image cannot be found .

**Comment by apricote** [comment]
Hi @lachnerd,

if you create a snapshot of a server (manually or through packer), this is saved as an "image" in the Hetzner Cloud API. To create a new server from this, you need to specify it in the `image` attribute instead of `iso`.

If you modify your example like this, it should work:

```diff
 resource "hcloud_server" "node" {
   name = var.name
-  image = var.image
+  image = var.snapshot_id
-  iso = var.iso # (e.g. ubuntu-20.04-1667390890)
   #user data only on first disk
   user_data = length(var.disks) == 1 ? local.cloud_init : null
   #user_data = length(var.disks) == 1 local.cloud_init
   server_type = var.server_type
   location = var.location
   backups = var.backups
   ssh_keys = [hcloud_ssh_key.default.id]
   keep_disk = var.keep_disk
   placement_group_id = var.placement_group_id
   delete_protection = var.delete_protection
   public_net {
     ipv4_enabled = true
     ipv6_enabled = true
   }
 }
```

Please note that you have to pass the snapshot id here, you can use a `data` resource to find the right snapshot by label:

```terraform
data hcloud_image packer_snapshot {
  with_selector = "app=foobar"
  most_recent = true
}

resource "hcloud_server" "node" {
  [...]
  image = data.hcloud_image.packer_snapshot.id
  [...]
}
```

I will try to improve the docs around this in the coming days

**Comment by lachnerd** [comment]
thx a lot, that worked
