### ISSUE TITLE
Can't remove server with protected volume

### ISSUE THREAD

**Issue by Somebi** [hetznercloud/terraform-provider-hcloud#60]
It should remove server and leave volume alive.
Server can be removed via hetzner cloud console web ui and after that, volume as expected is left with undetached status.

**Comment by Somebi** [comment]
It exits before removing the server, should just notify and proceed further.

**Comment by Somebi** [comment]
Anyone alive?

**Comment by Somebi** [comment]
Aha, ok. Now i got it. To persist volumes, you shoud not include it into the state. Just create volume attachment and hardcode volume id of already created volume into it. Attachment wont' remove the volume itself, but only detach it.

**Comment by LKaemmerling** [comment]
Sorry i did not look into this on the holiday days. 

You can create the volume with the `hcloud_volume` resource (and specify a location instead of a server) and use the `hcloud_volume_attachment` resource to attach the volume to the server.

**Comment by Somebi** [comment]
I was just using hardcoded volume id and volume itself was protected by me via web console UI.
But now i'm using attachment with hardcoded volume id instead, without hcloud_volume and it's working fine.

**Comment by LKaemmerling** [comment]
Instead of hardcoding the volume id you could use the `hcloud_volume` datasource:
https://www.terraform.io/docs/providers/hcloud/d/volume.html

**Comment by Somebi** [comment]
It's not persistent. On destroy, it will be deleted, but hardcoding volume id into attachment it doesn't remove the volume, because it is not in the state of terraform.

Terraform just don't remove what it does not create, only what it has created.

**Comment by LKaemmerling** [comment]
I know, the datasource is for this usecase :) A resource that isn‘t controlled By Terraform is a datasource :)

**Comment by Somebi** [comment]
Oh yeah, sorry didn't knew that. Haven't much time to properly read all docs. Terraform looks promising as a tool. Sometimes it stuck, but it's way better to manage servers.
