### ISSUE TITLE
[Feature]: Data source for server SSH fingerprints

### ISSUE THREAD

**Issue by rzlourenco** [hetznercloud/terraform-provider-hcloud#607]
### What whould you like to see?

I would like the `hcloud_server` data source to also report on server SSH fingerprints. This way, Terraform can generate an SSH configuration file that can be imported by the user's SSH configuration. This way, short names and appropriate authentication can be easily automated.

**Comment by apricote** [comment]
I do not think that this is easily possible. For starters, not every server has ssh access enabled. The Hetzner Cloud API does not know about the SSH fingerprint, so we would need to wait until the server is ready (and booted, and ssh available) to then connect to it to get the ssh fingerprint.

If you want to do something like this, i would suggest using [`null_resource`](https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource#example-usage) to get the fingerprint from the server using ssh locally and writing that to a file. Or possible using an [`external`](https://registry.terraform.io/providers/hashicorp/external/latest/docs/data-sources/data_source) data source that invokes a script and returns the ssh fingerprints back to terraform. The cleanest solution would be a new provider does retrieves this data and returns it in a terraform-native way.

**Comment by apricote** [comment]
Closing as it is out of scope for this provider.
