### ISSUE TITLE
[Feature]: List of datacenter values in terraform docs

### ISSUE THREAD

**Issue by MiguelGuedelha** [hetznercloud/terraform-provider-hcloud#608]
### What whould you like to see?

Currently the primary IP resource requires a "datacenter" value, unlike other resources that allow the "location" parameter instead.

It's already been discussed in issue [545](https://github.com/hetznercloud/terraform-provider-hcloud/issues/545) that adding the location is not possible.

Is there a list of what the valid datacenter values are available anywhere? The docs themselves don't seem to include it, unlike the location parameter which has the possible location in the docs for the server resource.

Thanks :)

**Comment by apricote** [comment]
Hi @MiguelGuedelha,

you can always get a canonical and up-to-date list of these values (location, datacenter, server-type, load-balancer-type) from our API. The easiest way to do that locally would be through our [`hcloud` cli](https://github.com/hetznercloud/cli):

```
$ hcloud datacenter list
ID   NAME        DESCRIPTION          LOCATION
2    nbg1-dc3    Nuremberg 1 DC 3     nbg1
3    hel1-dc2    Helsinki 1 DC 2      hel1
4    fsn1-dc14   Falkenstein 1 DC14   fsn1
5    ash-dc1     Ashburn DC1          ash
6    hil-dc1     Hillsboro DC 1       hil
```

Where would you expect such listings in the terraform docs? Multiple resources are using them, and copy&pasting the list to every resource that uses it makes the docs quite large, and the committed lists can get outdated.

As the `hcloud_server` resource contains a list of locations, I have created a PR that also adds the list of `datacenters` to that page: #613

**Comment by pat-s** [comment]
At least providing a link to a central resource would help - I also just stumbled over this. In the end, users always end up in the GH repo and open an issue. Having a link in the TF docs would help...
