### ISSUE TITLE
[Bug]: image id updated after apply from snapshot

### ISSUE THREAD

**Issue by anbraten** [hetznercloud/terraform-provider-hcloud#609]
### What happened?

It seems that the api is returning the image name / id used for creating. In our case `ubuntu-20.04`. But after a manual apply from a snapshot of the server machine, the image is now an id `89149223`. To use the id I tried to use 

```tf
data "hcloud_image" "node_image" {
  name = "ubuntu-20.04"
}
```

But that is returning `15512617` as id. I've also tried to re-import the server without success.

Any ideas how we could get the correct id or old name?

### What did you expect to happen?

The id / name used to initially create an instance should be kept.

### Please provide a minimal working example

```tf
data "hcloud_image" "node_image" {
  name = "ubuntu-20.04"
}

resource "hcloud_server" "node" {
  count        = var.node_count
  name         = "kube-node-${count.index + 1}"
  server_type  = var.node_type
  image        = data.hcloud_image.node_image.id
  location     = var.hetzner_location
  keep_disk    = true
  ssh_keys     = [data.hcloud_ssh_key.hetzner_ssh_key.id]
  firewall_ids = [hcloud_firewall.kube_wall_node.id]
}
```

**Comment by apricote** [comment]
A snapshot is (internally) just another image, so if you rebuild the server from the snapshot, the snapshot ID is reported as the `image`. The public API does not keep track of the image that the server used that the snapshot was created from.

If you just want to ignore this change to avoid recreating the server from the (old) image, you can use [`lifecycle.ignore_changes`](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes):

```terraform
data "hcloud_image" "node_image" {
  name = "ubuntu-20.04"
}

resource "hcloud_server" "node" {
  count        = var.node_count
  name         = "kube-node-${count.index + 1}"
  server_type  = var.node_type
  image        = data.hcloud_image.node_image.id
  location     = var.hetzner_location
  keep_disk    = true
  ssh_keys     = [data.hcloud_ssh_key.hetzner_ssh_key.id]
  firewall_ids = [hcloud_firewall.kube_wall_node.id]

  
  lifecycle {
    ignore_changes = [
      # Server was recreated from snapshot
      image,
    ]
  }
}
```

I hope this answered your question. Please feel free to ask any further questions here, or in a new issue.
