### ISSUE TITLE
Rebuild instead of destroy

### ISSUE THREAD

**Issue by frafra** [hetznercloud/terraform-provider-hcloud#61]
Instead of destroying and creating a new resource, rebuild could be used:
https://docs.hetzner.cloud/#server-actions-rebuild-a-server-from-an-image

This would avoid losing the IP every time.

**Comment by LKaemmerling** [comment]
The most common use case would be to delete the server if the resource will be destroyed. 
If you need a static/persistent IP I would recommend you to use a Floating IP.

**Comment by frafra** [comment]
@LKaemmerling If the resource is tainted or some changes require to rebuild the server, it looks to me that using the `rebuild` API function makes more sense than to destroy the resource and create it again, but that is just a personal opinion.

Simulating a rebuild by destroying and recreating the server would mean to lose the IP or paying a couple of euro per server (1 for floating IPv4 and 1 for IPv6 if using floating IP, that offers much more than just reserving an IP).
It seems to me that there would be additional costs, because you pay each resource by the hour, so if you destroy and create you could pay up to an additional hour per resource.

**Comment by LKaemmerling** [comment]
The problem that I see is, that people expect the server to be deleted instead of rebuilt and if we rebuild it, how can we destroy the server?

**Comment by frafra** [comment]
Got it. What about an option like `prefer_rebuild = false` for the resource to take advantage of the `rebuild` action?

**Comment by LKaemmerling** [comment]
Would be an idea, but is still didn't like the fact to "destroy the terraform resource but only rebuild the server" and as far as I know it is not possible from terraform side, because when terraform destroys the server it assume it is really destroyed.

**Comment by frafra** [comment]
Ok, I understand your position. Probably I should just accept the additional costs related to floating IP to have them fixed, while waiting for Hetzner Cloud support in go-discover, so it is easier to configure Nomad/Consul clusters: https://github.com/hashicorp/go-discover/issues/73

**Comment by tholu** [comment]
Why do you need a static/persistent IP? If you use consul + fabio reverse proxy + cloudflare, you can work around that requirement pretty good.

**Comment by frafra** [comment]
@tholu In order to use Consul you need to have at least one IP (from go-discover or a static IP) or a DNS entry; there is no go-discover support for Hetzner, static IP is costly, so you could use h a DNS server (or Cloudflare) to start Consul and take advantage of it (using Fabio reverse proxy etc.), but it still looks like a workaround to me (and you have to rely on external/additional services).

**Comment by tholu** [comment]
@frafra I have solved this by deploying a consul cluster via terraform on hcloud, with cloudflare pointing to the consul cluster and updating the DNS-RR entry automatically also via terraform when upgrading the consul cluster. Sure, it's a workaround - but it works quite fine so far.

**Comment by frafra** [comment]
@tholu thanks for sharing your solution :-) I think I will adopt a similar approach for the moment.

**Comment by invidian** [comment]
Also destroying + creating costs more, as Hetzner charges for full hour when you create new server, so that would be another use case for rebuilding.

**Comment by LKaemmerling** [comment]
I guess this can be closed. 

We won't add a flag/feature to rebuild instead of destroy a server when you run terraform destroy.

**Comment by therevoman** [comment]
so.  what about during a "taint" and "apply" action?  That would be a perfect fit for "openstack server rebuild".
