### ISSUE TITLE
[Bug]: hcloud_locations names deprecated warning

### ISSUE THREAD

**Issue by lainiwa** [hetznercloud/terraform-provider-hcloud#610]
### What happened?

Using the latest version (1.36.2).

Warning pops up about data.hcloud_locations.ds.names being deprecated.
> The attribute "names" is deprecated. Refer to the provider documentation for details.

But the docs (https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/data-sources/locations) doesn't mention names being deprecated.
I didn't succeed finding anything related in the changelog either.

### What did you expect to happen?

I expected the docs to have info on how to fix this warning.

### Please provide a minimal working example

The very example from the docs:

```
data "hcloud_locations" "ds" {
}

resource "hcloud_server" "workers" {
  count = 3

  name        = "node1"
  image       = "debian-9"
  server_type = "cx31"
  location    = element(data.hcloud_locations.ds.names, count.index)
}
```

**Comment by apricote** [comment]
It looks like terraform does not surface the deprecation message we set in the code: https://github.com/hetznercloud/terraform-provider-hcloud/blob/119f38c4358d101d60121535865a0eefd14856fd/internal/location/data_source.go#L83

I updated the docs to also include this message, and updated the example to use the new syntax: #614
