### ISSUE TITLE
[Bug]: Creating VM with only IPv6 fails with rescue linux and ssh provisioner

### ISSUE THREAD

**Issue by blackkaven** [hetznercloud/terraform-provider-hcloud#611]
### What happened?

I tried to install a flatcar on a VM provisioned with terraform and only an IPv6 interface. This fails with a timeout as terraform does not get the correct IP returned.

So terraform tries to connect to 
```
hcloud_server.flatcar-0 (remote-exec): Connecting to remote host via SSH...
hcloud_server.flatcar-0 (remote-exec):   Host: [2a01:4f8:c012:7cbc::1]
```

But the host actually has a different IP:
![image](https://user-images.githubusercontent.com/1243180/213877984-7a74109f-e273-410c-b4e4-ca2cd86e164a.png)

### What did you expect to happen?

The VM should have been created and terraform should be able to connect to the machine via ssh using the correct IP on the rescue OS.

### Please provide a minimal working example

```
terraform {
  required_version = ">= 0.13"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "1.36.2"
    }
  }
}


provider "hcloud" {
  token = <YOUR TOKEN HERE>
}

resource "hcloud_server" "flatcar-0" {
  name        = "flatcar-0"
  rescue      = "linux64"
  image       = "debian-11"
  server_type = "cpx11"
  location    = "fsn1"
  ssh_keys    = ["YOUR SSH KEY HERE"]
  public_net {
    ipv4_enabled = false
    ipv6_enabled = true
  }
  connection {
    user        = "root"
    private_key = file("YOUR PRIVATE SSH KEY HERE")
    host        = self.ipv6_address
    timeout     = "1m"
  }
  provisioner "remote-exec" {
    inline = [
      "echo -n 'hi'",
    ]
  }
}
```

**Comment by apricote** [comment]
Thanks for reporting this @blackkaven! I have talked to the responsible team and they plan on fixing this, though I can not provide a timeline for this.

At the moment you can replace `self.ipv6_address` with [`cidrhost(self.ipv6_network, 2)`](https://developer.hashicorp.com/terraform/language/functions/cidrhost) to get the IP address for the rescue system.

**Comment by apricote** [comment]
We just released a new version of the rescue system that also listens on `::1`, so you can now use the `self.ipv6_address` here :+1:
