### ISSUE TITLE
[Feature/Question]: Better decision/documentation for primary IPs

### ISSUE THREAD

**Issue by morremeyer** [hetznercloud/terraform-provider-hcloud#612]
### What whould you like to see?

The `hcloud_primary_ip` resources features a `datacenter` argument, which is useful to create the primary IP in the same DC than the server it will be attached to (I assume this makes the routing path shorter and is therefore to be preferred).

However, when not caring about which DC a server is running in, one has to guess which DC a server will be created in for creation. This is due to the `datacenter` being an attribute for the server, but the `hcloud_primary_ip` being needed for the creation, too.

As a IPv4 or IPv6 primary IP needs to exist on creation, this leads to a dependency loop.

There might be a better solution to this, but I did not find any documentation for it.

There might be some mechanism that automatically puts the server in the same DC as the primary IP, but I could not find any documentation about it.

I'm not aware of how to improve this, but right now it feels clunky and a bit wrong, so I'm raising this issue to get a discussion started about better ideas.

**Comment by apricote** [comment]
Hi @morremeyer,

this is indeed not very well documented.

Primary IPs are directly linked to `datacenters` and can only be assigned to a server in the same `datacenter`. If you want to use the `hcloud_primary_ip` resource, you need to specify the desired `datacenter`. Once you do that, you can use the same datacenter name/id when creating the server.

At the moment there is one `datacenter` per location, so you can hardcode the selection.

**Comment by morremeyer** [comment]
@apricote Really late, but thanks for the input! As long as there's only one possible value, I don't think there's anything else needed.
