### ISSUE TITLE
[Bug]: resource "hcloud_server" with public_net IPs enabled return wrong attribute values

### ISSUE THREAD

**Issue by shehi** [hetznercloud/terraform-provider-hcloud#616]
### What happened?

Imagine this in `main.tf`:
```
resource "hcloud_server" "server" {
  # ...
  public_net {
    ipv4_enabled = true
    ipv6_enabled = true
  }
}
```

with this `output.tf`:
```
output "ipv4_address" {
  value = hcloud_server.server.ipv4_address
}

output "ipv6_address" {
  value = hcloud_server.server.ipv6_address
}
```

After running `terraform apply`, output attributes for assigned IP addresses isn't populated. They are `<nil>`. Only after 2nd consequetive `terraform apply` these values get fetched and populated into the output.

### What did you expect to happen?

Assigned IPs properly populated after `terraform apply`.

### Please provide a minimal working example

Too lazy to do, sorry.

**Comment by shehi** [comment]
**ADDITIONALLY**, only for IPv6 addresses:

If value is `<nil>`, it types the following erroneous output as the value: `<nil>1`. I presume someone forgot `1` somewhere in the code?

**Comment by apricote** [comment]
Hi @shehi,

I am unable to reproduce your issue. What version of the terraform provider are you using? Please try the latest version (`v1.36.2`) if you are not using that. If it still fails with the latest version for you, could you send debug logs (`TF_LOG=DEBUG TF_LOG_PATH=tf-616.log terraform apply`) to my email `julian.toelle <at> hetzner-cloud.de`?

I used this configuration to test it:

```terraform
resource "hcloud_server" "server" {
  name        = "tf-616"
  server_type = "cx11"
  location    = "hel1"
  image       = "ubuntu-22.04"

  public_net {
    ipv4_enabled = true
    ipv6_enabled = true
  }
}

output "ipv4_address" {
  value = hcloud_server.server.ipv4_address
}

output "ipv6_address" {
  value = hcloud_server.server.ipv6_address
}
```

**Comment by shehi** [comment]
I couldn't reproduce it as well - I believe there was a weird glitch somewhere. I am using Gitlab as a Terraform State host, and running Terraform both locally and through GitLab CI, both sharing the same `http` backend state. Somehow I managed to have this weird case, where I had to run `terraform apply` twice to get updates. But later, I noticed in my CI workflow, that, having `terraform plan -> apply` twice in consequential GitLab CI stages caused this (i.e. `plan -> apply -> plan -> apply`). Second time invoking _plan -> apply_ sequence, TF complained about some external changes to the system. So I guess the wrapper GitLab is using (`gitlab-terraform`) is causing this abnormality. I removed this 2nd _plan -> apply_ flow from my CI setup for the moment, and things are working flawlessly.

I will close this for the moment, and reopen it if this case shows up again. Thanks a lot!

**Comment by shehi** [comment]
Ah yes, I remember it now :) GitLab, once `plan -> apply` is executed, creates an artifact for state, which needs to be stored, before one should run the same sequence again. This is what I was doing, and since the second time around TF detected discrepancy with the state, it complained.

I will be implementing multi-project triggered pipelines in GitLab to circumvent this. Or find some other solution to store the state-artifacts in the backend before running TF again.

REGARDLESS THO, I still find that `<nil>1` case very weird :D Checked your Go codebase searching for possible causes myself, but since my Go knowledge is quite limited, I failed.
