### ISSUE TITLE
[Bug]: Documentation misleading for hcloud_server

### ISSUE THREAD

**Issue by ofrzeta** [hetznercloud/terraform-provider-hcloud#618]
### What happened?

When using a name for the hcloud_server resource that includes an underscore you get an error message because it doesn't conform to RFC 1123. That is right but the documentation https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/server includes an example that has the name "server_test". 

### What did you expect to happen?

I want to see the docs showing a proper example :)

### Please provide a minimal working example

```
resource "hcloud_server" "server-test" {
  name        = "test-server"
  image       = "ubuntu-20.04"
  server_type = "cx11"
  datacenter  = "fsn1-dc14"
  labels = {
    "test" : "tessst1"
```

**Comment by apricote** [comment]
Hey @ofrzeta,

I am unable to reproduce your issue. In terraform, resources are usually named using underscores (`_`), but this does not have anything to do with our API, and should not cause any issues.

I tested this example from the linked docs page:

```terraform
### Server creation with one linked primary ip (ipv4)
resource "hcloud_primary_ip" "primary_ip_1" {
  name          = "primary_ip_test"
  datacenter    = "fsn1-dc14"
  type          = "ipv4"
  assignee_type = "server"
  auto_delete   = true
  labels = {
    "hallo" : "welt"
  }
}

resource "hcloud_server" "server_test" {
  name        = "test-server"
  image       = "ubuntu-20.04"
  server_type = "cx11"
  datacenter  = "fsn1-dc14"
  labels = {
    "test" : "tessst1"
  }
  public_net {
    ipv4_enabled = true
    ipv4         = hcloud_primary_ip.primary_ip_1.id
    ipv6_enabled = false
  }
}
```

Can you please post the full configuration where this happens for you?

**Comment by ofrzeta** [comment]
You are right. Trying to reproduce the issue myself I guess I had the wrongly formatted hostname in the "name" property. Maybe I was misled by the error message that looks like this:
```
│ Error: invalid input in field 'name' (invalid_input): [name => [Name must be a valid hostname.]]
│ 
│   with hcloud_server.ms_customer[0],
│   on main.tf line 34, in resource "hcloud_server" "ms_customer":
│   34: resource "hcloud_server" "ms_customer" {
```
Because that line is ok but the property below is not. Anyway, thanks for your help and sorry for the disturbance!
