### ISSUE TITLE
[Feature]: Support disabling public interface of load balancers

### ISSUE THREAD

**Issue by MartinNowak** [hetznercloud/terraform-provider-hcloud#623]
### What whould you like to see?

Hi, we're using a load balancer for some internal services and thanks to the possibility of detaching it from the public internet, we can do that even [without firewall support](https://docs.hetzner.com/cloud/firewalls/faq/#can-firewalls-be-applied-to-my-hetzner-cloud-load-balancers).
Would be great if we could deploy that directly from terraform rather than having to send an additional [API request](https://docs.hetzner.cloud/#load-balancer-actions-disable-the-public-interface-of-a-load-balancer).

```hcl
resource "hcloud_load_balancer" "load_balancer" {
  name                     = "my-load-balancer"
  load_balancer_type       = "lb11"
  location                 = "nbg1"
  disable_public_interface = true
}
```

**Comment by apricote** [comment]
Hey @MartinNowak,

you can set this flag on the [`hcloud_load_balancer_network`](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/load_balancer_network#enable_public_interface) resource:

```terraform
resource "hcloud_load_balancer_network" "load_balancer" {
  load_balancer_id        = hcloud_load_balancer.load_balancer.id
  network_id              = hcloud_network.your_network.id
  enable_public_interface = false
}
```
