### ISSUE TITLE
How can I rebuild a server using a snapshot ?

### ISSUE THREAD

**Issue by pchandra19** [hetznercloud/terraform-provider-hcloud#624]
Hi , 

I wanted to know if there is a way to rebuild a server using snapshot ?
If so, can you please provide an example or point me to the doc. for same. 

Thanks,
Prateek

**Comment by apricote** [comment]
Hey @pchandra19,

rebuilding a server like you can do in our API or Cloud Console is not possible in Terraform. It does not really match how you would work with terraform, and that is why its not implemented.

You can however create new servers using the snapshot, you just need to specify the snapshot id in argument [`image`](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/server#image):

```terraform
resource "hcloud_server" "from_snapshot" {
  name        = "from-snapshot"
  image       = "<your-snapshot-id>"
  server_type = "cx11"
  location    = "hel1"
}

**Comment by pchandra19** [comment]
@apricote Yes, I know about the apis and how to create server using snapshot in terraform. But many thanks for confirming that rebuild will not be implemented in terraform. This makes it easier for me to take a decision on a certain task at hand.
