### ISSUE TITLE
How do I upload new images to Hetzner Cloud using this Terraform provider?

### ISSUE THREAD

**Issue by devurandom** [hetznercloud/terraform-provider-hcloud#63]
I was so far unable to figure out how to upload new images to Hetzner Cloud using this Terraform provider (or at all, for that matter). The [documentation describes how to access existing images](https://www.terraform.io/docs/providers/hcloud/d/image.html) and it even hints at the possibility to upload images using Terraform ("This resource is useful if you want to use a non-terraform managed image."), but it is not obvious how to do that.

Hence my question: How do I upload new images to Hetzner Cloud using this Terraform provider?

**Comment by LKaemmerling** [comment]
You can not upload new images to the Hetzner Cloud. With the sentence:

> This resource is useful if you want to use a non-terraform managed image.

It is meant, that you could access our system images like (ubuntu, debian, centos or fedora) as a datasource.

**Comment by suchwerk** [comment]
You can use hashicorp packer to generate server snapshots. These snapshots can be used (if referenced by their id) like:

`resource "hcloud_server" "main" {
  image  = "424242"
}`

**Comment by devurandom** [comment]
> You can not upload new images to the Hetzner Cloud.

I would like to add information I got from customer support recently: It is possible to send customer support a download URL to an image and they will upload it manually and make it available in my Hetzner Cloud.

> You can use hashicorp packer to generate server snapshots.

Thanks. That at least allows me to automatically create variants of the Hetzner system images.

**Comment by LKaemmerling** [comment]
> It is possible to send customer support a download URL to an image and they will upload it manually and make it available in my Hetzner Cloud.

Just for correctness:
You can not upload an `image`. The process you described is for `iso` files.
