### ISSUE TITLE
hcloud_server as data source

### ISSUE THREAD

**Issue by c33s** [hetznercloud/terraform-provider-hcloud#64]
to keep the configs dry, i try to group repeated stuff in modules. having `hcloud_server` and `hcloud_floating_ip_assignment` in the same module let everything work nice but if i separate the floating ip assignment from my `server_module` to a standalone `float_module` makes it difficult to run provisioners.

```
resource "hcloud_floating_ip" "main_ip" {
  type = "ipv4"
  home_location = "${local.floating_ip_homelocation}"
}
data "template_file" "floating-ip" {
  template = "${file("${local.template_dir}/floating-ip.cfg")}"
  vars {
    ip = "${hcloud_floating_ip.main_ip.ip_address}"
    interface_name = "${var.floating_ip_interface_name}"
  }
}

resource "hcloud_floating_ip_assignment" "main_ip_assignment" {
  floating_ip_id = "${hcloud_floating_ip.main_ip.id}"
  server_id = "${hcloud_server.my_hserver.id}"

  provisioner "file" {
    content     = "${data.template_file.floating-ip.rendered}"
    destination = "${var.floating_ip_config_file}"
    connection {
      host  = "${hcloud_server.my_hserver.ipv4_address}"
      agent = true
    }
  }
  provisioner "remote-exec" {
    inline = [
        "service networking restart",
    ]
    connection {
      host  = "${hcloud_server.my_hserver.ipv4_address}"
      agent = true
    }
  }
  provisioner "remote-exec" {
    when    = "destroy"
    inline = [
      "rm ${var.floating_ip_config_file}",
      "service networking restart",
    ]
    connection {
      host  = "${hcloud_server.my_hserver.ipv4_address}"
      agent = true
    }
  }
}
```
i can't pass resources into a module, so i have to stick to simple types. i can only pass a `server_id` to the module but then i would need to create a data source from the passed `Server_id` inside of the module to access description, id, ip, ... for provisioners

**Comment by LKaemmerling** [comment]
The idea for creation a dedicated `hcloud_server` datasource sounds good for me, i will discuss it internally and prepare a PR for this.

The only negative thing about a datasource (for this particular use case) is the additional API call that is made when retrieving a datasource, although the data actually already exists (through the resource). Unfortunately, as far as I know there is no easy solution, so we have to accept another API call. I don't see any danger with smaller setups. Only with larger setups the probability to run into the API Rate Limit is relatively high.
