### ISSUE TITLE
[Feature]: Allow creating server with attached volume

### ISSUE THREAD

**Issue by CGamesPlay** [hetznercloud/terraform-provider-hcloud#647]
### What whould you like to see?

It's possible to use `hcloud_server` and `hcloud_volume_attachment` to create a server and then attach it, however these are separate operations and the server will begin to boot before the volume is attached. It's also possible for the volume attachment to fail if the volume is in a different region than the server is created.

When using the hcloud CLI, it's possible to create a server with the volume attachment at the same time. This means the volume is available instantly on the server, and the whole call fails if the region is invalid.

Feature request: add `volume_ids` to `hcloud_server` to enable attaching a volume in the same instant that the server is created.

**Comment by apricote** [comment]
Hey @CGamesPlay, this was requested in #502 already. Going to close this issue :)
