### ISSUE TITLE
[Bug]: with_selector for images retrieves no output.

### ISSUE THREAD

**Issue by amosmid** [hetznercloud/terraform-provider-hcloud#662]
### What happened?

My goal is to retrieve the available images, filter them and output them.

As a filter I applied the following selectors for testing purposes: 

```
data "hcloud_images" "images" {
    with_selector = "architecture=x86"
}
```
and in second run

```
data "hcloud_images" "images" {
    with_selector = "os_flavor=debian"
}
```
Without specifying the selectors, we get all available images, as expected. By specifying the selectors, we get 0 results each time.

### What did you expect to happen?

We expected at least a list consisting of images with x86 architecture or only images with os-flavor debian.

### Please provide a minimal working example

```
terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
      version = "1.35.2"
    }
  }
}

data "hcloud_images" "images" {
    with_selector = "os_flavor=debian"
}

output "images" {
value = data.hcloud_images.images
}
```

EDIT: Same issue with version 1.38.1.

**Comment by apricote** [comment]
Hey @amosmid,

the `with_selector` argument is to specify a [label selector](https://docs.hetzner.cloud/#label-selector). The official images do not have any labels set.

To filter for the architecture, you can use the `with_architecture` argument:

```hcl
data "hcloud_images" "images" {
    with_architecture = ["x86"]
}
```

There is currently no way to filter by the `os_flavor`, as we generally only implement filters that are supported by the [API](https://docs.hetzner.cloud/#images-get-all-images).

I hope this answers your questions, I am going to close the issue but you can still comment here if you have further questions/problems.
