### ISSUE TITLE
[Bug]: load_balancer_network validation does not check if either subnet_id or network_id is set

### ISSUE THREAD

**Issue by sinuscosinustan** [hetznercloud/terraform-provider-hcloud#663]
### What happened?

I've tried to disable the public network without defining a network_id nor a subnet_id. For obvious reasons, the validation should break because
 - The public network can't be disabled without a private network attached
 - The load balancer needs any info how to connect to the private network

### What did you expect to happen?

Validation fails with `Either subnet_id or network_id is required`.

### Please provide a minimal working example

```Terraform
resource "hcloud_load_balancer" "apiserver" {
  name               = "apitest"
  load_balancer_type = "lb11"
  location           = "fsn1"
  algorithm {
    type = "least_connections"
  }
}

resource "hcloud_load_balancer_network" "apiserver" {
  load_balancer_id        = hcloud_load_balancer.apiserver.id
  enable_public_interface = false
}
```

**Comment by apricote** [comment]
Hey Tom,

I dont understand what the issue is here. You wrote that you expect the validation to fail with this message, and for me it happens exactly like that.

You also wrote that you tried to __disable__ the public network, but your example has it set to __enabled__.

**Comment by sinuscosinustan** [comment]
> You also wrote that you tried to disable the public network, but your example has it set to enabled.

woops. Looks like a copy pasta issue :see_no_evil: 

> I dont understand what the issue is here. You wrote that you expect the validation to fail with this message, and for me it happens exactly like that.

If you do a `terraform plan`, the validation passes. But as soon as I try to deploy it, it fails. Maybe I should've clarified that further

**Comment by apricote** [comment]
Understood :) Added some earlier validation in #721
