### ISSUE TITLE
[Bug]:  The apps cannot be used instead of the os images

### ISSUE THREAD

**Issue by maxmielchen** [hetznercloud/terraform-provider-hcloud#664]
### What happened?

When I tried to create a server with the intended terraform script, it unfortunately only worked if I entered the value "ubuntu-..." for the "image" argument, but if I tried to set the value for "image" to "docker-ce" I got this error message:

```
Error: image docker_ce for architecture x86 not found
```

### What did you expect to happen?

I think that at the moment it is not possible to start a server with docker-ce and the other apps or that you have to use some trick for the image name so that the server understands it.

### Please provide a minimal working example

```hcl
resource "hcloud_server" "example" {
    name = "example"
    server_type = "cx11"
    image = "docker-ce"
}
```

**Comment by laurnts** [comment]
I also have similar issues while running with terraform.

Error: more than one Image found for name ubuntu-20.04

I think the problem is that Hetzner introduced new server architecture the ARM architecture. This require different os images. Hence there are 2 different images (maybe sharing the same name), but for different OS'es. Defining the OS'es architecture according to the documentation also doesn't seem to fix the issue atm.

**Comment by laurnts** [comment]
@maxmielchen I found the solution on other post (temporary). Only works if you use non-arm cloud server
add this to your main.tf on top of the resource
```
data "hcloud_images" "images" {
    with_architecture = ["x86"]
}
```

**Comment by maxmielchen** [comment]
Yes, that worked. I have the solution here again, once for arm and once for x86.

x86
```hcl
data "hcloud_image" "docker_ce_x86" {
    name = "docker-ce"
    with_architecture = "x86"
}

resource "hcloud_server" "example_x86" {
    name = "example-x86"
    server_type = "cx11"
    image = data.hcloud_image.docker_ce_x86.id
    location = "fsn1"
}
```

arm
```hcl
data "hcloud_image" "docker_ce_arm" {
    name = "docker-ce"
    with_architecture = "arm"
}

resource "hcloud_server" "example_arm" {
    name = "example-arm"
    server_type = "cax11"
    image = data.hcloud_image.docker_ce_arm.id
    location = "fsn1"
}
```

**Comment by apricote** [comment]
Hey together,

I just tested this with v1.38.2 of the terraform provider and this config:

```terraform
resource "hcloud_server" "x86" {
  name        = "tf-x86-oca"
  location    = "fsn1"
  server_type = "cx11"
  image       = "docker-ce"
}

resource "hcloud_server" "arm" {
  name        = "tf-arm-oca"
  location    = "fsn1"
  server_type = "cax11"
  image       = "docker-ce"
}
```

And it worked for both instances.

Could you try again with the latest version of the provider and if its still not working send me additional logs to my email at `julian.toelle <at> hetzner-cloud.de`? You can generate the additional logs using `TF_LOG=TRACE TF_LOG_PATH=oca-per-name.log terraform apply`
