### ISSUE TITLE
[Bug]: data.hcloud_image source, the most_recent option doesn't work

### ISSUE THREAD

**Issue by alrf** [hetznercloud/terraform-provider-hcloud#665]
### What happened?

`data.hcloud_image`  source, the `most_recent` option doesn't work as expected:
[most_recent](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/data-sources/image#most_recent) - (Optional, bool) If more than one result is returned, use the most recent Image.

But in both cases (`true/false`) it returns an old image.

Checked with provider versions: 1.36.2, 1.38.2

### What did you expect to happen?

With `most_recent=true` the latest version of the ubuntu-20.04 image should be returned.

### Please provide a minimal working example

```
data "hcloud_image" "ubuntu" {
  name        = "ubuntu-20.04"
  most_recent = true
}
```
and
```
data "hcloud_image" "ubuntu" {
  name        = "ubuntu-20.04"
  most_recent = false
}
```

in both cases it returns the old image created by `2020-04-23T17:55:14Z`:
```
{
  "architecture" = "x86"
  "created" = "2020-04-23T17:55:14Z"
  "deprecated" = tostring(null)
  "description" = "Ubuntu 20.04"
  "id" = 15512617
  "labels" = tomap({})
  "most_recent" = true
  "name" = "ubuntu-20.04"
  "os_flavor" = "ubuntu"
  "os_version" = "20.04"
  "rapid_deploy" = true
  "selector" = tostring(null)
  "type" = "system"
  "with_architecture" = "x86"
  "with_selector" = tostring(null)
  "with_status" = tolist(null) /* of string */
}
```

however, the recent image is (created by `2023-03-20T10:09:51Z`):
```
{
  + created      = "2023-03-20T10:09:51Z"
  + deprecated   = ""
  + description  = "Ubuntu 20.04"
  + id           = 103908070
  + labels       = {}
  + name         = "ubuntu-20.04"
  + os_flavor    = "ubuntu"
  + os_version   = "20.04"
  + rapid_deploy = true
  + selector     = ""
  + type         = "system"
}
```

**Comment by alrf** [comment]
It works as expected with `with_architecture = "x86"` option.

**Comment by apricote** [comment]
Hey @alrf,

as you have already noticed, the images `15512617` & `103908070` have different architectures and we only return x86 images by default. The `most_recent` flag should be used when you use `with_selector` to filter images by labels.
