### ISSUE TITLE
[Bug]: select server-image by name not working

### ISSUE THREAD

**Issue by mm-ruhri** [hetznercloud/terraform-provider-hcloud#666]
### What happened?

I created a new server with an debian-11 image and got  
`Error: more than one Image found for name debian-11`

### What did you expect to happen?

A server created with the debian-11 image for x86

As there are new arm-Server-types (aka cax11) there exist two images named debian-11 (one x86 and one arm).
The hetzner cloud-api will select the right one by architecture of the server. Here i have to use the image-id as workaround.
 -> could be documented
 

### Please provide a minimal working example

```
resource "hcloud_server" "bluenode" {
  name         = "bluenode"
  image        =  "debian-11"
  server_type  = "cx11" 
  public_net {
    ipv4_enabled = true
    ipv6_enabled = true
  }
}
```

**Comment by apricote** [comment]
Hey @mm-ruhri, please update your version of the terraform provider. This is fixed in version v1.38.0+ (but best to use the latest version v1.38.2 atm).
