### ISSUE TITLE
[Bug]: Starting ARM server in rescue mode fails

### ISSUE THREAD

**Issue by blackkaven** [hetznercloud/terraform-provider-hcloud#667]
### What happened?

I tried to install flatcar on a ARM server this fails as the IP address given by the ARM server refuses SSH access.

![image](https://user-images.githubusercontent.com/1243180/233740017-6cdd0bc1-813f-4e8b-bf25-941c9b837c8d.png)

### What did you expect to happen?

The ssh connection should  work as it does vor x86 servers e.g. `cpx11`

### Please provide a minimal working example

```
terraform {
  required_version = ">= 0.13"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "1.38.2"
    }
  }
}

provider "hcloud" {
  token = <YOUR TOKEN HERE>
}

resource "hcloud_server" "flatcar-0" {
  name        = "flatcar-0"
  rescue      = "linux64"
  image       = "debian-11"
  server_type = "cax11"
  location    = "fsn1"
  ssh_keys    = ["YOUR SSH KEY HERE"]
  public_net {
    ipv4_enabled = true
    ipv6_enabled = true
  }
  connection {
    user        = "root"
    host        = self.ipv4_address
    timeout     = "1m"
  }
  provisioner "remote-exec" {
    inline = [
      "echo -n 'hi'",
    ]
  }
}
```

**Comment by apricote** [comment]
Hey @blackkaven,

this is a known bug in our rescue system, that causes the Arm rescue system to start very slowly if there is an IPv6 subnet attached. If you set `ipv6_enabled = false` or set the timeout to a larger value (4m worked in my tests) it should work.

We are working on a fix for the rescue system, but I can not provide you with an ETA for the fix. I will post an update once this is fixed from our side.

/cc @tomsiewert

**Comment by sinuscosinustan** [comment]
The slow start bug in combination with enabled IPv6 has been fixed on Wednesday. Please check if you still encounter the issue.

**Comment by blackkaven** [comment]
> The slow start bug in combination with enabled IPv6 has been fixed on Wednesday. Please check if you still encounter the issue.

Yeah it is a lot better it only takes around 1.5 minutes now.

**Comment by sinuscosinustan** [comment]
> > The slow start bug in combination with enabled IPv6 has been fixed on Wednesday. Please check if you still encounter the issue.
> 
> Yeah it is a lot better it only takes around 1.5 minutes now.

Is your mentioned issue fixed with that or do we need to investigate this further?

**Comment by blackkaven** [comment]
> > > The slow start bug in combination with enabled IPv6 has been fixed on Wednesday. Please check if you still encounter the issue.
> > 
> > 
> > Yeah it is a lot better it only takes around 1.5 minutes now.
> 
> Is your mentioned issue fixed with that or do we need to investigate this further?

No for me it is fixed.
