### ISSUE TITLE
[Feature]: Allow setting rdns for serverless primary_ip's

### ISSUE THREAD

**Issue by talamus** [hetznercloud/terraform-provider-hcloud#668]
### What whould you like to see?

You can create a server-less `"hcloud_primary_ip"`, but currently you cannot assign `"hcloud_rdns"` to it without a server.

The Hetzner Cloud API does allow this:
https://docs.hetzner.cloud/#primary-ip-actions-change-reverse-dns-entry-for-a-primary-ip

Could you add a `primary_ip_id` argument to the `"hcloud_rdns"`:
https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/rdns

Thank you for your work!

**Comment by apricote** [comment]
This will require some changes in `hcloud-go` so `PrimaryIP` implements the `RDNSSupporter` interface. Working on it :)

**Comment by apricote** [comment]
Related PRs:

- hetznercloud/hcloud-go#252
- #669
