### ISSUE TITLE
[Feature]: Support Hetzner DNS API

### ISSUE THREAD

**Issue by spoletum** [hetznercloud/terraform-provider-hcloud#671]
### What whould you like to see?

I would like to see the Hetzner DNS APIs to be mapped as Terraform resources so that I can map servers to A entries.

**Comment by strgalt-t** [comment]
While waiting for an official support, you can utilize the Hetzerdns provider: https://registry.terraform.io/providers/timohirt/hetznerdns/latest

**Comment by truh** [comment]
I would still like to see this.

**Comment by apricote** [comment]
Thanks for the interest but right now this provider is focused on the _Hetzner Cloud API_. The _Hetzner DNS API_ is a separate project, which uses a different authentication schema.

**Comment by gowizzard** [comment]
Hi @apricote, has anything changed in the project? We also need an integration for the DNS API.

**Comment by apricote** [comment]
Hey @gowizzard,

nothing has changed, `Hetzner DNS` is still a separate API with a different authentication schema. Any updates would be posted to the _Hetzner Cloud_ Changelog. You can subscribe per RSS if you want to get notifications: https://docs.hetzner.cloud/changelog  

We are looking for Go developers who want to work on DNS: https://hetzner-cloud.de/en/jobs/1366639

**Comment by gowizzard** [comment]
Hi @apricote, that's a pity, I guess many would find this feature useful, even if in a second Terraform project.

Perhaps we will have to develop something directly for it in our company or fall back on the existing third-party solution.

Thank you for the offer, if something changes for me professionally, I will gladly keep this in mind.

Have a good start to the week!

**Comment by c33s** [comment]
i also miss this feature very much (in hcloud cli tool and in the terraform provider). what about reopening the issue to get more attention, it would also promote your job offers. maybe even pin it.
it feels strange to have such an awesome provider from a company which misses out dns (and storage boxes!).
