### ISSUE TITLE
[Bug]: centos-stream-9 and centos-Stream-9 images for x86 and ARM

### ISSUE THREAD

**Issue by strgalt-t** [hetznercloud/terraform-provider-hcloud#673]
### What happened?

Hello,

I've stumbled upon an issue when creating an ARM server with the centos-stream-9 image.

While the image name "centos-stream-9" works fine with x86 severs, for ARM servers the name has to be "centos-Stream-9", with an uppercase S.

This can be double checked with the hcloud cli, where hcloud list images 

### What did you expect to happen?

I've expected the image name for x86 and ARM servers to be the same, as is the behavior with other OSes.

### Please provide a minimal working example

Works:
resource "hcloud_server" "test-arm" {
  name               = var.name
  image              = "centos-Stream-9"
  server_type        = "cax21"
  location           = var.location
}

Doesn't work:
resource "hcloud_server" "test-arm" {
  name               = var.name
  image              = "centos-stream-9"
  server_type        = "cax21"
  location           = var.location
}

**Comment by apricote** [comment]
Thanks for the report @strgalt-t! Fixed the names in our API, should work as expected now.
