### ISSUE TITLE
[Feature]: Volume `mount_path`

### ISSUE THREAD

**Issue by hey-leon** [hetznercloud/terraform-provider-hcloud#674]
### What whould you like to see?

NOTE: This was mentioned on another [issue](https://github.com/hetznercloud/terraform-provider-hcloud/issues/473#issuecomment-1248036135) but I thought it would be good to track it in a separate issue.

Currently there is no way to specify a mount path for a volume. I did some digging and it appears that the issue spans multiple layers. AFAICT:
- there is no argument for any terraform resources
- hcloud-go volume.AttachWithOpts does not support it
- Hetzner Cloud API does not support

However this seems like it is a pretty useful feature. To add an example of what this could look like:

```terraform
resource "hcloud_server" "node" {
  name        = "node1"
  image       = "debian-11"
  server_type = "cx11"
}

resource "hcloud_volume" "node_volume" {
  name       = "node-volume"
  size       = 50
  server_id  = hcloud_server.node.id
  mount_path = "/mnt/node-volume"
  automount  = true
  format     = "ext4"
}
```

**Comment by apricote** [comment]
Hello @hey-leon,

I have forwarded the feature request to the responsible team. As this is currently not possible in our API, and we can only implement was is available, I am going to close this issue here.
