### ISSUE TITLE
[Bug]: hcloud_network_subnet vswitch_id is not working

### ISSUE THREAD

**Issue by zboralski** [hetznercloud/terraform-provider-hcloud#675]
### What happened?

I am experiencing issues with the vswitch_id parameter of the hcloud_network_subnet resource. I have defined a subnet for nomad_clients with the following configuration:

However, the subnet does not show the `vswitch_id` in the Cloud interface:

![image](https://user-images.githubusercontent.com/104316/236358221-fe43c893-e14a-473c-a2fd-d312a6f25b2b.png)

The corresponding vSwitch is not connected to the subnet in the robot interface.

### What did you expect to happen?

On the other hand, when I manually create a subnet, the vswitch_id is correctly displayed in the Cloud interface:

![image](https://user-images.githubusercontent.com/104316/236358466-156a21ea-36b7-47a4-a72c-a6d5a5d1059f.png)

And the corresponding vSwitch is connected to the subnet in the robot interface:

![image](https://user-images.githubusercontent.com/104316/236358515-0a714101-155d-468d-8b5d-36aa4f76d3c7.png)

### Please provide a minimal working example

```
❯ (cd terraform; terraform state show hcloud_network_subnet.nomad_clients)
# hcloud_network_subnet.nomad_clients:
resource "hcloud_network_subnet" "nomad_clients" {
    gateway      = "10.0.0.1"
    id           = "2849705-10.0.1.0/24"
    ip_range     = "10.0.1.0/24"
    network_id   = 2849705
    network_zone = "eu-central"
    type         = "cloud"
    vswitch_id   = 39784
}
```

**Comment by apricote** [comment]
Hey @zboralski,

when you add a vSwitch to a network, you need to set `type = "vswitch"` in your terraform configuration. You currently use `type = "cloud"`.

You can read more on the documentation page: https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/network_subnet

I am going to close the issue, please feel free to respond here if its still not working after changing the type :)
