### ISSUE TITLE
[Bug]: terraform destroy "Still destroying... " until timeout error.

### ISSUE THREAD

**Issue by wondertalik** [hetznercloud/terraform-provider-hcloud#676]
### What happened?

I am using this [repo](https://github.com/wondertalik/terraform-k8s-hcloud) to deploy k8s cluster. The problem that after creation `terraform destroy` doesnt work properly. 

```
hcloud_network_subnet.private_network_subnet: Still destroying... [id=2851542-10.98.0.0/16, 2m50s elapsed]
hcloud_server.worker[1]: Still destroying... [id=32110003, 3m0s elapsed]
hcloud_network_subnet.private_network_subnet: Still destroying... [id=2851542-10.98.0.0/16, 3m0s elapsed]
hcloud_server.worker[1]: Still destroying... [id=32110003, 3m10s elapsed]
hcloud_network_subnet.private_network_subnet: Still destroying... [id=2851542-10.98.0.0/16, 3m10s elapsed]
```

I believe that is because load balancer that was created by ingress controller did not remove. After deleteting it manualy destroy fineshed without any problem.

### What did you expect to happen?

Terraform destroys all resources.

### Please provide a minimal working example

create k8s cluster with this configuration.

```terraform.tfvars
cluster_name                    = "k8sdev"
hcloud_token                    = "your token"
k8s_hcloud_token                = "your token"
entrance_type                   = "cx11"
master_type                     = "cx21"
master_count                    = 3
worker_type                     = "cx21"
worker_count                    = 2
kubernetes_version              = "1.26.4"
containerd_version              = "1.7.0"
private_network_ip_range        = "10.98.0.0/16"
private_network_subnet_ip_range = "10.98.0.0/16"
load_balancer_master_private_ip = "10.98.0.2"
ssh_private_key_entrance        = "~/.ssh/id_hetzner_entrance"
ssh_public_key_entrance         = "~/.ssh/id_hetzner_entrance.pub"
ssh_private_key_nodes           = "~/.ssh/id_hetzner_nodes"
ssh_public_key_nodes            = "~/.ssh/id_hetzner_nodes.pub"
custom_ssh_port                 = 22871
user_name                       = "user"
user_passwd                     = "password_hash"

ingress_enabled                 = true
ingress_count                   = 1
cilium_enabled                  = true
hccm_enabled                    = true
```

**Comment by apricote** [comment]
Hey @wondertalik,

Terraform can only delete resources that it knows about. As you created the Load Balancer outside of the Terraform state (through the hcloud-cloud-controller-manager), Terraform can not remove it.

Deleting the subnet is stuck, because the Load Balancer was still assigned to it. I am not sure why the server would not be deleted though, perhaps also because it was configured as a target in the LB?

**Comment by wondertalik** [comment]
@apricote, ok i understand, will change configuration. thanks.

**Comment by wondertalik** [comment]
Hi, there. So i changed configuration to create load-balancer by terraform. But now terraform wants to change every time port of load balancer of 80 and 443. 

```bash
#  terraform plan -out="k8s-dev-stand.plan"

  # hcloud_load_balancer_service.ingress_https_load_balancer_service[0] will be updated in-place
  ~ resource "hcloud_load_balancer_service" "ingress_https_load_balancer_service" {
      ~ destination_port = 30210 -> 443
        id               = "1277782__443"
        # (4 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

Probably it because hcloud-controller-manager (k8s) changed it from 443 -> 30210, 80 -> 31530. Is it posible to do something with that?

**Comment by apricote** [comment]
Kubernetes will select a random nodePort for the `LoadBalancer` service if you do not specify one. HCCM assigns the service port to match this, to make the traffic reach the right target.

You can override this selection to whatever you want by setting `service.spec.ports[*].nodePort` to your desired value.

This is unrelated to the terraform-provider-hcloud
