### ISSUE TITLE
[Feature]: return disksize from hcloud_server resource/datasource

### ISSUE THREAD

**Issue by harmesit** [hetznercloud/terraform-provider-hcloud#683]
### What whould you like to see?

currently, you are able to not scale the Disk when scaling the rest of the Server resources which is nice for later downgrade. doing so in the Webui does not change the data returned for the resource or datasource.

this leads to inconsistencies when using terraform to automatically document the vm aside from just creating and managing it when documenting the available resources via the server_type datasource only.

**Comment by EttoreFoti** [comment]
I would like to work on it.

edit: https://github.com/hetznercloud/terraform-provider-hcloud/pull/801

This should be enough to add the data you're interested in.

**Comment by apricote** [comment]
Implemented in #801
