### ISSUE TITLE
[Bug]: accessing non-existing ipv6_address results in "<nil>1"

### ISSUE THREAD

**Issue by c33s** [hetznercloud/terraform-provider-hcloud#687]
### What happened?

outputting the previous disabled but then enabled and not created  ipv6_address for output leads to `<nil>1` as output

---

i report this mainly for googlers, i am not sure if it is possible to easily reproduce this but as i found some bugs which also outputs this result i thought it is worth having a dedicated issue.

https://github.com/hetznercloud/terraform-provider-hcloud/issues/571
https://github.com/hetznercloud/terraform-provider-hcloud/issues/482

- using terragrunt
- using gitlab as state backend
- i created a server where i enabled ipv4 (terraform apply)
- after i created the server i enabled the ipv6 and added `dns_records` to the output
- running `terraform plan` (`terragrunt plan` in particular) leads to the output `<nil>1` for the ipv6_address `hcloud_server.standard_servers[name]["ipv6_address"]`

```
Terraform v1.4.4
on linux_amd64
+ provider registry.terraform.io/hetznercloud/hcloud v1.39.0
+ provider registry.terraform.io/timohirt/hetznerdns v2.2.0
```

```
locals {
  dns_records = merge([
    for name, server in local.servers : {
      for address_type in ["ipv4", "ipv6"] : "${name}_${address_type}" => {
        zone_id = coalesce(server.dns_record.zone_id, var.internal_zone.zone_id)
        name    = coalesce(server.dns_record.name, name)
        value   = coalesce(server.dns_record.value, hcloud_server.standard_servers[name][address_type == "ipv4" ? "ipv4_address" : "ipv6_address"])
        type    = address_type == "ipv4" ? "A" : "AAAA"
        ttl     = coalesce(server.dns_record.ttl, 300)
      }
    }
  ]...)
}
```

### What did you expect to happen?

outputting the address should result in a valid `<nil>` aka `null`

### Please provide a minimal working example

i have quite a complex setup with terragrunt. just wanted to report the `<nil>1` output is happening again. if i have some time and i am able to create a reporducer i will provide a minimal working example later.

**Comment by apricote** [comment]
Minimal reproduction:

```tf
resource "hcloud_server" "tf_687" {
  server_type = "cax11"
  name = "tf-687"
  image = "ubuntu-22.04"
  location = "fsn1"

  public_net {
    ipv4_enabled = true
    ipv6_enabled = false
  }
}

output "ipv6" {
  value = hcloud_server.tf_687.ipv6_address
}
```

Output:

```
ipv6 = "<nil>1"
```

**Comment by apricote** [comment]
Thanks for reporting the bug @c33s :) Will be fixed in the next release.
