### ISSUE TITLE
[Bug]: hcloud_load_balancer Argument service

### ISSUE THREAD

**Issue by MarcoWel** [hetznercloud/terraform-provider-hcloud#699]
### What happened?

Output:
```
│ Error: Unsupported argument
│ 
│   on main.tf line 328, in resource "hcloud_load_balancer" "lb":
│  328:   service = [
│ 
│ An argument named "service" is not expected here.
```

### What did you expect to happen?

Building a load balancer works, but not if the service argument is specified.

### Please provide a minimal working example

```
resource "hcloud_load_balancer" "lb" {
  name        = "mylb"
  load_balancer_type = "lb11"
  location    ="nbg1"

  service = [
    {
      protocol = "http"
      listen_port = 80
      destination_port = 80
      proxyprotocol = true
      health_check = {
        protocol = "tcp"
        port = 80
        interval = 3
        timeout = 3
        retries = 3
      }
    },
    {
      protocol = "https"
      listen_port = 443
      destination_port = 80
      proxyprotocol = true
      health_check = {
        protocol = "tcp"
        port = 80
        interval = 3
        timeout = 3
        retries = 3
      }
    }
  ]
}
```

**Comment by apricote** [comment]
Hey @MarcoWel,

there is no `service` argument for `hcloud_load_balancer`. To create services you can use the [`hcloud_load_balancer_service`](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/load_balancer_service) resource.

**Comment by MarcoWel** [comment]
Hi @apricote,
Thank you for the quick reply! I must have missed this. However the Terraform docs are not clear though, see:

> [service](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/load_balancer#service) - (list) List of services a Load Balancer provides.

**Comment by apricote** [comment]
Mh, not sure how that got in the docs, there is no `service` argument/attribute in the code. Removing it in #701.

It was under the "Attributes" section though, which are read-only. You can only set the "Arguments" in your code.

Thanks for the hint :)
