### ISSUE TITLE
[Bug]: hcloud_managed_certificate creation fails (timeout)

### ISSUE THREAD

**Issue by felixscheinost** [hetznercloud/terraform-provider-hcloud#705]
### What happened?

Deployment fails:

```
Error: hcclient/WaitForActions: action 1074026836 failed: Could not verify domain was delegated to DNS zone (certificate_could_not_verify_domain_delegated_to_zone)
```

### What did you expect to happen?

I expected the managed certificate to be created.

### Please provide a minimal working example

I am using CDKTF, but I think the generated JSON is readable enough.

```json
{
  "//": {
    "metadata": {
      "backend": "s3",
      "stackName": "test-network2",
      "version": "0.17.0"
    },
    "outputs": {
    }
  },
  "provider": {
    "hcloud": [
      {
        "token": "${var.hcloud_token_test}"
      }
    ]
  },
  "resource": {
    "hcloud_load_balancer": {
      "k8s-ingress-public-lb": {
        "//": {
          "metadata": {
            "path": "test-network2/k8s-ingress-public-lb",
            "uniqueId": "k8s-ingress-public-lb"
          }
        },
        "load_balancer_type": "lb11",
        "location": "fsn1",
        "name": "k8s-ingress-public-2"
      }
    },
    "hcloud_load_balancer_service": {
      "k8s-ingress-public-tls-termination": {
        "//": {
          "metadata": {
            "path": "test-network2/k8s-ingress-public-tls-termination",
            "uniqueId": "k8s-ingress-public-tls-termination"
          }
        },
        "destination_port": 40080,
        "health_check": {
          "http": {
            "path": "/healthz",
            "status_codes": [
              "200"
            ]
          },
          "interval": 5,
          "port": 40080,
          "protocol": "http",
          "retries": 3,
          "timeout": 1
        },
        "http": {
          "certificates": [
            "${tonumber(hcloud_managed_certificate.wildcard-certificate.id)}"
          ],
          "redirect_http": true
        },
        "load_balancer_id": "${hcloud_load_balancer.k8s-ingress-public-lb.id}",
        "protocol": "https",
        "proxyprotocol": true
      }
    },
    "hcloud_managed_certificate": {
      "wildcard-certificate": {
        "//": {
          "metadata": {
            "path": "test-network2/wildcard-certificate",
            "uniqueId": "wildcard-certificate"
          }
        },
        "depends_on": [
          "hcloud_load_balancer.k8s-ingress-public-lb"
        ],
        "domain_names": [
          "*.<domain_name>"
        ],
        "name": "symentis-com-wildcard"
      }
    },
    "hcloud_network": {
      "backlan": {
        "//": {
          "metadata": {
            "path": "test-network2/backlan",
            "uniqueId": "backlan"
          }
        },
        "ip_range": "10.193.0.0/16",
        "name": "backlan"
      }
    },
    "hcloud_network_subnet": {
      "subnet-loadbalancers": {
        "//": {
          "metadata": {
            "path": "test-network2/subnet-loadbalancers",
            "uniqueId": "subnet-loadbalancers"
          }
        },
        "ip_range": "10.193.1.0/24",
        "network_id": "${tonumber(hcloud_network.backlan.id)}",
        "network_zone": "eu-central",
        "type": "cloud"
      }
    }
  },
  "terraform": {
    "backend": {
      "s3": {}
    },
    "required_providers": {
      "hcloud": {
        "source": "hetznercloud/hcloud",
        "version": "1.36.0"
      }
    }
  },
  "variable": {
    "hcloud_token_test": {
      "sensitive": true
    },
  }
}
```

I think the problem is that the plugin waits until the certificate is completely provisioned, even though the certificate IDs would already be known.

As the `hcloud_managed_certificate` resource isn't finished creating the `hcloud_load_balancer_service` (which would connect the LB to the certificate) isn't created. But without a LB the certificate will never be provisioned so the creation can never succeed.

**Comment by felixscheinost** [comment]
I found a bug in my CDKTF setup which caused an older version of `hetznercloud/hcloud` provider (1.36) to be used than I thought. But I can reproduce this issue with 1.41 as well.

**Comment by apricote** [comment]
Hello @felixscheinost,

managed (LetsEncrypt) certificates can be issues without a Load Balancer. The error message you receive indicates that you have not correctly configured your domain in Hetzner DNS. Please make sure that you have setup the domain in Hetzner DNS in the same Hetzner account that is the owner of the Cloud project.


You can learn more in our docs & tutorials:
- Docs ["What do I need for a Let's Encrypt certificate?"](https://docs.hetzner.com/cloud/load-balancers/faq/#what-do-i-need-for-a-lets-encrypt-certificate)
- Tutorial ["Setting up a Let's Encrypt certificate on cloud load balancers with external domain"](https://community.hetzner.com/tutorials/configure-lb-cert-with-external-domain)


If you are sure that you have setup the DNS zone correctly, please open a [support ticket](https://console.hetzner.cloud/support) so the team can take a look at this.

**Comment by felixscheinost** [comment]
Thanks @apricote, I was just about to post a comment saying the same.

I tried creating a certificate in the UI manually for the same domain and this also failed.

But a certificate for another domain, also in Hetzner DNS, works. 

I am looking into what the issue with that zone is, sorry for the confusion.
