### ISSUE TITLE
[Feature]: Use Application Load Balancers for Blue-Green and Canary Deployments

### ISSUE THREAD

**Issue by shehi** [hetznercloud/terraform-provider-hcloud#711]
### What whould you like to see?

[Terraform Reference Tutorial Example via AWS provider](https://developer.hashicorp.com/terraform/tutorials/aws/blue-green-canary-tests-deployments)

Quoting the above-mentioned tutorial use-case:
> Blue-green deployments and rolling deployments (canary tests) let you release new software gradually, reducing the potential blast radius of a failed software release. This workflow lets you publish software updates with near-zero downtime.

> AWS's [application load balancer](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/introduction.html) (ALB) lets you define rules that route traffic at the application layer. This differs from classic load balancers, which only let you balance traffic across multiple EC2 instances. You can define an ALB's [listeners](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html) (rules) and [target groups](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html) to dynamically route traffic to multiple services. These rules let you run canary tests on and incrementally promote the green environment.

**It would be great to have a similar feature in Hetzner Cloud, and by extension, in this TF provider lib.** That is, the ability to define `weight` for Load-Balancers. Didn't check Hetzner TF docs, but from WebUI, the "Algorithms" section seems to be the best place to implement this feature:

![image](https://github.com/hetznercloud/terraform-provider-hcloud/assets/653569/cafd2763-ebca-4e64-8522-766892daeb32)

**Comment by apricote** [comment]
Hey @shehi,

I have submitted your feedback to our internal feedback tool, thanks for the suggestion!

The terraform provider can only implement features that the Hetzner Cloud API supports. As this feature is currently not supported, I will close the issue.

**Comment by shehi** [comment]
Thanks. Yes, this was rather a feature request from Hetzner Cloud.
