### ISSUE TITLE
[Feature]: Ability to create a new server attached to a private subnet without having to manually manage the IP

### ISSUE THREAD

**Issue by mzhaase** [hetznercloud/terraform-provider-hcloud#714]
### What whould you like to see?

Creating a server that is reachable only via a private subnet is an extremely common use case - maybe _the most common_ use case.

Currently, this is not possible by only using terraform at scale. One has to implement their own IPAM solution to assign IP addresses at creation time. This is not really sensible, when talking about hundreds of servers, managed by multiple independent teams.

Ideally, something similar to this would be implemented.

```HCL
resource "hcloud_server" "this" {
    [...]
    public_net {
        ipv4_enabled = "false"
        ipv6_enabled = "false"
    }
    subnet_id = hcloud_subnet.this.subnet_id
}
```

The server would then be created, with its primary IP chosen randomly from one of the available IPs in hcloud_subnet.this.

As part of this it would also be great for subnets to have labels so we could use a data source to get the subnet_id.

**Comment by apricote** [comment]
Hey @mzhaase,

you said:

> The server would then be created, with its primary IP chosen randomly from one of the available IPs in hcloud_subnet.this.

This does not work, subnets belong to a (private) Network, and they do not contain publicly routable Primary IPs.

If you meant to assign private IP from the subnet, please see https://github.com/hetznercloud/terraform-provider-hcloud/issues/672 for an explanation of the issue. Closing this as duplicate.
