### ISSUE TITLE
[Bug]:  no image found matching the selection

### ISSUE THREAD

**Issue by EdmondAvdalyan** [hetznercloud/terraform-provider-hcloud#716]
### What happened?

We have a packer image configuration which is successfully  created snapshot in  Hetzner Cloud:

Here is the part of my packer config.

```go
source "hcloud" "ubuntu" {
  image        = "ubuntu-22.04"
  server_type  = "cx11"
  ssh_username = "root"
  token        = "hided"
  location     =  "nbg1"
  snapshot_name   = "initial_nomad_setup-{{timestamp}}"
  snapshot_labels = {
    custom_image  = "initial_nomad_setup"
  }
}
``` 

terraform config to use this snapshot to spin up a server.

```go
data "hcloud_image" "filtered_snapshot" {
  with_selector = "custom_image=initial_nomad_setup"
  most_recent   = true
  with_status   = ["available"]
}

resource "hcloud_server" "server" {
  name              = "${var.name}-server"
  image             = data.hcloud_image.filtered_snapshot.id
  server_type       = var.server_instance_type # cx11 The same that I used for snapshot
  location          = var.location # nbg1 The same that I used for snapshot
``` 

So during apply, I see this Error: 
**Error: no image found matching the selection**

### What did you expect to happen?

I decided to try to get directly from hetzner API

curl -H "Authorization: Bearer $API_TOKEN" "https://api.hetzner.cloud/v1/images?type=snapshot"

And I see my image with snapshot type created by Packer

```
"images": [
    {
      "id": 555555,
      "type": "snapshot",
      "status": "available",
      "name": null,
      "description": "initial_nomad_setup-1689063818",
      "image_size": 1.6912361376953124,
      "disk_size": 20,
      "created": "2023-07-11T08:26:09+00:00",
      "created_from": {
        "id": 34738276,
        "name": "packer-64ad118a-c18c-7a5c-1996-8c4f11321641"
      },
      "bound_to": null,
      "os_flavor": "ubuntu",
      "os_version": null,
      "rapid_deploy": false,
      "protection": {
        "delete": false
      },
      "deprecated": null,
      "labels": {
        "custom_image": "initial_nomad_setup"
      },
      "deleted": null,
      "architecture": "x86"
    }
  ],
  "meta": {
    "pagination": {
      "page": 1,
      "per_page": 25,
      "previous_page": null,
      "next_page": null,
      "last_page": 1,
      "total_entries": 1
    }
  }
}

``` 

So for testing, I set the snapshot ID "5555555" in my terraform config

```go
image  =  "555555"
``` 

But I got this error:
 **Error: image 555555 for architecture x86 not found**

### Please provide a minimal working example

Provided above

**Comment by apricote** [comment]
Hey @EdmondAvdalyan, what did you change to make it work?

**Comment by EdmondAvdalyan** [comment]
Hey @apricote , The fault was mine, since I used 'Right' token to create Packer image in Hetzner and 'Wrong token' to spin up a new server.
Sorry for inconvinence

**Comment by apricote** [comment]
No worries :) Documenting what went wrong is always helpful for people who land on this issue through Google.

**Comment by keremispirli** [comment]
@EdmondAvdalyan I have the same error. I created the server via Terraform, but created the Snapshot via Web UI. Is that the reason why it cannot use the selector?

It's strange, because the snapshot image is not entirely invisible; if I provide the correct id, I can create a VM from that image.

**Comment by EdmondAvdalyan** [comment]
@keremispirli , I guess you need to pay attention to server_type, location and architecture type (x86 or any) applied to both the server and snapshot. They have to be the same.

You can also test the snapshot retrieval with your token, which you need to use via terraform.
`curl -H "Authorization: Bearer $API_TOKEN" "https://api.hetzner.cloud/v1/images?type=snapshot"
`

**Comment by keremispirli** [comment]
I use the same code for deploying my VM; the only difference is how I get the ID of the snapshot. If I hardcode it myself, it works:

``` terraform
resource "hcloud_server" "dev" {
  name          = "..."
  image         = 12...
  location      = "fsn1"
  server_type   = "cax31"
  ssh_keys      = [hcloud_ssh_key.dev.id]

  public_net {
    ipv4_enabled = true
    ipv6_enabled = true
  }
}
```

If I introduce an `hcloud_image` resource and use `with_selector` for a label, then it cannot find the image.
``` terraform
data "hcloud_image" "my_image" {
  with_selector = "role=dev"
  most_recent   = true  # removing this doesn't help, either
}

resource "hcloud_server" "dev" {
  name          = "haskell-stack"
  image         = data.hcloud_image.my_image.id
  location      = "fsn1"
  server_type   = "cax31"
  ssh_keys      = [hcloud_ssh_key.dev.id]

  public_net {
    ipv4_enabled = true
    ipv6_enabled = true
  }
}
```

I just tried API call you suggested with the same token I use for terraform deployment. The response contains the correct snapshot with the ID and labels.
``` json
{
  "images": [
    {
      "id": 12...,
      "type": "snapshot",
      "status": "available",
      "name": null,
      "description": "...",
      ...
      "labels": {
        ...
        "role": "dev",
        ...
      },
      "deleted": null,
      "architecture": "arm"
    }
  ],
  "meta": {   ...    }
  }
}
```

**Comment by apricote** [comment]
Hey @keremispirli,

the data resource `hcloud_image` sets `with_architecture = "x86"` by default (for backwards compatibility). If you want to use an an arm image, please add `with_architecture = "arm"` to the datasource.

[Docs](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/data-sources/image#with_architecture)

**Comment by keremispirli** [comment]
Thanks @apricote, it worked! I haven't checked the docs; I just assumed that not passing a filter means no filter.
