### ISSUE TITLE
Creating a hcloud_server from an hcloud_image.id destroys and recreates the server on every apply

### ISSUE THREAD

**Issue by devurandom** [hetznercloud/terraform-provider-hcloud#72]
In a setup like the following, the `hcloud_server` will be destroyed and recreated on every `terraform apply`, citing the `image` attribute changing from a name (e.g. `centos-7`) to an id (e.g. `3`) as the reason:
```hcl
provider "hcloud" {
  token = "${var.hcloud_token}"
}

data "hcloud_image" "centos_7" {
  name = "${var.bastion_image_name}"
}

data "hcloud_ssh_key" "ssh_key" {
  name = "${var.ssh_key_name}"
}

resource "hcloud_server" "bastion" {
  name = "bastion"
  server_type = "cx11"
  image = "${data.hcloud_image.centos_7.id}"
  ssh_keys = ["${data.hcloud_ssh_key.ssh_key.id}"]
}
```

I would expect the logic to be more "intelligent" and check both name and id before deciding that the attribute changed.

This is using:
```
Terraform v0.11.12
+ provider.hcloud v1.8.0
```

**Comment by LKaemmerling** [comment]
After reading a bit through the source on other providers, I would recommend using the image name, from the datasource instead of the ID. 

As long as i see we have no possibility to change this behavior. 

So i will label it with `wontfix`.


~~Edit: Found a possible solution. Will try to implement it.~~
Edit: This is behavior is indeed. When you use a system image (like ubuntu-18.04) with a name, you should use the name of the image instead of the id. If you use a snapshot (or backup) you should use the ID.

**Comment by devurandom** [comment]
This is quite inconvenient, since it means that I cannot switch from a system image to a custom image / snapshot, without also adjusting other code, since `data.hcloud_image.<...>.name` will only work for system images but not for snapshots, while `data.hcloud_image.<...>.id` will only work for snapshots but not for system images.

I now work around this using a local for each image, but it appears to be cumbersome and unnecessarily difficult for newcomers:
```hcl
locals {
  NODETYPE_image = "${data.hcloud_image.NODETYPE.name != "" ? data.hcloud_image.NODETYPE.name : data.hcloud_image.NODETYPE.id}"
}
```

Maybe a possible solution would be to have an `image_id` argument on `hcloud_server`? That way the `hcloud_server` state fetched from the Hetzner Cloud API (which for the `image` attribute currently appears to contain the `name` for system images, but the `id` for custom ones) and the desired configuration of that `hcloud_server` (which in my example contains the `id` in the `image` argument) would stop disagreeing, because the new `image_id` argument and the `image_id` attribute would both always use the `id`.

I suggest to go one step further and deprecate the `image` argument / attribute. This would force people to go through the `hcloud_image` datasource to resolve an image name into an id, which can then be used with the `image_id` argument / attribute of `hcloud_server`. That would keep the `hcloud_server` arguments simple and consistent and prevent argument bloat.

Since `ssh_keys` also uses the "name or ID" pattern: Is that argument also prone to this type of problem?
