### ISSUE TITLE
[Bug]: Terraform adding/removing alias_ips without code change

### ISSUE THREAD

**Issue by furstenbergs** [hetznercloud/terraform-provider-hcloud#724]
### What happened?

I'm assigning an alias IP to my resource. On the first Terrafrom run, the alias IPs get added to the resources. For example:

```
  network {
    network_id = hcloud_network.hyve-private.id
    ip         = "10.100.0.2"
    alias_ips  = [
      "10.100.127.1",
      "10.100.127.10"
    ]
  }
```
However on subsequent run it is removing the alias IPs, without any code changes. 
```
  ~ resource "hcloud_server_network" "fw-network-az1" {
      ~ alias_ips   = [
          - "10.100.127.1",
          - "10.100.127.10",
        ]
        id          = "34979676-3130818"
        # (4 unchanged attributes hidden)
    }
```
Then on the next it it is added back and so it continues

I've tried different versions of Terraform, including 1.3.8, 1,4,1 but the issue remains. Also tried with older versions of the hcloud provider with no luck.

### What did you expect to happen?

The alias_ips should remain and not get removed and added on runs. 

### Please provide a minimal working example

```
terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
      version = "1.41.0"
    }
  }
}

provider "hcloud" {
  token = var.hcloud_token
}

resource "hcloud_server" "firewall-az1" {
  name                  = "test"
  image                 = ubuntu-22.04
  server_type           = cpx31
  location              = fsn1
  network {
    network_id = hcloud_network.hyve-private.id
    ip         = "10.100.0.2"
    alias_ips  = [
      "10.100.127.1",
      "10.100.127.10"
    ]
  }
  public_net {
    ipv4_enabled        = true
    ipv6_enabled        = false
  }
}
```

**Comment by apricote** [comment]
Hey @furstenbergs,

sorry for the late response.

I have trouble reproducing this. Can you send debug logs for it? You can generate logs by running `TF_LOG=TRACE TF_LOG_PATH=gh-724.log terraform apply`. You can then send the logs to me (`julian.toelle <at> hetzner-cloud.de`)
