### ISSUE TITLE
[Feature]:  Support new CPU Typs: dedicated vCPU AMD processor

### ISSUE THREAD

**Issue by hegerdes** [hetznercloud/terraform-provider-hcloud#742]
### What whould you like to see?

On the 23rd of agust you announced new CPUs for the hcloud enviorment with [this blog post](https://docs.hetzner.cloud/whats-new)

Please enable the usage of these servers with terrafrom

Currently these servers can not be provisioned with terraform:
 * ccx13
 * ccx23
 * ccx33
 * ccx43
 * ccx53
 * ccx63

**Comment by apricote** [comment]
Hello,

this should already be supported. I just tested it with this configuration.

```terraform
resource "hcloud_server" "tf_742" {
  name        = "gh-742"
  image       = "ubuntu-22.04"
  server_type = "ccx13"
  location    = "fsn1"

  ssh_keys           = ["julian.toelle"]
}
```

Can you share your configuration that fails and the error message (similar to the Bug issue template)?

**Comment by hegerdes** [comment]
When your own deeply nested module setup with proper validation bites your butt instead of helping you. Sorry, added the new server types to my validation set.
