### ISSUE TITLE
[Bug]: some documentation issues

### ISSUE THREAD

**Issue by zoro16** [hetznercloud/terraform-provider-hcloud#757]
### What happened?

Hi,

I was going through the documentation and trying out creating resources and I found out the following issues.

### Primary IP

<https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/primary_ip>

`id` is added as an Argument, but it's *an invalid or unknown key*

### RDNS

<https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/rdns>

`server_id - (Required, int) The server the ip_address belongs to.` is unnecessarily add to most of the arguments.

### Load Balancer Service

<https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/load_balancer_service>

- `load_balancer_id` is listed as a *(Required, string)*, but I think it should be and *int*
- `http` and `health_check` arguments are listed as *(Optional, list)*, but they are actually Blocks. Also an example for their use will be really appreciated.

### Managed Certificate 

https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/managed_certificate

Argument should be `domain_names` not `domains`

**Comment by apricote** [comment]
Thanks a lot for the reports @zoro16, will be fixed by #760.

After we switch to the new plugin framework (#752) I hope we can also autogenerate our docs from the actual schema using [terraform-plugin-docs](https://github.com/hashicorp/terraform-plugin-docs) to avoid these types of errors.
