### ISSUE TITLE
[Feature]: server resource documentation update

### ISSUE THREAD

**Issue by mo9a7i** [hetznercloud/terraform-provider-hcloud#758]
### What whould you like to see?

Hello Hetzner,

Thanks for the wonderful code, infrastructure and overall service.
Just noticed something in the documentation of the provider, not sure if I should report it as a bug or feature request.

The example in the `server` resource page states
```hcl
# Link a managed ipv4 but autogenerate ipv6
resource "hcloud_server" "server_test" {
  //...
  public_net {
    ipv4_enabled = true
    ipv4 = hcloud_primary_ip.primary_ip_1.id
    ipv6_enabled = false
  }
  //...
}
```

while `ipv66_enabled` is set to `false`, either to update the comment, or change `ipv6_enabled` to `true`

Thanks.
**Mohannad**

**Comment by apricote** [comment]
Thanks a lot for the report @mo9a7i! Will be fixed by #760.
