### ISSUE TITLE
[Bug]: poll_interval not working

### ISSUE THREAD

**Issue by beagleknight** [hetznercloud/terraform-provider-hcloud#761]
### What happened?

We are trying to use Hetzner as our cloud provider to deploy development machines using https://coder.com/
Our template `provider` is configured like this:

```terraform
provider "hcloud" {
  poll_interval = "30000ms"
}
```

However, when we deploy a new workspace, we observe that we are sending requests to the Hetzner API every ~500ms (the default value of `poll_interval`).

We double-checked that this provider is being used during the plan because we tried to change the `token` field using a bad one, and it rejects as an invalid token.

### What did you expect to happen?

We expect the `poll_interval` value to be used instead of the default one.

### Please provide a minimal working example

```terraform
terraform {
  required_providers {
    coder = {
      source  = "coder/coder"
      version = "~> 0.12.1"
    }
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "1.43.0"
    }
  }
}

provider "coder" { }

provider "hcloud" {
  poll_interval = "30000ms"
}


resource "hcloud_server" "root" {
  name        = "my-server"
  server_type = "cx41"
  # ...
}
```

**Comment by beagleknight** [comment]
I was checking the source code and I realized that the `backoff` strategy depends on retries and it is only executed for some particular http response codes:
https://github.com/hetznercloud/hcloud-go/blob/d6505ac13d68be8d52e9bfd8a483f68cf821a2f4/hcloud/client.go#L289C1-L290C1

In our case, when we are creating the `server`, terraforming is polling the `/v1/actions` endpoint, and it is receiving a `200 OK` so we keep hammering the API to check when the `server` is created.

**Comment by jooola** [comment]
Nice catch, I think we assign the function the wrong variable:

https://github.com/hetznercloud/hcloud-go/blob/d6505ac13d68be8d52e9bfd8a483f68cf821a2f4/hcloud/client.go#L128

This should assign it to:

https://github.com/hetznercloud/hcloud-go/blob/d6505ac13d68be8d52e9bfd8a483f68cf821a2f4/hcloud/client.go#L62

**Comment by jooola** [comment]
A fix is on the way, it should be fixed next week.

**Comment by apricote** [comment]
Fixed by #739. Is this blocking you right now? If yes, we can issue a new release this week.

**Comment by fcsonline** [comment]
Right now we are rolling out Coder (it is using Hetzner provider underneath) to all our team, and it is blocking a bit because we get random `rate_limits` and the experience is not good. If you can release it, we would really appreciate it. 🙏

**Comment by apricote** [comment]
Released as https://github.com/hetznercloud/terraform-provider-hcloud/releases/tag/v1.44.0

I also added the Coder Hetzner Cloud template to [our awesome list](https://github.com/hetznercloud/awesome-hcloud/commit/481175d95b2a92c38ba744b18713e7b5790c20a2) :rocket:

**Comment by fcsonline** [comment]
Thank you so much for your effort! You rock! 💪
