### ISSUE TITLE
[Bug]: `Provider produced invalid plan` after upgrade to v1.44.1

### ISSUE THREAD

**Issue by maxkratz** [hetznercloud/terraform-provider-hcloud#772]
### What happened?

After I upgraded the version of this terraform provider from `1.43.0` to `1.44.1` I get the following error message when running `terraform apply`:

```
Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/hetznercloud/hcloud" planned an invalid value for hcloud_primary_ip.staging-ipv4.labels: planned value cty.MapValEmpty(cty.String) for a non-computed
│ attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

The complete error output for the minimal working example:
```
terraform plan -var-file="secrets.tfvars"
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/hetznercloud/hcloud" planned an invalid value for hcloud_server.test.shutdown_before_deletion: planned value cty.False for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/hetznercloud/hcloud" planned an invalid value for hcloud_server.test.keep_disk: planned value cty.False for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/hetznercloud/hcloud" planned an invalid value for hcloud_server.test.backups: planned value cty.False for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/hetznercloud/hcloud" planned an invalid value for hcloud_server.test.allow_deprecated_images: planned value cty.False for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/hetznercloud/hcloud" planned an invalid value for hcloud_server.test.ignore_remote_firewall_ids: planned value cty.False for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### What did you expect to happen?

I did not expect that the update would break an existing (previously working) configuration.

### Please provide a minimal working example

`secrets.tfvars`:
```
# Hetzner
hcloud_token = "<secret>"
passwd = "123"
```

`main.tf`:
```
resource "hcloud_server" "test" {
  name = "test"
  image = "debian-11"
  server_type = "cpx21"
  location = "nbg1"
  delete_protection = true
  rebuild_protection = true
}
```

`utils.tf`:
```
variable "hcloud_token" {
  description = "Hetzner Cloud token"
  type        = string
  sensitive   = true
}

variable "passwd" {
  description = "Password for the user"
  type        = string
  sensitive   = true
}


terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
      version = "1.44.1"
    }
  }
}

provider "hcloud" {
  token = var.hcloud_token
}
```

**Comment by apricote** [comment]
Seems related to #749. I will take a look.

**Comment by apricote** [comment]
Hey @maxkratz,

I am unable to reproduce the issue with Terraform 1.6.0. What version are you using?

 Could you set these two environment variables during `terraform apply` and send the resulting log file to my email `julian.toelle <at> hetzner-cloud.de`?

`TF_LOG=TRACE TF_LOG_PATH=invalid-plan.log terraform apply`

**Comment by maxkratz** [comment]
> Hey @maxkratz,
> 
> I am unable to reproduce the issue with Terraform 1.6.0. What version are you using?

I'm using Terraform version v1.0.11:
```
$ terraform --version                      
Terraform v1.0.11
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.6.1. You can update by downloading from https://www.terraform.io/downloads.html
```

(It seems very outdated ... I installed it via [this ansible role](https://github.com/robertdebock/ansible-role-terraform) and v1.0.11 seems to be the default version.)

> Could you set these two environment variables during `terraform apply` and send the resulting log file to my email `julian.toelle <at> hetzner-cloud.de`?
> 
> `TF_LOG=TRACE TF_LOG_PATH=invalid-plan.log terraform apply`

Yes, I did set up the two environment variables and ran `$ terraform plan -var-file="secrets.tfvars"`. I've sent the log to your email address.

Thank you for your help.

**Comment by apricote** [comment]
Can you try to install a current version of Terraform (ie 1.5 or 1.6)?

---

Terraform introduced stricter [Data Consistency Checks](https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/data-consistency-errors) in 0.12+,  but these checks should only apply to Resources using the Plugin Framework (#749). We recently added the skaffolding for the new Plugin Framework, but did not migrate any Resources to it yet, so I did not expect anything to fail.

It looks like older versions of Terraform have an issue where they also expect Resources not using the Plugin Framework to conform to the Data Consistency Checks if the provider uses [muxing](https://developer.hashicorp.com/terraform/plugin/framework/migrating/mux).

**Comment by maxkratz** [comment]
I've installed the most recent Terraform version (v1.6.1) and the error seems to be gone. I guess you were right and only the older versions did not like the recent change in the provider's code.
