### ISSUE TITLE
I am unable to create a server with a given static private ip in a private subnet through Ansible

### ISSUE THREAD

**Issue by samiksha1191** [hetznercloud/terraform-provider-hcloud#776]
Hello Hetzner team,

I am trying to create servers with static ip in the hetzner private subnet using this collection **hetzner.hcloud.hcloud_server_network module** 

But I am getting error. 

can you please help to understand the requirement for parameters for this module as I have checked already, the ansible version and the [hetzner.hcloud collection](https://galaxy.ansible.com/ui/repo/published/hetzner/hcloud/) version is already as per the requirement.

**_Below is my code snippet.

    - name: Create a basic network
      hetzner.hcloud.hcloud_network:
        name: "{{ item.name }}"
        ip_range: "{{ item.ip_range }}"
        state: "{{ infrastructure_state }}"
        api_token: "{{ hcloud_token }}"
      with_items: "{{ networks }}"

    - name: Create a basic subnetwork
      hcloud_subnetwork:
        network: network1
        ip_range:  "{{ item.ip_range }}"
        network_zone: eu-central
        type: cloud
        state: present
        api_token: "{{ hcloud_token }}"

    - name: Create a basic server
      hcloud_server:
        name: my-server
        server_type: cx11
        image: ubuntu-22.04
        state: present                                            
        enable_ipv4: false
        enable_ipv6: false
        datacenter: nbg1-dc3
        private_networks:
           - network1
        api_token: "{{ hcloud_token }}"

    - name: Create a server network and specify the ip address
      hcloud_server_network:
        network: network1
        server: my-server 
        ip: 10.0.1.10
        state: present
        api_token: "{{ hcloud_token }}"_**

can you please help here?

**Comment by apricote** [comment]
Hey @samiksha1191,

this is the issue tracker for the Hetzner Cloud _Terraform Provider_. 

Please open your issue [here](https://github.com/ansible-collections/hetzner.hcloud/issues/new/choose)

When you open the issue, please also specify:

- The actual error message you get
- The value of your `item` variable
