### ISSUE TITLE
[Bug]: Not checking for snapshots

### ISSUE THREAD

**Issue by xogoodnow** [hetznercloud/terraform-provider-hcloud#777]
### What happened?

Hi,
When destroying the project, it does not check for snapshots
os if an incremental snapshot has been previously taken from the instance, it would remain there (completely useless :))
since it does not contain the whole image, you can not boot an instance or revert it on anything.
keep in mind that the snapshot has been taken manually and not within the project, I believe it would be better to check for this matter as well.
I do not know whether to consider this a bug or a feature request
p.s: Thank you for your services

### What did you expect to happen?

Expected to check if there are any snapshots present for the instance

### Please provide a minimal working example

1. Just create an instance with any flavor on any region.
2. manually take a snapshot from the instance
3. terraform destroy
4. an orphaned incremental snapshot would remain there

**Comment by apricote** [comment]
Hey @xogoodnow,

a snapshot can be used to boot a new server just fine. This is how the [Packer Plugin](https://github.com/hashicorp/packer-plugin-hcloud) builds and saves images of servers to reuse later. You can read about this in the docs: https://docs.hetzner.com/cloud/servers/getting-started/creating-a-server

In general, Terraform will only remove resources that it knows about, so it wont remove anything that you do create outside of it, unless you import it into the Terraform state.

Based on these two points, I think this is working as intended.

**Comment by xogoodnow** [comment]
hi @apricote,
I understand your point (which is correct), but IMHO it would be better to check if an instance has a snapshot or not.
but you are quite right on "I think this is working as intended".
