### ISSUE TITLE
Please publish 1.9 Terraform plugin binaries

### ISSUE THREAD

**Issue by loxal** [hetznercloud/terraform-provider-hcloud#81]
My company's server portfolio at Hetzner is 50+ and we extensively use Terraform for provisioning Hetzner VMs. However recently I wanted to introduce volumes... I got 

> Error: hcloud_volume.master: : invalid or unknown key: automount

because apparently v1.5 of the Terraform plugin does not support the `automount` keyword. However I cannot find any newer Terraform plugin binaries. Could you please provide those binaries as just doing `make install` does not work and I really do not have the time or the passion to dive into Golang tooling.

**Comment by LKaemmerling** [comment]
You just need to run `terraform init -upgrade` again. You don't need to download the binaries yourself.

https://www.terraform.io/docs/commands/init.html#plugin-installation

**Comment by loxal** [comment]
> terraform init -upgrade
> Upgrading modules...
> - module.iFinder
>   Updating source "intrafind/iFinder"
> 
> Initializing the backend...
> 
> Initializing provider plugins...
> - Checking for available provider plugins on https://releases.hashicorp.com...
> - Downloading plugin for provider "google" (2.4.0)...
> - Downloading plugin for provider "null" (2.1.1)...
> 
> The following providers do not have any version constraints in configuration,
> so the latest version was installed.
> 
> To prevent automatic upgrades to new major versions that may contain breaking
> changes, it is recommended to add version = "..." constraints to the
> corresponding provider blocks in configuration, with the constraint strings
> suggested below.
> 
> * provider.google: version = "~> 2.4"
> * provider.hcloud: version = "~> 1.5"
> * provider.null: version = "~> 2.1"
> 
> Terraform has been successfully initialized!
> 

Still, I get the same error: 

> Error: hcloud_volume.master: : invalid or unknown key: automount


@LKaemmerling

**Comment by LKaemmerling** [comment]
I have tested it, it works with Terraform v0.11.13

You just need to call:
` terraform init -upgrade=true`

**Comment by loxal** [comment]
> terraform init -upgrade=true
> Upgrading modules...
> - module.iFinder
>   Updating source "intrafind/iFinder"
> 
> Initializing the backend...
> 
> Initializing provider plugins...
> - Checking for available provider plugins on https://releases.hashicorp.com...
> - Downloading plugin for provider "null" (2.1.1)...
> - Downloading plugin for provider "google" (2.4.0)...
> 
> The following providers do not have any version constraints in configuration,
> so the latest version was installed.
> 
> To prevent automatic upgrades to new major versions that may contain breaking
> changes, it is recommended to add version = "..." constraints to the
> corresponding provider blocks in configuration, with the constraint strings
> suggested below.
> 
> * provider.google: version = "~> 2.4"
> * provider.hcloud: version = "~> 1.5"
> * provider.null: version = "~> 2.1"


>  terraform version
> Terraform v0.11.13
> + provider.google v2.4.0
> + provider.hcloud v1.5.0
> + provider.null v2.1.1

...is what I've got. I looks like my setup ist stuck with v1.5.0 that does not support `automount`. I am using gcs as terraform state storage but the Terraform plugins are stored in the local `.terraform` directory only and not synced as part of the Terraform state?

@LKaemmerling

**Comment by LKaemmerling** [comment]
Could you try to set the version in your provider configuration to `1.9.0` ?

**Comment by loxal** [comment]
Great, the snippet below, solved the problem for me! @LKaemmerling 

> provider "hcloud" "Hetzner" {
>   token = "${var.hetzner_cloud_analyze_law}"
>   version = "1.9.0"
> }
