### ISSUE TITLE
ci(e2e): make debug logs available

### ISSUE THREAD

**Issue by apricote** [hetznercloud/terraform-provider-hcloud#814]
### What whould you like to see?

When an issue happens in the e2e tests, we can not properly debug it and must hope that we can reproduce it locally.

It would be awesome if we generated full debug/trace logs including the Hetzner Cloud API requests, to make debugging issues easier.

Logs can be generated by running with `TF_LOG=TRACE TF_LOG_PATH=e2e.log make testacc`.

**Comment by jooola** [comment]
I believe this was solved in #835 
The hcloud go requests are logged as well.
