### ISSUE TITLE
terraform error - ipv4_address_private' for variable 'hcloud_server.www-1.ipv4_address_private'

### ISSUE THREAD

**Issue by alexongotos** [hetznercloud/terraform-provider-hcloud#83]
Hi, 
I am running a terraform file that is creating an haproxy server in front of to nginx servers.

the 2 nginx servers get created but the haproxy server provisioner section fails with these two lines...

``"sudo sed -i 's/WWW_1_PRIVATE_IP/${hcloud_server.www-1.ipv4_address_private}/g' /etc/haproxy/haproxy.cfg",
      "sudo sed -i 's/WWW_2_PRIVATE_IP/${hcloud_server.www-2.ipv4_address_private}/g' /etc/haproxy/haproxy.cfg",``

In the editor if I pause on the ${hcloud_server.www-1.ipv4_address_private} its says ipv4_address_private - not specified.

Do i need to pay for two floating IP4 IPs for this to work?
Converting this terraform script from one that worked on Digitaloceon using the same lines...
many thanks

**Comment by alexongotos** [comment]
This is the screen listing...

 terraform apply
hcloud_server.www-2: Refreshing state... (ID: 2511202)
hcloud_server.www-1: Refreshing state... (ID: 2511203)
hcloud_server.haproxy-www: Refreshing state... (ID: 2511211)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

-/+ hcloud_server.haproxy-www (tainted) (new resource required)
      id:            "2511211" => <computed> (forces new resource)
      backup_window: "" => <computed>
      backups:       "false" => "false"
      datacenter:    "nbg1-dc3" => <computed>
      image:         "ubuntu-16.04" => "ubuntu-16.04"
      ipv4_address:  "116.203.128.205" => <computed>
      ipv6_address:  "2a01:4f8:c2c:5055::" => <computed>
      ipv6_network:  "2a01:4f8:c2c:5055::/64" => <computed>
      keep_disk:     "false" => "false"
      location:      "nbg1" => "nbg1"
      name:          "haproxy-www" => "haproxy-www"
      server_type:   "cx11" => "cx11"
      ssh_keys.#:    "1" => "1"
      ssh_keys.0:    "elay15@Eddies-MacBook-Pro.local" => "elay15@Eddies-MacBook-Pro.local"
      status:        "running" => <computed>


Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

hcloud_server.haproxy-www: Destroying... (ID: 2511211)
hcloud_server.haproxy-www: Destruction complete after 1s
hcloud_server.haproxy-www: Creating...
  backup_window: "" => "<computed>"
  backups:       "" => "false"
  datacenter:    "" => "<computed>"
  image:         "" => "ubuntu-16.04"
  ipv4_address:  "" => "<computed>"
  ipv6_address:  "" => "<computed>"
  ipv6_network:  "" => "<computed>"
  keep_disk:     "" => "false"
  location:      "" => "nbg1"
  name:          "" => "haproxy-www"
  server_type:   "" => "cx11"
  ssh_keys.#:    "" => "1"
  ssh_keys.0:    "" => "elay15@Eddies-MacBook-Pro.local"
  status:        "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* hcloud_server.haproxy-www: Resource 'hcloud_server.www-1' does not have attribute 'ipv4_address_private' for variable 'hcloud_server.www-1.ipv4_address_private'

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by LKaemmerling** [comment]
Hey, the hcloud_server does not have an attribute called „ipv4_address_private“. You can See all available Attributes under https://www.terraform.io/docs/providers/hcloud/r/server.html#inner .
