### ISSUE TITLE
[Bug]: Destroying server gracefully with attached volume not possible because of incorrect ordering

### ISSUE THREAD

**Issue by peterhirn** [hetznercloud/terraform-provider-hcloud#830]
### What happened?

Using `shutdown_before_deletion` on a server with attached volume will detach the volume first, then shutdown the server. This is obviously not expected on the server and will corrupt data (mounted device just disappears).

```
hcloud_volume_attachment.monitoring: Destroying... [id=100163788]
hcloud_volume_attachment.monitoring: Destruction complete after 4s
hcloud_server.server: Destroying... [id=41604715]
...
```

`hcloud_volume` and `hcloud_volume_attachment` depend on the server-id, so it makes sense for terraform to destroy the volume/attachment first.

Because of this I'm unable to force a correct order by using

```
depends_on = [
  hcloud_volume_attachment.monitoring
]
```

as this is a cyclic dependency

```console
Error: Cycle: hcloud_volume_attachment.monitoring, hcloud_server.server
```

I also tried setting `create_before_destroy` on the `hcloud_volume_attachment`, which doesn't work (tries to create new server with identical name first).

### What did you expect to happen?

Server should shutdown first.

- `hcloud_server` should be able to depend on `volume` or `volume_attachment`
- alternatively `volume_attachment` could have a `shutdown_server_first` field

### Please provide a minimal working example

https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/volume

**Comment by peterhirn** [comment]
## Workaround

```tf
resource "null_resource" "shutdown" {
  depends_on = [hcloud_volume_attachment.data]

  triggers = {
    hcloud_token = var.hcloud_token
    server_id    = hcloud_server.server.id
  }

  provisioner "local-exec" {
    when        = destroy
    interpreter = ["bash"]
    command     = "${path.module}/utils/shutdown.sh"

    environment = {
      HCLOUD_TOKEN = nonsensitive(self.triggers.hcloud_token)
      SERVER_ID    = self.triggers.server_id
      TIMEOUT      = 90
      SKIP         = false
    }
  }
}
```

`utils/shutdown.sh`
```bash
#!/usr/bin/env bash
set -euo pipefail

if [ "${SKIP}" = "true" ]; then exit 0; fi

echo Shutdown ${SERVER_ID}

curl --fail --no-progress-meter \
	-X POST \
	-H "Authorization: Bearer ${HCLOUD_TOKEN}" \
	https://api.hetzner.cloud/v1/servers/${SERVER_ID}/actions/shutdown

echo Waiting for status: off

for i in $(seq ${TIMEOUT}); do
	status=$(curl --fail --no-progress-meter \
		-H "Authorization: Bearer ${HCLOUD_TOKEN}" \
		https://api.hetzner.cloud/v1/servers/${SERVER_ID} | jq -r '.server.status')

	if [ "${status}" = "off" ]; then break; fi
	if [[ $i -eq ${TIMEOUT} ]]; then exit 1; fi
	sleep 1
done
```

### Notes

- I've been using this for a week (~50x destroy and recreate) and it seems very stable.
- The `triggers` variables are captured on create, which means if you change `hcloud_token` the shutdown will fail. I added a `SKIP` variable for this case.
- This runs perfectly fine on Terraform Cloud: all used tools (bash, curl, jq) are available.
- Additional features of this hack compared to `shutdown_before_deletion`
  - configurable timeout
  - bail on shutdown error

**Comment by sLite** [comment]
also stumbled into this, we are running a postgres cluster on top of external volumes and this is kind of a dealbreaker.

are there any plans to fix this in the provider or is the workaround the only option?

**Comment by peterhirn** [comment]
A proper solution would be great. Capturing the trigger variables and forcing the token to be `nonsensitive` is janky and probably a security risk.

Maybe it is unfeasible to reverse the dependency `hcloud_volume_attachment -> hcloud_server`?

As this issue was closed as stale without response, I don't think anyone will ever look at it again unless you make some noise.

**Comment by sLite** [comment]
i think de dependency is dictated by hetzner here. you also have to detach
before destroy in their web ui. but you can manually shutdown the server
first there.

just don't know if something like this possible with terraforms dependency
handling, don't know too much about the internal workings of that.

maybe a shutdown_server_before_detach for the attachment itself would be a
more appropriate solution.
