### ISSUE TITLE
[Bug]: hcloud_primary_ip is not destorying when user run terraform destroy

### ISSUE THREAD

**Issue by garry-t** [hetznercloud/terraform-provider-hcloud#840]
### What happened?

If you create primary_ip with `auto_delete=false` resource is not destroying. 

### What did you expect to happen?

All primary IPs should be deleted if user run terraform destroy. It is only should be error when `deletion_protection` enabled

### Please provide a minimal working example

```terraform 

terraform {
  required_version =">=1.2.4"
  required_providers {
    consul = {
      source = "hashicorp/consul"
      version = "2.15.1"
    }
    hcloud = {
      source = "hetznercloud/hcloud"
      version = "1.34.3"
    }
  }
}

resource "hcloud_primary_ip" "main" {
  name          = "primary_ip_test"
  datacenter    = "fsn1-dc14"
  type          = "ipv4"
  assignee_type = "server"
  auto_delete   = true
  labels = {
    "hallo" : "welt"
  }
}
// Link a server to a primary IP
resource "hcloud_server" "server_test" {
  name        = "test-server"
  image       = "ubuntu-20.04"
  server_type = "cx11"
  datacenter  = "fsn1-dc14"
  labels = {
    "test" : "tessst1"
  }
  public_net {
    ipv4 = hcloud_primary_ip.main.id
  }

}
```

**Comment by apricote** [comment]
Hey @garry-t,

I am a little bit confused by your description. In the first sentence you mention `auto_delete=false` and then your example uses `auto_delete=true`.

With terraform, you should in the best case use `auto_delete=false`, otherwise deleting the server will also delete the Primary IP.

I noticed that you specify version `1.34.3` for the hcloud provider. This release is 1.5 years old and was one of the first to add support for Primary IPs. Please upgrade to a recent release, as we have fixed many bugs related to Primary IPs since then.

**Comment by garry-t** [comment]
@apricote  Hi. 
For my understanding `auto_delete=false` preserves IPs even if we completely remove resources?

**Comment by apricote** [comment]
The documentation for this field in the provider is pretty bad.

From our [API Docs](https://docs.hetzner.cloud/#primary-ips-update-a-primary-ip):

> Delete this Primary IP when the resource it is assigned to is deleted

- `auto_delete=true` => IP is deleted when the attached server is deleted
  - this is done for compatibility with the existing behaviour of IPs before the Primary IP feature was added
- `auto_delete=false` => When the resource/server is deleted, the Primary IP is detached but kept around

When you destroy the resource in terraform, it will be deleted either way.

**Comment by garry-t** [comment]
@apricote Thanks for clarification. I rechecked with `1.45.0` and now its really delete when all resource are destroyed. 
So in my case it was old version of provider, that's why IPs persists even after destroy.
Closing.
