### ISSUE TITLE
[Bug]: In case you use hcloud_primary_ip as separate resource and you want to taint VM and recreate, first apply always fails

### ISSUE THREAD

**Issue by garry-t** [hetznercloud/terraform-provider-hcloud#842]
### What happened?

If you want to update server independently from `hcloud_primary_ip ` resource it will fails, since api not wait while IP deallocate state and try assign IP to a new instance. This behaviour leads to fails during apply

### What did you expect to happen?

terraform provider waits while resource remove link to an old server and then proceed with creation new server only.

### Please provide a minimal working example

```terraform
resource "hcloud_primary_ip" "main" {
  name          = "primary_ip_test"
  datacenter    = "fsn1-dc14"
  type          = "ipv4"
  assignee_type = "server"
  auto_delete   = true
  labels = {
    "hallo" : "welt"
  }
}
// Link a server to a primary IP
resource "hcloud_server" "server_test" {
  name        = "test-server"
  image       = "ubuntu-20.04"
  server_type = "cx11"
  datacenter  = "fsn1-dc14"
  labels = {
    "test" : "tessst1"
  }
  public_net {
    ipv4 = hcloud_primary_ip.main.id
  }

}
```
terraform 1.6.6
hetznercloud/hcloud 1.44.0
`terraform taint 2` (server_test)
`terraform apply`

**Comment by apricote** [comment]
Hey @garry-t,

we do not recommend using `auto_delete = true` for precisely the reason you encountered here. Please use `auto_delete = false`(default) to keep the IP available for the next server.

**Comment by garry-t** [comment]
@apricote I think here is typo. `auto_delete   = false` I copied it from example :).
https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/primary_ip. 
Tried with latest provider version. Not reproduced.

```terraform 
hcloud = {
      source = "hetznercloud/hcloud"
      version = "1.45.0"
    }

resource "hcloud_primary_ip" "managed_ipv4" {
  for_each      = var.managed_primary_ip ? local.server_set : []
  name          = format("ip-%s", each.value)
  type          = "ipv4"
  assignee_type = "server"
  datacenter    = regex("(fsn1|nbg1)", each.value)[0] == "fsn1" ? "fsn1-dc14" : "nbg1-dc3"
  auto_delete   = false
  labels        = {
    component = var.name_prefix
  }
}
```
