### ISSUE TITLE
Adding `hcloud_floating_ip` `ip_address` as a variable to `template_file` forces resources replacement

### ISSUE THREAD

**Issue by artem-fw** [hetznercloud/terraform-provider-hcloud#85]
Hi guys.

I’m quite new to terraform. For now i’m working with it to create a mongo cluster of 3(by default) hetzner nodes with associated floating ip’s. Also I need an ability to add some more hetzner members there, and this was done by giving correct `count` option via variable that named `members_count` in example below.

It works fine, but changing `members_count` variable to a bigger value forces terraform to destroy and create replacement for all existed `hcloud_floating_ip_assignment` and this confuses me.

But bigger problem happened when I tried to add a `hcloud_floating_ip` `ip_address` to `template_file` variable. In this situation changing `members_count` variable to a bigger value forces terraform to recreate all existed `hcloud_server` resources. I see no reason for this because I can not find a thing that is changed in `user_data`. Recreated nodes contains same `floating ip` as before recreation.

My config is:
`go version -> 1.12.5`
`terraform version -> 0.11.13`
`terraform-provider-hcloud -> 1.9.0`

My code:
```
data "template_file" "hetzner_member" {
  count    = "${var.members_count}"
  template = "${file("${path.module}/templates/hetzner_provision.sh.tpl")}"

  vars {
    server_ip_address = "${element(hcloud_floating_ip.floating_ip.*.ip_address, count.index)}"
  }
}

resource "hcloud_server" "member" {
  count       = "${var.members_count}"
  name        = "member-${count.index}"
  image       = "ubuntu-18.04"
  server_type = "${var.members_type}"
  location    = "${var.members_location}"
  user_data   = "${data.template_file.hetzner_member.*.rendered[count.index]}"
}

resource "hcloud_floating_ip" "floating_ip" {
  count         = "${var.members_count}"
  home_location = "${var.members_location}"
  type          = "ipv4"
}

resource "hcloud_floating_ip_assignment" "member_floating_ip" {
  count          = "${var.members_count}"
  floating_ip_id = "${element(hcloud_floating_ip.floating_ip.*.id, count.index)}"
  server_id      = "${element(hcloud_server.member.*.id, count.index)}"
}
```

I expected that previously created resources will stay as they are without replacement and only new resources will be created.

Please give me an advice what should I fix in my code, because I’d like to avoid senseless resource recreation.

**Comment by LKaemmerling** [comment]
Please keep in mind, that terraform always refers the current state of you infrastructure (or: it tries to archive the state you described).

The problem on this is, that the indexes of the template file will be changed, so terraform assume that there is a change. It will trigger than the recreation. This is not a `bug` on our side. You need to go to the terraform repository directly. https://github.com/hashicorp/terraform

**Comment by artem-fw** [comment]
ok. Thank you for your answer.
