### ISSUE TITLE
Update for terraform 0.12

### ISSUE THREAD

**Issue by farcaller** [hetznercloud/terraform-provider-hcloud#86]
Now that terraform 0.12 is released, hetzner cloud is broken:

```
Error: Failed to instantiate provider "hcloud" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
```

Please update the code to support terraform 0.12 as it comes with a magnitude of important improvements.

**Comment by LKaemmerling** [comment]
With the latest Version we are 0.12 ready (release 1.10.0)
