### ISSUE TITLE
[Feature]: Allow Assigning Public Floating IPs to Load Balancers while also letting them join private networks.

### ISSUE THREAD

**Issue by sharkymcdongles** [hetznercloud/terraform-provider-hcloud#867]
### What whould you like to see?

I am trying to attach a load balancer to a private network for my k3s cluster. I can do this fine using network_id. I cannot do this if I specify my floating IP though because the private network doesn't contain my floating IP.

I also cannot get subnet_ids anyway I have tried to.

**Comment by apricote** [comment]
Hey @sharkymcdongles,

> I am trying to attach a load balancer to a private network for my k3s cluster. I can do this fine using network_id. I cannot do this if I specify my floating IP though because the private network doesn't contain my floating IP.

It is not possible to specify a Floating IP as a target for the Load Balancer. You will get an error `cannot add IP to load balancer: IP belongs to Hetzner Cloud resource (cloud_resource_ip_not_allowed)`. Only IPs from Robot Servers are supported for this. To add a server you need to use `type = "server"` and `server_id = ...`. Floating IPs are also always a publicly routed IP, there is no way to access the Floating IP through the private network.

Perhaps I am misunderstanding what you are trying to do. Could you explain it a bit more and post some example terraform code for me to check against?

> I also cannot get subnet_ids anyway I have tried to.

The `subnet_id` is faked inside the terraform-provider-hcloud to help terraform get the right dependency order. You can get it from the `hcloud_network_subnet` resource. Note that its not possible to force the subnet from which an IP is taken when assigning Load Balancers or Servers to the Network. You will need to manually manage the IPs if you want an IP from a specific subnet.
