### ISSUE TITLE
remote-exec provisioner has no host in its connection

### ISSUE THREAD

**Issue by fcanovai** [hetznercloud/terraform-provider-hcloud#87]
I'm creating a vm and running a remote-exec provisioner.

The logs show that the provisioner tries connecting to the server until it times out. The host it's trying to connect to, however, seems to be missing:

```
hcloud_server.vm[0]: Still creating... [1m20s elapsed]
hcloud_server.vm[0] (remote-exec): Connecting to remote host via SSH...
hcloud_server.vm[0] (remote-exec):   Host:
hcloud_server.vm[0] (remote-exec):   User: root
hcloud_server.vm[0] (remote-exec):   Password: false
hcloud_server.vm[0] (remote-exec):   Private key: false
hcloud_server.vm[0] (remote-exec):   Certificate: false
hcloud_server.vm[0] (remote-exec):   SSH Agent: true
hcloud_server.vm[0] (remote-exec):   Checking Host Key: false
```

This is how the vm is created:

```
resource "hcloud_server" "vm" {
  count       = 1
  name        = "provisionertest"
  image       = "ubuntu-18.04"
  server_type = "cx11"
  datacenter  = "nbg1-dc3"
  ssh_keys    = [ "francesco" ]

  provisioner "remote-exec" {
    inline = [
      "apt update",
    ]
  }
}
```

The provisioner works correctly if I specify the connection:

```
  provisioner "remote-exec" {
    connection {
      host = self.ipv4_address
    }
    inline = [
      "apt update",
    ]
  }
```

```
hcloud_server.vm[0] (remote-exec): Connecting to remote host via SSH...
hcloud_server.vm[0] (remote-exec):   Host: 159.69.109.97
hcloud_server.vm[0] (remote-exec):   User: root
hcloud_server.vm[0] (remote-exec):   Password: false
hcloud_server.vm[0] (remote-exec):   Private key: false
hcloud_server.vm[0] (remote-exec):   Certificate: false
hcloud_server.vm[0] (remote-exec):   SSH Agent: true
hcloud_server.vm[0] (remote-exec):   Checking Host Key: false
hcloud_server.vm[0]: Still creating... [30s elapsed]
hcloud_server.vm[0] (remote-exec): Connected!
```

I was able to run the provisioner without the need to specify the host before migrating to terraform 0.12 and terraform-provider-hcloud 1.10.0.

**Comment by LKaemmerling** [comment]
We have entered this issue today on our own setup, it looks like this is an terraform 0.12 issue. I have wrote the @terraform guys already.

**Comment by LKaemmerling** [comment]
After talking with @jbardin about it, it is working as expected. The connection is not populatable from a provider side since 0.12 (https://www.terraform.io/upgrade-guides/0-12.html#default-settings-in-connection-blocks)

**Comment by jbardin** [comment]
Thanks for filing this. While the `host` field is required, I see you have no `connection` block at all, and that is causing the validation to be skipped. I filed an issue here to take care that: https://github.com/hashicorp/terraform/issues/21690
