### ISSUE TITLE
DNS entry support

### ISSUE THREAD

**Issue by loxal** [hetznercloud/terraform-provider-hcloud#88]
Currently I use Google to manage my DNS entries. It would be nice if I could leverage Hetzner's DNS infrastructure via Terraform.

**Comment by codeagencybe** [comment]
Any update or feedback about this? 
I'm currently in same situation at GCP DNS and Cloudflare because those are the only 2 that currently are able to manage and automate with Terraform. 

Thanks for updating!

**Comment by jelly** [comment]
It seems they have an API now for DNS https://dns.hetzner.com/api-docs/

**Comment by loxal** [comment]
Yes, just tested 

`curl https://dns.hetzner.com/api/v1/records?zone_id=loxal.net -H 'Auth-API-Token: JDFddSDFJLKsdfjslkafjfsafdU'`

Also there is no complicated mechanism like OAuth2 where you need a master token, to get another token, to do the actual call. Here you just use a fixed token :) 

On the other hand the API seems to be over-engineered. Does one really need paging for DNS records? I mean I saw perfectly robust APIs that return multi-MB bodies. Does one need paging for a few KB DNS data?! But I guess somebody had fun implementing it :laughing:

**Comment by k-nut** [comment]
I agree that this would be very investing. @LKaemmerling could you imagine accepting a PR for this feature or is it something that you think is out of scope for this provider?

**Comment by LKaemmerling** [comment]
Hey,

I think adding support for the Hetzner DNS API to the Hetzner Cloud Terraform provider does not fit well. Unfortunately, the Hetzner DNS API and the Hetzner Cloud API are completely independent APIs. Therefore we won't accept any PRs which implement the DNS API into the Cloud Terraform provider. The preferred way for us would be to create a new Terraform provider.

I know there are people working on clients/automation support for the new DNS API, but
will probably take some time.

**Comment by k-nut** [comment]
Thank you for your quick reply, makes for better planning 🙏

**Comment by c33s** [comment]
also see #183
