### ISSUE TITLE
[Feature]: implement "managed certificates" into hcloud_certificate

### ISSUE THREAD

**Issue by ministry-of-code** [hetznercloud/terraform-provider-hcloud#896]
### What whould you like to see?

If I read and understand the current documentation correctly, there is currently no way to manage "managed certificates" (Letsencrypt certs that are being ordered and auto-renewed from Hetzner and can be attached to load balancer instances) with Terraform and it would be great if you could implement that.

**Comment by apricote** [comment]
Check out [`hcloud_managed_certificate`](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/managed_certificate) for Managed Certificates. Managed and uploaded certs have drastically different fields, so using separate terraform resources makes it easier to use and to implement.

We should update the docs for `hcloud_certificate` to point to both resources 👍

**Comment by ministry-of-code** [comment]
Thanks for pointing me to the right resource! I just did a search for "terraform Hetzner certificates" that was linked to the documentation and I didn't recognised the other "managed" resource at all because the navigation bar with that topic was collapsed.
