### ISSUE TITLE
[Bug]: This configuration does not support Terraform version 1.7.5

### ISSUE THREAD

**Issue by GodAtum360** [hetznercloud/terraform-provider-hcloud#900]
### What happened?

Using hcloud version 1.45.0, on **terraform init** I get the error:

```
Error: Unsupported Terraform Core version
│ 
│   on versions.tf line 7, in terraform:
│    7:   required_version = ">= 1.45.0"
│ 
│ This configuration does not support Terraform version 1.7.5. To proceed, either choose another supported Terraform version or update this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or unexpected behavior.
```

### What did you expect to happen?

Please tell me what hcloud versions are supported my what terraform versions.

### Please provide a minimal working example

```terraform
terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
    }
  }
  required_version = ">= 1.45.0"
}
```

**Comment by apricote** [comment]
Hey @GodAtum360,

your configuration actually specifies the `required_version` of Terraform to `>= 1.45.0`, which Terraform 1.7.5 does not fulfill. You can read about [Provider Requirements](https://developer.hashicorp.com/terraform/language/providers/requirements#requiring-providers) in the official docs. The following code sets the required version of the hcloud Provider:

```
terraform {
  required_providers {
    hcloud = {
      source = "hetznercloud/hcloud"
      version = ">= 1.45.0"
    }
  }
}
```

Hope this new code works for you, feel free to continue posting here if you still have the error with the updated config.
