### ISSUE TITLE
[Bug]: Release v1.46.0 not available on Terraform registry

### ISSUE THREAD

**Issue by xoxys** [hetznercloud/terraform-provider-hcloud#906]
### What happened?

The latest version on the Terraform registry is still v1.45.0 while the GH release already exist.

![image](https://github.com/hetznercloud/terraform-provider-hcloud/assets/3391958/f49b4999-0d8d-4ad3-9a32-a6aa1070444f)

Ref: https://registry.terraform.io/providers/hetznercloud/hcloud/latest

### What did you expect to happen?

GH release in sync with terraform registry

### Please provide a minimal working example

```Shell
$ cat versions.tf 
terraform {
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "1.46.0"
    }
  }
}

$ terraform init 

Initializing the backend...

Initializing provider plugins...
- Finding hetznercloud/hcloud versions matching "1.46.0"...
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hetznercloud/hcloud: no available releases match the given constraints 1.46.0
╵
```

**Comment by xoxys** [comment]
What is a bit weird is that I have used v1.46.0 since a few days already, and it stopped working randomly this morning.

**Comment by jooola** [comment]
I'll have a look.

**Comment by apricote** [comment]
We have not figured out why the `1.46.0` release was not published to the Hashicorp Registry, the webhook on GitHub did not show any calls.

We have now release `1.46.1` which is available on the Hashicorp Registry. Please upgrade to that version.
