### ISSUE TITLE
Predefined private network for server

### ISSUE THREAD

**Issue by webchi** [hetznercloud/terraform-provider-hcloud#92]
Should server be attached to existing private network like in web interface.
Or it should be attaching hcloud_server_network each time?

p.s. also server create apis has array of private networks to be attached https://docs.hetzner.cloud/#servers-create-a-server

**Comment by LKaemmerling** [comment]
If you use the terraform provider, you should use the resource `hcloud_server_network` for attaching a server to a network. 

We know that there is a networks array on the create-server call, but we decided to let it out of the `hcloud_server` resource because the usage with the `hcloud_server_network` is ways more flexible.

**Comment by webchi** [comment]
Ok, but this produce tons of code per server
```
resource "hcloud_server_network" "srvnetwork" {
  server_id = "${hcloud_server.node1.id}"
  network_id = "${hcloud_network.mynet.id}"
  ip = "10.0.1.5"
}
```
Maybe it should be an array of server ids or dynamic block from terraform 0.12?

**Comment by LKaemmerling** [comment]
Why does it produces tons of code? You can always use https://www.terraform.io/docs/configuration/resources.html#count-multiple-resource-instances. As a really easy sample:

```
# Configure the Hetzner Cloud Provider
provider "hcloud" {
  token = "${var.hcloud_token}"
}

resource "hcloud_server" "node" {
  name        = "${format(var.hostname_format, count.index + 1)}"
  image       = "ubuntu-18.04"
  server_type = "${var.hcloud_type}"
  ssh_keys    = "${var.hcloud_ssh_keys}"
  location    = "${var.hcloud_location}"
  count       = "${var.node_count}"
}

resource "hcloud_network" "testnw" {
  name     = "test-network-max-1"
  ip_range = "10.0.0.0/8"
}

resource "hcloud_network_subnet" "foonet" {
  network_id   = "${hcloud_network.testnw.id}"
  type         = "server"
  network_zone = "eu-central"
  ip_range     = "10.0.0.0/24"
}

resource "hcloud_server_network" "srvnw" {
  network_id = "${hcloud_network.testnw.id}"
  server_id  = "${element(hcloud_server.node.*.id, count.index)}"
  ip         = "${cidrhost(hcloud_network_subnet.foonet.ip_range, count.index + 2)}"
  count      = "${var.node_count}"
}

output "public_ips" {
  value = "${hcloud_server.node.*.ipv4_address}"
}

output "private_ips" {
  value = "${hcloud_server_network.srvnw.*.ip}"
}
```
(I have not added the variables here)

With this code, we have created up to 100 servers and attached them to the network. Of course, you don't need to specify the IP on the `hcloud_server_network`. The field is optional, you can let our system choose the IP for you.

**Comment by webchi** [comment]
Ok. This is possible but expected behavior is like in hcloud web ui - attach network when creating server.
![Снимок экрана от 2019-07-12 10-06-20](https://user-images.githubusercontent.com/27108/61109118-c6d90980-a48c-11e9-9462-be608d0c8241.png)

**Comment by LKaemmerling** [comment]
Yep, I understand your concern, but we have chosen to support the most flexible solution for the terraform provider, and we want the `hcloud_server` resource be really thin and not overloaded.
