### ISSUE TITLE
[Feature]: add data source `load_balancer_types`

### ISSUE THREAD

**Issue by simonostendorf** [hetznercloud/terraform-provider-hcloud#945]
### What whould you like to see?

I would like to see a data source to read all existing lb types from the API (like it is already implemented for locations, datacenters and servers).

I don't think there is much more that can be said about this and no further examples can be given. The data sources mentioned above serve as an example.

**Comment by apricote** [comment]
Good suggestion, we should support every single resource in our API.

If anyone wants to pick this up before we get to this, you can check out the patterns we have in the `datacenter` data source. We are currently migrating to a new Terraform Plugin framework, so not every resource lends itself to be copied.

https://github.com/hetznercloud/terraform-provider-hcloud/tree/main/internal/datacenter
