### ISSUE TITLE
[Bug]: rescue for server fails on server creation

### ISSUE THREAD

**Issue by andreashe** [hetznercloud/terraform-provider-hcloud#956]
### What happened?

Received an error when using

`rescue = "linux64"`

this is what it says:

```
│ Error: error during placement (resource_unavailable)
│
│   with hcloud_server.any_server,
│   on main.tf line 123, in resource "hcloud_server" "any_server":
│  123: resource "hcloud_server" "any_server" {
│

```

### What did you expect to happen?

init server and boot into rescue mode

### Please provide a minimal working example

resource "hcloud_server" "any_server" {
 ...
  rescue = "linux64"
...
}

**Comment by jooola** [comment]
@andreashe This error seem to be related to the current shortage for the cx plans, https://status.hetzner.com/incident/aa5ce33b-faa5-4fd0-9782-fde43cd270cf

Could you confirm that you are using a cx server type?

**Comment by andreashe** [comment]
Oh yes, a CX42

The info you linked is not very clear. For me it sounds like; they are simply not availlable all the time.

(meanwhile I spent some more hours to do it by using terraform+bash+API calls)

best regards
