### ISSUE TITLE
hcloud_server remote-exec provisioner connection fails

### ISSUE THREAD

**Issue by nimame** [hetznercloud/terraform-provider-hcloud#96]
In my setup I'm having trouble with the ssh connection that the remote-exec tries to establish with the newly created server. Here is a minimal example:

```terraform
variable "token" {}

provider "hcloud" {
  token = var.token
}

resource "hcloud_server" "host" {
  name        = "host1"
  location    = "nbg1"
  image       = "ubuntu-18.04"
  server_type = "cx11"
  ssh_keys    = ["ssh-key-description"]

  provisioner "remote-exec" {
    inline = [
      "echo remote-exec worked",
    ]
  }
}
```
Before running terraform apply, I confirm that the ssh agent is running using `ssh-add -L`. When applying, the server is created but the remote-exec fails, because the ssh-connection times out:

> module.provider.hcloud_server.host: Creating...
> module.provider.hcloud_server.host: Provisioning with 'remote-exec'...
> ...
> module.provider.hcloud_server.host (remote-exec): Connecting to remote host via SSH...
> module.provider.hcloud_server.host (remote-exec):   Host:
> module.provider.hcloud_server.host (remote-exec):   User: root
> module.provider.hcloud_server.host (remote-exec):   Password: false
> module.provider.hcloud_server.host (remote-exec):   Private key: false
> module.provider.hcloud_server.host (remote-exec):   Certificate: false
> module.provider.hcloud_server.host (remote-exec):   SSH Agent: true
> module.provider.hcloud_server.host (remote-exec):   Checking Host Key: false
> module.provider.hcloud_server.host: Still creating... [10s elapsed]
> ...
> module.provider.hcloud_server.host (remote-exec): Connecting to remote host via SSH...
> module.provider.hcloud_server.host (remote-exec):   Host:
> module.provider.hcloud_server.host (remote-exec):   User: root
> module.provider.hcloud_server.host (remote-exec):   Password: false
> module.provider.hcloud_server.host (remote-exec):   Private key: false
> module.provider.hcloud_server.host (remote-exec):   Certificate: false
> module.provider.hcloud_server.host (remote-exec):   SSH Agent: true
> module.provider.hcloud_server.host (remote-exec):   Checking Host Key: false
> module.provider.hcloud_server.host: Still creating... [5m0s elapsed]
> 
> 
> Error: timeout - last error: dial tcp :22: connect: connection refused

When I lookup the IP address of the created server, I am able to ssh into it using the running agent. So there doesn't seem to be a problem with the agent or the identity.

Regarding my setup: I'm on a Windows machine running terraform in a docker container (the `hashicorp/terraform:0.12.0` image) that in turn uses the auth socket form another container, to avoid having to give the container direct access to any private keys (see [docker-ssh-agent](https://github.com/nardeas/ssh-agent)), like this: 

`docker run --rm -it -v ${PWD}:/app --volumes-from=ssh-agent -e SSH_AUTH_SOCK=/.ssh-agent/socket terraform apply`

**Comment by nimame** [comment]
Just realized that the read-me says Terraform 0.11.x was a requirement. So does this provider not work for Terraform 0.12 ?

**Comment by LKaemmerling** [comment]
This provider works on Terraform 0.12. But as of 0.12 it is a requirement to set the host in the connection itself. For this message i have pinned this issue: https://github.com/terraform-providers/terraform-provider-hcloud/issues/87
