### ISSUE TITLE
[Bug]: Floating IP with provided required fields not creating Floating IPs in platform

### ISSUE THREAD

**Issue by achivi** [hetznercloud/terraform-provider-hcloud#977]
### What happened?

I created the Floating IP as indicated in the TF Provider here - https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/floating_ip

In my case i had labels and type:

```terraform
resource "hcloud_floating_ip" "main" {
  type = "ipv4"
  labels = {
    "test" : "test"
  }
}
```

In terms of Plan and Apply it worked, but in UI it did not show any of the Floating IPs (No error in apply)

Once i updated my floating IP resource to include - name, type, home_location and labels, I had floating IPs created after Apply 

### What did you expect to happen?

To have Floating IPs created in my project, or in case they cannot be created due to missing fields to encounter an error in the plan / apply phase. 

### Please provide a minimal working example

```terraform
resource "hcloud_floating_ip" "main" {
  type = "ipv4"
  labels = {
    "test" : "test"
  }
  home_location = "hel1"
  name = "test-floating-ip"
}
```

Maybe you need to update the docs and validators to include all mandatory fields as in the UI

**Comment by apricote** [comment]
I am unable to reproduce the issue. Running `apply` shows an error with a description of the fields that are required. What version of the provider are you using?

```
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

OpenTofu will perform the following actions:

  # hcloud_floating_ip.main will be created
  + resource "hcloud_floating_ip" "main" {
      + delete_protection = false
      + home_location     = (known after apply)
      + id                = (known after apply)
      + ip_address        = (known after apply)
      + ip_network        = (known after apply)
      + labels            = {
          + "test" = "test"
        }
      + name              = (known after apply)
      + server_id         = (known after apply)
      + type              = "ipv4"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  OpenTofu will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

hcloud_floating_ip.main: Creating...
╷
│ Error: one of home location or server is required
│ 
│   with hcloud_floating_ip.main,
│   on 977.tf line 1, in resource "hcloud_floating_ip" "main":
│    1: resource "hcloud_floating_ip" "main" {
│ 
╵
```

The docs state:

> - [`server_id`](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/floating_ip#server_id) - (Optional, int) Server to assign the Floating IP to.
> - [`home_location`](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/floating_ip#home_location) - (Optional, string) Name of home location (routing is optimized for that location). Optional if server_id argument is passed.

So `home_location` is only optional if `server_id` is set, which it is not in your example. I will update the docs to also have a hint on the `server_id` that it is only optional if `home_location` is set.

**Comment by achivi** [comment]
What happened to me was that apply was completed successfully showing in TF that resources were created but they weren't. (When my resource contained just type) 

Only once I added the name and location it was actually created and seen in the UI

Also, when creating it manually name and location are mandatory fields

**Comment by achivi** [comment]
@apricote Thanks! I think i also was confused as there's a chance i just did plan and not apply 😅
